process.env.COS_MSG_RATE_MAX=process.env.COS_MSG_RATE_MAX||'1000'; /* v35: pagination tests post 45 messages at once */
const test=require('node:test'),assert=require('node:assert/strict'),{DatabaseSync}=require('node:sqlite');
const factory=require('../server/messages');const sz={readNotifs:(db,ws,uid)=>db.prepare('SELECT * FROM notifications WHERE recipient_id=?').all(uid).map(n=>({id:n.id,k:n.type,who:n.actor_id,t:n.entity_id,entityType:n.entity_type})),writeNotif:(db,ws,n)=>db.prepare("INSERT INTO notifications(id,workspace_id,recipient_id,actor_id,type,entity_type,entity_id,message,created_at) VALUES(?,?,?,?,?,?,?,?,datetime('now'))").run(n.id,ws,n.recipient,n.who,n.k,n.entityType,n.t,n.message||'')};
function setup(){const db=new DatabaseSync(':memory:');db.exec("CREATE TABLE teams(id TEXT PRIMARY KEY,workspace_id TEXT,team_lead_id TEXT,is_archived INTEGER DEFAULT 0);CREATE TABLE team_memberships(team_id TEXT,user_id TEXT);CREATE TABLE workspace_members(user_id TEXT,workspace_id TEXT);CREATE TABLE tasks(id TEXT PRIMARY KEY,workspace_id TEXT);CREATE TABLE notifications(id TEXT PRIMARY KEY,workspace_id TEXT,recipient_id TEXT,actor_id TEXT,type TEXT,entity_type TEXT,entity_id TEXT,message TEXT,read_at TEXT,created_at TEXT);INSERT INTO teams VALUES('design','ws','laura',0);INSERT INTO team_memberships VALUES('design','laura'),('design','sarah');INSERT INTO workspace_members VALUES('laura','ws'),('sarah','ws'),('eve','ws'),('zein','ws');INSERT INTO tasks VALUES('T-1','ws');");const routes={};const chat=factory(db,'ws',(m,p,h)=>routes[m+' '+p]=h,sz);return {db,chat,call:(m,p,u,params={},body={},query={})=>routes[m+' '+p](u,params,query,body)};}
const laura={id:'laura',role:'member',caps:{view_messages:true,send_message:true,create_group_chat:true,pin_message:true}},sarah={id:'sarah',role:'member',caps:{view_messages:true,send_message:true}},eve={id:'eve',role:'viewer',caps:{view_messages:true,send_message:true}},zein={id:'zein',role:'member',caps:{view_messages:true,send_message:true,create_group_chat:true}};
test('every team gets exactly one #general and membership follows the team roster (§3.1, §136.3)',()=>{const s=setup();const list=s.call('GET','/api/messages/conversations',laura);assert.equal(list.filter(c=>c.type==='TEAM_DEFAULT').length,1);assert.deepEqual(list[0].members.sort(),['laura','sarah']);assert.equal(s.call('GET','/api/messages/conversations',eve).length,0);s.chat.ensureTeamDefaults();assert.equal(s.db.prepare("SELECT count(*) n FROM conversations WHERE type='TEAM_DEFAULT'").get().n,1);assert.throws(()=>s.call('POST','/api/messages/conversations/:id/leave',laura,{id:'cv_design_general'}),/follows the team/);});
test('DM between two users is unique in both directions (§4, §60)',()=>{const s=setup();const a=s.call('POST','/api/messages/conversations',laura,{},{type:'DM',members:['laura','sarah']});const b=s.call('POST','/api/messages/conversations',sarah,{},{type:'DM',members:['sarah','laura']});assert.equal(a.id,b.id);assert.throws(()=>s.call('POST','/api/messages/conversations',laura,{},{type:'DM',members:['laura','ghost']}),/Choose a member/);});
test('messages: membership enforced, refs validated, pagination cursor, reactions idempotent, read state (§12, §15, §55)',()=>{const s=setup();const cv='cv_design_general';assert.throws(()=>s.call('POST','/api/messages/conversations/:id/messages',eve,{id:cv},{body:'hi'}),/not found/);for(let i=0;i<45;i++)s.call('POST','/api/messages/conversations/:id/messages',laura,{id:cv},{id:'m'+i,body:'msg '+i,refs:i===0?[{type:'TASK',entityId:'T-1'},{type:'TASK',entityId:'T-404'},{type:'URL',url:'javascript:alert(1)'}]:[]});const first=s.call('GET','/api/messages/conversations/:id/messages',sarah,{id:cv},{},{limit:'40'});assert.equal(first.items.length,40);assert.ok(first.nextCursor);const older=s.call('GET','/api/messages/conversations/:id/messages',sarah,{id:cv},{},{limit:'40',before:first.nextCursor});assert.equal(older.items.length,5);assert.equal(older.items[0].refs.length,1,'only the existing task ref survives');assert.equal(s.call('GET','/api/messages/conversations',sarah)[0].unread,45);s.call('POST','/api/messages/:id/reactions',sarah,{id:'m0'},{emoji:'👍'});s.call('POST','/api/messages/:id/reactions',sarah,{id:'m0'},{emoji:'👍'});assert.deepEqual(s.call('GET','/api/messages/conversations/:id/messages',sarah,{id:cv},{},{limit:'50'}).items[0].reactions,{});s.call('PATCH','/api/messages/conversations/:id/read',sarah,{id:cv},{lastReadMessageId:'m44'});assert.equal(s.call('GET','/api/messages/conversations',sarah)[0].unread,0);});
test('mentions, notification levels and fan-out land in the existing notifications table (§46, §142)',async()=>{const s=setup();const cv='cv_design_general';s.call('PATCH','/api/messages/conversations/:id',sarah,{id:cv},{notificationLevel:'MENTIONS'});s.call('POST','/api/messages/conversations/:id/messages',laura,{id:cv},{body:'plain'});s.call('POST','/api/messages/conversations/:id/messages',laura,{id:cv},{body:'@Sarah look',mentions:[{userId:'sarah',display:'Sarah'}]});await new Promise(r=>setTimeout(r,30));const n=s.db.prepare("SELECT type FROM notifications WHERE recipient_id='sarah'").all().map(x=>x.type);assert.deepEqual(n,['chat_mention']);});
test('pins point to messages; groups need 2–20 members; only owner edits (§5, §140)',()=>{const s=setup();const g=s.call('POST','/api/messages/conversations',laura,{},{type:'GROUP',name:'Leads',members:['sarah']});assert.deepEqual(g.members.sort(),['laura','sarah']);const m=s.call('POST','/api/messages/conversations/:id/messages',sarah,{id:g.id},{body:'pin me'});s.call('POST','/api/messages/:id/pin',sarah,{id:m.id});assert.deepEqual(s.call('GET','/api/messages/conversations',laura).find(c=>c.id===g.id).pins,[m.id]);assert.throws(()=>s.call('PATCH','/api/messages/conversations/:id',sarah,{id:g.id},{name:'x'}),/owner/);assert.throws(()=>s.call('POST','/api/messages/conversations',laura,{},{type:'GROUP',name:'solo',members:[]}),/2–20/);s.call('DELETE','/api/messages/:id',sarah,{id:m.id});assert.deepEqual(s.call('GET','/api/messages/conversations',laura).find(c=>c.id===g.id).pins,[]);});

test('archive: any member archives a DM/group for reading only, team channels need manage_team_channel, #general never (§141)',()=>{const s=setup();const g=s.call('POST','/api/messages/conversations',laura,{},{type:'GROUP',name:'G',members:['sarah']});s.call('PATCH','/api/messages/conversations/:id',sarah,{id:g.id},{archived:true});assert.throws(()=>s.call('POST','/api/messages/conversations/:id/messages',laura,{id:g.id},{body:'x'}),/archived/);assert.equal(s.call('GET','/api/messages/conversations',laura).find(c=>c.id===g.id).archivedBy,'sarah');s.call('PATCH','/api/messages/conversations/:id',laura,{id:g.id},{archived:false});s.call('POST','/api/messages/conversations/:id/messages',laura,{id:g.id},{body:'ok again'});assert.throws(()=>s.call('PATCH','/api/messages/conversations/:id',laura,{id:'cv_design_general'},{archived:true}),/together with its team/);const lead={id:'laura',role:'member',caps:{view_messages:true,send_message:true,create_team_channel:true,manage_team_channel:true}};const ch=s.call('POST','/api/messages/conversations',lead,{},{type:'TEAM_CHANNEL',teamId:'design',name:'crit'});assert.throws(()=>s.call('PATCH','/api/messages/conversations/:id',sarah,{id:ch.id},{archived:true}),/team lead or admin/);s.call('PATCH','/api/messages/conversations/:id',lead,{id:ch.id},{archived:true});assert.ok(s.call('GET','/api/messages/conversations',sarah).find(c=>c.id===ch.id).archivedAt);});

test('ordinary URLs are parsed authoritatively, normalized, deduplicated, and synced on edit/delete',()=>{const s=setup(),cv='cv_design_general';const m=s.call('POST','/api/messages/conversations/:id/messages',laura,{id:cv},{id:'url1',body:'See https://example.com/a, https://example.com/a and www.example.org/b. javascript:alert(1)'});assert.equal(m.refs.length,2);assert.deepEqual(m.refs.map(r=>r.normalizedUrl),['https://example.com/a','https://www.example.org/b']);assert.ok(m.refs.every(r=>r.type==='URL'&&r.source==='BODY'));let links=s.call('GET','/api/messages/conversations/:id/refs',laura,{id:cv},{},{kind:'links',limit:'20'});assert.equal(links.items.length,2);const edited=s.call('PATCH','/api/messages/:id',laura,{id:m.id},{body:'Only https://dribbble.com/shots/123 now'});assert.equal(edited.refs.length,1);assert.equal(edited.refs[0].normalizedUrl,'https://dribbble.com/shots/123');s.call('DELETE','/api/messages/:id',laura,{id:m.id});links=s.call('GET','/api/messages/conversations/:id/refs',laura,{id:cv},{},{kind:'links',limit:'20'});assert.equal(links.items.length,0);});

test('media and files are derived from validated MIME classification without duplicate rows',()=>{const s=setup(),cv='cv_design_general';s.call('POST','/api/messages/conversations/:id/messages',laura,{id:cv},{id:'media1',body:'latest',refs:[{type:'FILE',name:'screen.png',mimeType:'image/png',mediaKind:'FILE',preview:'data:image/png;base64,AA=='},{type:'FILE',name:'brief.pdf',mimeType:'application/pdf',mediaKind:'IMAGE'}]});s.call('POST','/api/messages/conversations/:id/messages',laura,{id:cv},{id:'media2',body:'clip',refs:[{type:'FILE',name:'walkthrough.mp4',mimeType:'video/mp4'}]});const media=s.call('GET','/api/messages/conversations/:id/refs',laura,{id:cv},{},{kind:'media',limit:'20'}),files=s.call('GET','/api/messages/conversations/:id/refs',laura,{id:cv},{},{kind:'files',limit:'20'});assert.deepEqual(media.items.map(x=>x.ref.mediaKind).sort(),['IMAGE','VIDEO']);assert.deepEqual(files.items.map(x=>x.ref.name),['brief.pdf']);assert.equal(media.items.some(x=>x.ref.name==='brief.pdf'),false);});

test('v35: sending is rate limited per person and over-long messages are refused, not cut',()=>{const prev=process.env.COS_MSG_RATE_MAX;process.env.COS_MSG_RATE_MAX='30';try{const s=setup();const cv='cv_design_general';
  assert.throws(()=>s.call('POST','/api/messages/conversations/:id/messages',laura,{id:cv},{body:'x'.repeat(4001)}),e=>e.status===413);
  s.call('POST','/api/messages/conversations/:id/messages',laura,{id:cv},{body:'y'.repeat(4000)});
  let blocked=0;for(let i=0;i<40;i++){try{s.call('POST','/api/messages/conversations/:id/messages',sarah,{id:cv},{body:'m'+i});}catch(e){if(e.status===429)blocked++;else throw e;}}
  assert.ok(blocked>=10,'blocked '+blocked);}finally{process.env.COS_MSG_RATE_MAX=prev;}});
