/* v19 §7.7 Decision log — one small table; visibility follows project access (§17). */
const { uid, now } = require('./db');
module.exports = function (db, ws, route) {
  db.exec("CREATE TABLE IF NOT EXISTS decisions (id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL, project_id TEXT, title TEXT NOT NULL, note TEXT DEFAULT '', source_type TEXT, source_id TEXT, task_id TEXT, message_id TEXT, created_by TEXT NOT NULL, created_at TEXT NOT NULL)");
  const error = (code, msg) => { const e = new Error(msg); e.status = code; throw e; };
  const out = r => ({ id: r.id, projectId: r.project_id, title: r.title, note: r.note || '', sourceType: r.source_type, sourceId: r.source_id, taskId: r.task_id, messageId: r.message_id, by: r.created_by, at: r.created_at });
  route('GET', '/api/decisions', u => db.prepare('SELECT * FROM decisions WHERE workspace_id=? ORDER BY created_at DESC').all(ws).map(out));
  route('POST', '/api/decisions', (u, p, q, b) => { const title = String(b.title || '').trim().slice(0, 140); if (!title) error(400, 'Write the decision first.'); const id = /^[-\w]{1,40}$/.test(String(b.id || '')) ? String(b.id) : uid('dc'); { const ex = db.prepare('SELECT created_by FROM decisions WHERE id=? AND workspace_id=?').get(id, ws); if (ex && ex.created_by !== u.id && u.role !== 'admin') error(403, 'You can only edit your own decisions.'); } if (b.projectId && !db.prepare('SELECT 1 FROM projects WHERE id=? AND workspace_id=?').get(String(b.projectId), ws)) error(400, 'Unknown project.'); db.prepare('INSERT INTO decisions(id,workspace_id,project_id,title,note,source_type,source_id,task_id,message_id,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET project_id=excluded.project_id, title=excluded.title, note=excluded.note, source_type=excluded.source_type, source_id=excluded.source_id, task_id=excluded.task_id, message_id=excluded.message_id').run(id, ws, b.projectId ? String(b.projectId) : null, title, String(b.note || '').slice(0, 2000), b.sourceType ? String(b.sourceType) : null, b.sourceId ? String(b.sourceId) : null, b.taskId ? String(b.taskId) : null, b.messageId ? String(b.messageId) : null, u.id, now()); return out(db.prepare('SELECT * FROM decisions WHERE id=?').get(id)); });
  route('DELETE', '/api/decisions/:id', (u, p) => { const d = db.prepare('SELECT * FROM decisions WHERE id=? AND workspace_id=?').get(p.id, ws); if (!d) error(404, 'Decision not found.'); if (d.created_by !== u.id && u.role !== 'admin') error(403, 'Only the author or an admin can remove a decision.'); db.prepare('DELETE FROM decisions WHERE id=?').run(d.id); return { ok: true }; });
};
