/* v18 §11–15, §55–58, §144–147 — Messages server module.
   Durable data lives here; realtime is one Server-Sent-Events transport per
   browser session, multiplexed: a user inbox stream plus the ONE active
   conversation the client subscribed to. Typing/presence are ephemeral.
   Notifications are written through the existing notifications table. */
const { uid, now, tx } = require('./db');
const dns = require('node:dns').promises;
const dnsCb = require('node:dns');
const http = require('node:http');
const https = require('node:https');
const { Readable } = require('node:stream');
const net = require('node:net');
module.exports = function (db, ws, route, deps) {
  const { readNotifs, writeNotif, onNotification } = deps || {};
  db.exec(`
    CREATE TABLE IF NOT EXISTS conversations (id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL, team_id TEXT, project_id TEXT, type TEXT NOT NULL, name TEXT, description TEXT DEFAULT '', created_by TEXT NOT NULL, created_at TEXT NOT NULL, archived_at TEXT, archived_by TEXT, dm_key TEXT);
    CREATE UNIQUE INDEX IF NOT EXISTS conversations_dm ON conversations(workspace_id, dm_key) WHERE dm_key IS NOT NULL;
    CREATE UNIQUE INDEX IF NOT EXISTS conversations_team_default ON conversations(workspace_id, team_id) WHERE type='TEAM_DEFAULT';
    CREATE TABLE IF NOT EXISTS conversation_members (conversation_id TEXT NOT NULL, user_id TEXT NOT NULL, role TEXT DEFAULT 'member', joined_at TEXT NOT NULL, last_read_message_id TEXT, last_read_at TEXT, notification_level TEXT DEFAULT 'ALL', starred INTEGER DEFAULT 0, PRIMARY KEY(conversation_id, user_id));
    CREATE TABLE IF NOT EXISTS messages (id TEXT PRIMARY KEY, conversation_id TEXT NOT NULL, sender_id TEXT NOT NULL, type TEXT DEFAULT 'TEXT', body TEXT DEFAULT '', mentions TEXT DEFAULT '[]', refs TEXT DEFAULT '[]', reply_to_message_id TEXT, created_at TEXT NOT NULL, edited_at TEXT, deleted_at TEXT);
    CREATE INDEX IF NOT EXISTS messages_cursor ON messages(conversation_id, created_at, id);
    CREATE TABLE IF NOT EXISTS message_reactions (message_id TEXT NOT NULL, user_id TEXT NOT NULL, emoji TEXT NOT NULL, created_at TEXT NOT NULL, PRIMARY KEY(message_id, user_id, emoji));
    CREATE TABLE IF NOT EXISTS conversation_pins (id TEXT PRIMARY KEY, conversation_id TEXT NOT NULL, message_id TEXT NOT NULL, pinned_by TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(conversation_id, message_id));
    CREATE TABLE IF NOT EXISTS link_metadata_cache (normalized_url TEXT PRIMARY KEY, hostname TEXT NOT NULL, title TEXT, description TEXT, favicon_url TEXT, image_url TEXT, status TEXT NOT NULL DEFAULT 'pending', fetched_at TEXT, expires_at TEXT);
  `);
  try { db.exec('ALTER TABLE conversations ADD COLUMN archived_by TEXT'); } catch (e) {}
  const error = (code, msg) => { const e = new Error(msg); e.status = code; throw e; };
  const cap = (u, k) => u.role === 'admin' || !!(u.caps || {})[k];
  const canView = u => cap(u, 'view_messages') || cap(u, 'view_all');
  const canSend = u => cap(u, 'send_message') || cap(u, 'view_all');
  const MAX_BODY = 4000, MAX_REFS = 24, MAX_ATTACH = 5, PAGE = 40;
  /* v35: a message over the limit is refused with a reason instead of being cut silently
     (the composer also stops at 4,000). Sending is rate limited per person so one account
     cannot flood a channel and everyone's notifications (was: 60 messages in 0.3 s). */
  const checkBody = v => { const t = String(v || ''); if (t.length > MAX_BODY) error(413, 'Messages can be up to ' + MAX_BODY.toLocaleString('en-US') + ' characters.'); return t; };
  const sendRate = new Map();
  const rateCheck = u => { const now = Date.now(), w = 30000, max = Math.max(5, +(process.env.COS_MSG_RATE_MAX || 30)); let r = sendRate.get(u.id); if (!r || r.start + w < now) { r = { start: now, n: 0 }; sendRate.set(u.id, r); } if (++r.n > max) error(429, 'You are sending messages too fast. Wait a few seconds.'); if (sendRate.size > 5000) for (const [k, x] of sendRate) if (x.start + w < now) sendRate.delete(k); };
  const normalizeUrl = value => { let raw=String(value||'').trim(); if(/^www\./i.test(raw))raw='https://'+raw; if(!/^https?:\/\//i.test(raw))return ''; try{const u=new URL(raw);if(!['http:','https:'].includes(u.protocol)||u.username||u.password)return '';u.hostname=u.hostname.toLowerCase();return u.toString();}catch(e){return '';} };
  const bodyUrls = text => { const s=String(text||''), re=/(?:https?:\/\/|www\.)[^\s<>"']+/ig, out=[], seen=new Set(); let m; while((m=re.exec(s))){let raw=m[0];while(/[.,!?;:]$/.test(raw))raw=raw.slice(0,-1);while(/\)$/.test(raw)&&(raw.match(/\(/g)||[]).length<(raw.match(/\)/g)||[]).length)raw=raw.slice(0,-1);const url=normalizeUrl(raw);if(url&&!seen.has(url)){seen.add(url);out.push(url);}}return out; };
  const providerOf = url => { const u=new URL(url), h=u.hostname.toLowerCase(); let m; if((m=url.match(/drive\.google\.com\/drive\/(?:u\/\d+\/)?folders\/([-\w]+)/)))return ['GOOGLE_DRIVE','folder',m[1],'DRIVE_LINK']; if((m=url.match(/drive\.google\.com\/file\/d\/([-\w]+)/)))return ['GOOGLE_DRIVE','file',m[1],'DRIVE_LINK']; if((m=url.match(/docs\.google\.com\/document\/d\/([-\w]+)/)))return ['GOOGLE_DOCS','document',m[1],'DRIVE_LINK']; if((m=url.match(/docs\.google\.com\/spreadsheets\/d\/([-\w]+)/)))return ['GOOGLE_SHEETS','spreadsheet',m[1],'DRIVE_LINK']; if((m=url.match(/docs\.google\.com\/presentation\/d\/([-\w]+)/)))return ['GOOGLE_SLIDES','presentation',m[1],'DRIVE_LINK']; if(h==='figma.com'||h.endsWith('.figma.com'))return ['FIGMA','file',(url.match(/\/(?:file|design|board)\/([-\w]+)/)||[])[1]||'','URL']; if(h==='canva.com'||h.endsWith('.canva.com'))return ['CANVA','design','','URL']; if(/[?#].*(task|conv)=/.test(url))return ['ZENCREVIA','internal','','URL']; return ['GENERIC','website',h,'URL']; };
  const refsFromBody = body => bodyUrls(body).map(url => {const p=providerOf(url);return {type:p[3],url,normalizedUrl:url,provider:p[0],resourceType:p[1],resourceId:p[2],hostname:new URL(url).hostname,source:'BODY'};});
  const teamMemberIds = teamId => db.prepare('SELECT user_id FROM team_memberships WHERE team_id=?').all(teamId).map(r => r.user_id);
  const wsMember = id => !!db.prepare('SELECT 1 FROM workspace_members WHERE user_id=? AND workspace_id=?').get(id, ws);
  /* ---------- membership: team channels follow the team roster (§136.3) ---------- */
  const memberIds = c => (c.type === 'TEAM_DEFAULT' || c.type === 'TEAM_CHANNEL') ? teamMemberIds(c.team_id) : db.prepare('SELECT user_id FROM conversation_members WHERE conversation_id=?').all(c.id).map(r => r.user_id);
  const isMember = (c, userId) => memberIds(c).includes(userId);
  const memberState = (c, userId) => db.prepare('SELECT * FROM conversation_members WHERE conversation_id=? AND user_id=?').get(c.id, userId) || {};
  const ensureMemberRow = (c, userId) => db.prepare('INSERT OR IGNORE INTO conversation_members(conversation_id,user_id,joined_at) VALUES(?,?,?)').run(c.id, userId, now());
  const ensureTeamDefaults = () => { db.prepare("SELECT id, team_lead_id FROM teams WHERE workspace_id=? AND is_archived=0").all(ws).forEach(t => { if (!db.prepare("SELECT 1 FROM conversations WHERE workspace_id=? AND team_id=? AND type='TEAM_DEFAULT'").get(ws, t.id)) db.prepare('INSERT INTO conversations(id,workspace_id,team_id,type,name,description,created_by,created_at) VALUES(?,?,?,?,?,?,?,?)').run('cv_' + t.id + '_general', ws, t.id, 'TEAM_DEFAULT', 'general', 'Diskusi umum tim.', t.team_lead_id || 'system', now()); }); };
  try { ensureTeamDefaults(); } catch (e) { /* teams table may use a different archive column on very old DBs; handled lazily by sync-teams */ }
  /* ---------- serialisation ---------- */
  const J = (s, d) => { try { return JSON.parse(s); } catch (e) { return d; } };
  const reactionsOf = id => { const out = {}; db.prepare('SELECT user_id, emoji FROM message_reactions WHERE message_id=? ORDER BY created_at').all(id).forEach(r => { (out[r.emoji] = out[r.emoji] || []).push(r.user_id); }); return out; };
  const msgOut = m => ({ id: m.id, conversationId: m.conversation_id, senderId: m.sender_id, type: m.type, body: m.deleted_at ? '' : m.body, mentions: J(m.mentions, []), refs: m.deleted_at ? [] : J(m.refs, []), replyTo: m.reply_to_message_id, createdAt: m.created_at, editedAt: m.edited_at, deletedAt: m.deleted_at, reactions: reactionsOf(m.id) });
  const lastMessage = id => db.prepare('SELECT * FROM messages WHERE conversation_id=? AND deleted_at IS NULL ORDER BY created_at DESC, id DESC LIMIT 1').get(id);
  const unreadFor = (c, userId) => { const st = memberState(c, userId); return db.prepare('SELECT count(*) n FROM messages WHERE conversation_id=? AND sender_id<>? AND deleted_at IS NULL AND created_at>?').get(c.id, userId, st.last_read_at || '').n; };
  const convOut = (c, userId) => { const st = memberState(c, userId), last = lastMessage(c.id), members = memberIds(c); return { id: c.id, type: c.type, teamId: c.team_id, projectId: c.project_id, name: c.name, description: c.description || '', createdBy: c.created_by, createdAt: c.created_at, archivedAt: c.archived_at, archivedBy: c.archived_by || null, members, pins: db.prepare('SELECT message_id FROM conversation_pins WHERE conversation_id=? ORDER BY created_at').all(c.id).map(r => r.message_id), starredBy: db.prepare('SELECT user_id FROM conversation_members WHERE conversation_id=? AND starred=1').all(c.id).map(r => r.user_id), readState: { [userId]: { lastReadMessageId: st.last_read_message_id || null, lastReadAt: st.last_read_at || '' } }, notificationLevel: { [userId]: st.notification_level || 'ALL' }, unread: unreadFor(c, userId), lastMessage: last ? { id: last.id, senderId: last.sender_id, body: (last.body || '').slice(0, 120), createdAt: last.created_at } : null }; };
  const getConv = (u, id) => { const c = db.prepare('SELECT * FROM conversations WHERE workspace_id=? AND id=?').get(ws, id); if (!c || !isMember(c, u.id)) error(404, 'Conversation not found.'); return c; };
  /* ---------- realtime: one SSE connection per session, logical subscriptions (§58) ---------- */
  const clients = new Map(); /* sessionKey -> {res, userId, active} */
  const send = (client, ev) => { try { client.res.write('data: ' + JSON.stringify(ev) + '\n\n'); } catch (e) { clients.delete(client.key); } };
  const publishToUsers = (userIds, ev) => { for (const c of clients.values()) if (userIds.includes(c.userId)) send(c, ev); };
  const publishToConversation = (conv, ev, onlyActive) => { const ids = memberIds(conv); for (const c of clients.values()) if (ids.includes(c.userId) && (!onlyActive || c.active === conv.id)) send(c, ev); };
  /* Generic previews are optional and never sit on the message delivery path.
     DNS is checked before every request/redirect; no credentials or cookies are
     forwarded, HTML is capped, and the cache prevents render-time fetches. */
  const privateIp = ip => { let s=String(ip).toLowerCase(); const mapped=s.match(/^::ffff:(\d+\.\d+\.\d+\.\d+)$/); if(mapped) s=mapped[1]; if(net.isIP(s)===4){const p=s.split('.').map(Number);return p[0]===10||p[0]===127||p[0]===0||p[0]>=224||(p[0]===169&&p[1]===254)||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===168)||(p[0]===192&&p[1]===0&&p[2]===0)||(p[0]===198&&(p[1]===18||p[1]===19))||(p[0]===100&&p[1]>=64&&p[1]<=127);} if(net.isIP(s)!==6) return true; return s==='::1'||s==='::'||s.startsWith('::ffff:')||s.startsWith('64:ff9b:')||/^f[cd]/.test(s)||/^fe[89ab]/.test(s)||s.startsWith('ff'); };
  /* v29 DNS-rebinding guard: the address is re-validated at connect time inside the
     socket lookup, so a hostname that resolved to a public IP during safeTarget() cannot
     switch to an internal one before the request is made. */
  const guardedLookup = (host, opts, cb) => { if (typeof opts === 'function') { cb = opts; opts = {}; } dnsCb.lookup(host, { all: true, verbatim: true }, (err, addrs) => { if (err) return cb(err); if (!addrs.length || addrs.some(a => privateIp(a.address))) { const e = new Error('blocked address'); e.code = 'EBLOCKED'; return cb(e); } if (opts && opts.all) return cb(null, addrs); cb(null, addrs[0].address, addrs[0].family); }); };
  const pinnedFetch = (target, signal, headers) => new Promise((resolve, reject) => { const mod = target.protocol === 'https:' ? https : http; const req = mod.request(target, { method: 'GET', headers, lookup: guardedLookup, signal, agent: false }, inc => { const h = new Headers(); Object.entries(inc.headers).forEach(([k, v]) => { if (v != null) h.set(k, Array.isArray(v) ? v.join(', ') : String(v)); }); const noBody = [204, 205, 304].includes(inc.statusCode) || inc.statusCode < 200; if (noBody) inc.resume(); resolve(new Response(noBody ? null : Readable.toWeb(inc), { status: inc.statusCode < 200 ? 502 : inc.statusCode, headers: h })); }); req.on('error', reject); req.end(); });
  const safeTarget = async value => { const url=normalizeUrl(value);if(!url)return null;const u=new URL(url),host=u.hostname.toLowerCase();if(host==='localhost'||host.endsWith('.localhost')||host.endsWith('.local')||host.endsWith('.internal')||/\.example$/.test(host)||/^(example\.(com|org|net)|.+\.test)$/.test(host))return null;if(u.port&&!['80','443'].includes(u.port))return null;const rows=await dns.lookup(host,{all:true,verbatim:true});if(!rows.length||rows.some(r=>privateIp(r.address)))return null;return u; };
  const htmlText = s => String(s||'').replace(/<[^>]*>/g,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/\s+/g,' ').trim();
  const metaTag = (html,key) => { const tags=html.match(/<meta\b[^>]*>/ig)||[];for(const tag of tags){const name=(tag.match(/(?:property|name)\s*=\s*["']([^"']+)["']/i)||[])[1],content=(tag.match(/content\s*=\s*["']([^"']*)["']/i)||[])[1];if(name&&content&&name.toLowerCase()===key)return htmlText(content);}return ''; };
  const limitedText = async res => { const reader=res.body&&res.body.getReader?res.body.getReader():null;if(!reader){const b=await res.arrayBuffer();if(b.byteLength>262144)throw new Error('preview too large');return Buffer.from(b).toString('utf8');}let size=0,chunks=[];for(;;){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>262144){reader.cancel();throw new Error('preview too large');}chunks.push(Buffer.from(value));}return Buffer.concat(chunks).toString('utf8'); };
  const fetchPreview = async normalized => { let target=await safeTarget(normalized);if(!target)return null;let res;for(let redirects=0;redirects<=3;redirects++){const ac=new AbortController(),timer=setTimeout(()=>ac.abort(),3500);try{res=await pinnedFetch(target,ac.signal,{Accept:'text/html,application/xhtml+xml;q=0.9','User-Agent':'ZenCrevia-LinkPreview/1.0'});}finally{clearTimeout(timer);}if(res.status>=300&&res.status<400&&res.headers.get('location')){target=await safeTarget(new URL(res.headers.get('location'),target).toString());if(!target)return null;continue;}break;}if(!res||!res.ok||!/^text\/html\b/i.test(res.headers.get('content-type')||''))return null;const len=Number(res.headers.get('content-length')||0);if(len>262144)return null;const html=await limitedText(res),title=metaTag(html,'og:title')||htmlText((html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)||[])[1]).slice(0,200),description=(metaTag(html,'og:description')||metaTag(html,'description')).slice(0,500),iconRaw=(html.match(/<link\b[^>]*rel=["'][^"']*(?:icon)[^"']*["'][^>]*href=["']([^"']+)["']/i)||[])[1],imageRaw=metaTag(html,'og:image');const safeAsset=async raw=>{if(!raw)return '';try{const u=new URL(raw,target).toString();return await safeTarget(u)?u:'';}catch(e){return '';}};return {hostname:target.hostname,title,description,faviconUrl:await safeAsset(iconRaw),imageUrl:await safeAsset(imageRaw),status:'ok'}; };
  const previewQueue=[], previewRate={at:0,n:0}; let previewActive=0;
  const runPreviewQueue=()=>{while(previewActive<2&&previewQueue.length){const job=previewQueue.shift();previewActive++;job().catch(()=>{}).finally(()=>{previewActive--;runPreviewQueue();});}};
  const queueLinkMetadata=(c,messageId)=>{const minute=Math.floor(Date.now()/60000);if(previewRate.at!==minute){previewRate.at=minute;previewRate.n=0;}if(previewRate.n>=20)return;const row=db.prepare('SELECT * FROM messages WHERE id=? AND deleted_at IS NULL').get(messageId);if(!row)return;const refs=J(row.refs,[]), todo=refs.filter(r=>r.type==='URL'&&r.provider==='GENERIC'&&r.normalizedUrl&&!r.title).slice(0,2);todo.forEach(ref=>{previewRate.n++;previewQueue.push(async()=>{const cached=db.prepare('SELECT * FROM link_metadata_cache WHERE normalized_url=? AND expires_at>?').get(ref.normalizedUrl,now());let meta=cached&&cached.status==='ok'?{hostname:cached.hostname,title:cached.title||'',description:cached.description||'',faviconUrl:cached.favicon_url||'',imageUrl:cached.image_url||'',status:'ok'}:null;if(!cached){try{meta=await fetchPreview(ref.normalizedUrl);}catch(e){}const at=now(),exp=new Date(Date.now()+(meta?12:1)*3600e3).toISOString();db.prepare('INSERT INTO link_metadata_cache(normalized_url,hostname,title,description,favicon_url,image_url,status,fetched_at,expires_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(normalized_url) DO UPDATE SET hostname=excluded.hostname,title=excluded.title,description=excluded.description,favicon_url=excluded.favicon_url,image_url=excluded.image_url,status=excluded.status,fetched_at=excluded.fetched_at,expires_at=excluded.expires_at').run(ref.normalizedUrl,ref.hostname||new URL(ref.normalizedUrl).hostname,meta&&meta.title||'',meta&&meta.description||'',meta&&meta.faviconUrl||'',meta&&meta.imageUrl||'',meta?'ok':'blocked',at,exp);}if(!meta)return;const fresh=db.prepare('SELECT * FROM messages WHERE id=? AND deleted_at IS NULL').get(messageId);if(!fresh)return;const next=J(fresh.refs,[]).map(r=>(r.normalizedUrl===ref.normalizedUrl?Object.assign({},r,meta):r));db.prepare('UPDATE messages SET refs=? WHERE id=?').run(JSON.stringify(next),messageId);const out=msgOut(db.prepare('SELECT * FROM messages WHERE id=?').get(messageId));publishToConversation(c,{type:'message_updated',conversationId:c.id,messageId,message:out});});});runPreviewQueue(); };
  route('GET', '/api/messages/stream', (u, p, q, b, req, res) => {
    if (!canView(u)) error(403, 'Your role cannot view Messages.');
    if (!res || !res.writeHead) error(500, 'Stream needs the raw response.');
    res.writeHead(200, { 'Content-Type': 'text/event-stream', 'Cache-Control': 'no-cache', Connection: 'keep-alive', 'X-Accel-Buffering': 'no' });
    const key = uid('sse'); const client = { key, res, userId: u.id, active: null }; clients.set(key, client);
    res.write('data: ' + JSON.stringify({ type: 'connected' }) + '\n\n');
    const ping = setInterval(() => { try { res.write(': ping\n\n'); } catch (e) {} }, 25000);
    publishToUsers(Array.from(new Set(Array.from(clients.values()).map(c => c.userId))), { type: 'presence', userId: u.id, state: 'online' });
    req.on('close', () => { clearInterval(ping); clients.delete(key); const still = Array.from(clients.values()).some(c => c.userId === u.id); if (!still) publishToUsers(Array.from(new Set(Array.from(clients.values()).map(c => c.userId))), { type: 'presence', userId: u.id, state: 'offline' }); });
    return { __raw: true };
  });
  route('POST', '/api/messages/subscribe', (u, p, q, b) => { const c = getConv(u, String(b.conversationId || '')); for (const cl of clients.values()) if (cl.userId === u.id) cl.active = c.id; return { ok: true }; });
  route('POST', '/api/messages/conversations/:id/typing', (u, p) => { const c = getConv(u, p.id); publishToConversation(c, { type: 'typing', conversationId: c.id, userId: u.id }, true); return { ok: true }; });
  /* ---------- conversations ---------- */
  route('GET', '/api/messages/conversations', u => { if (!canView(u)) error(403, 'Your role cannot view Messages.'); ensureTeamDefaults(); return db.prepare('SELECT * FROM conversations WHERE workspace_id=? ORDER BY created_at').all(ws).filter(c => isMember(c, u.id)).map(c => convOut(c, u.id)); });
  route('POST', '/api/messages/conversations/sync-teams', u => { ensureTeamDefaults(); return { ok: true }; });
  route('POST', '/api/messages/conversations', (u, p, q, b) => {
    if (!canSend(u)) error(403, 'Your role cannot start conversations.');
    const type = String(b.type || ''); const id = /^[-\w]{1,40}$/.test(String(b.id || '')) ? String(b.id) : uid('cv'); const at = now();
    if (type === 'DM') { const other = String((b.members || []).find(m => m !== u.id) || ''); if (!other || !wsMember(other)) error(400, 'Choose a member to message.'); const key = [u.id, other].sort().join('|'); const ex = db.prepare('SELECT * FROM conversations WHERE workspace_id=? AND dm_key=?').get(ws, key); if (ex) return convOut(ex, u.id); tx(db, () => { db.prepare('INSERT INTO conversations(id,workspace_id,type,created_by,created_at,dm_key) VALUES(?,?,?,?,?,?)').run(id, ws, 'DM', u.id, at, key); [u.id, other].forEach(m => db.prepare('INSERT INTO conversation_members(conversation_id,user_id,joined_at) VALUES(?,?,?)').run(id, m, at)); }); }
    else if (type === 'GROUP') { if (!(cap(u, 'create_group_chat') || cap(u, 'view_all'))) error(403, 'Your role cannot create groups.'); const name = String(b.name || '').trim().slice(0, 60); if (!name) error(400, 'Give the group a name.'); const members = Array.from(new Set([u.id].concat((b.members || []).map(String)))).filter(wsMember); if (members.length < 2 || members.length > 20) error(400, 'A group needs 2–20 members.'); tx(db, () => { db.prepare('INSERT INTO conversations(id,workspace_id,type,name,created_by,created_at) VALUES(?,?,?,?,?,?)').run(id, ws, 'GROUP', name, u.id, at); members.forEach(m => db.prepare('INSERT INTO conversation_members(conversation_id,user_id,joined_at,role) VALUES(?,?,?,?)').run(id, m, at, m === u.id ? 'owner' : 'member')); }); }
    else if (type === 'TEAM_CHANNEL') { if (!(cap(u, 'create_team_channel') || cap(u, 'manage_teams'))) error(403, 'Your role cannot create team channels.'); const teamId = String(b.teamId || ''); if (!db.prepare('SELECT 1 FROM teams WHERE id=? AND workspace_id=?').get(teamId, ws)) error(400, 'Unknown team.'); const name = String(b.name || '').toLowerCase().replace(/[^a-z0-9-_]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 40); if (!name || name === 'general') error(400, 'Choose another channel name.'); db.prepare('INSERT INTO conversations(id,workspace_id,team_id,type,name,description,created_by,created_at) VALUES(?,?,?,?,?,?,?,?)').run(id, ws, teamId, 'TEAM_CHANNEL', name, String(b.description || '').slice(0, 160), u.id, at); }
    else error(400, 'Unsupported conversation type.');
    const c = db.prepare('SELECT * FROM conversations WHERE id=?').get(id); const out = convOut(c, u.id); publishToUsers(memberIds(c), { type: 'conversation_updated', conversation: out }); return out; });
  route('PATCH', '/api/messages/conversations/:id', (u, p, q, b) => { const c = getConv(u, p.id); const at = now();
    if (b.notificationLevel !== undefined) { if (!['ALL', 'MENTIONS', 'MUTED'].includes(b.notificationLevel)) error(400, 'Bad level.'); ensureMemberRow(c, u.id); db.prepare('UPDATE conversation_members SET notification_level=? WHERE conversation_id=? AND user_id=?').run(b.notificationLevel, c.id, u.id); }
    if (b.starred !== undefined) { ensureMemberRow(c, u.id); db.prepare('UPDATE conversation_members SET starred=? WHERE conversation_id=? AND user_id=?').run(b.starred ? 1 : 0, c.id, u.id); }
    if (b.archived !== undefined) { /* §141: DM/GROUP by any member, TEAM_CHANNEL by manage_team_channel/manage_teams, #general only with its team */ if (c.type === 'TEAM_DEFAULT') error(400, '#general is archived together with its team.'); if (c.type === 'TEAM_CHANNEL' && !(cap(u, 'manage_team_channel') || cap(u, 'manage_teams'))) error(403, 'Only a team lead or admin can archive a team channel.'); db.prepare('UPDATE conversations SET archived_at=?, archived_by=? WHERE id=?').run(b.archived ? at : null, b.archived ? u.id : null, c.id); }
    if (b.name !== undefined || b.members !== undefined || b.description !== undefined) { const owner = c.created_by === u.id || cap(u, c.type === 'GROUP' ? 'manage_group_chat' : 'manage_team_channel') || cap(u, 'manage_teams'); if (!owner) error(403, 'Only the group owner or an admin can edit it.'); if (c.type === 'TEAM_DEFAULT' && b.name !== undefined) error(400, '#general cannot be renamed.'); if (b.name !== undefined) db.prepare('UPDATE conversations SET name=? WHERE id=?').run(String(b.name).trim().slice(0, 60), c.id); if (b.description !== undefined) db.prepare('UPDATE conversations SET description=? WHERE id=?').run(String(b.description).slice(0, 160), c.id); if (b.members !== undefined && c.type === 'GROUP') { const members = Array.from(new Set(b.members.map(String))).filter(wsMember); if (members.length < 2 || members.length > 20) error(400, 'A group needs 2–20 members.'); tx(db, () => { db.prepare('DELETE FROM conversation_members WHERE conversation_id=? AND user_id NOT IN (' + members.map(() => '?').join(',') + ')').run(c.id, ...members); members.forEach(m => db.prepare('INSERT OR IGNORE INTO conversation_members(conversation_id,user_id,joined_at) VALUES(?,?,?)').run(c.id, m, at)); }); } }
    const fresh = db.prepare('SELECT * FROM conversations WHERE id=?').get(c.id); const out = convOut(fresh, u.id); publishToUsers(memberIds(fresh), { type: 'conversation_updated', conversation: out }); return out; });
  route('POST', '/api/messages/conversations/:id/leave', (u, p) => { const c = getConv(u, p.id); if (c.type === 'TEAM_DEFAULT') error(400, 'Membership of #general follows the team.'); if (c.type === 'TEAM_CHANNEL') error(400, 'Leave the team to leave its channels.'); db.prepare('DELETE FROM conversation_members WHERE conversation_id=? AND user_id=?').run(c.id, u.id); publishToUsers(memberIds(c), { type: 'membership_changed', conversation: convOut(c, u.id) }); return { ok: true }; });
  route('PATCH', '/api/messages/conversations/:id/read', (u, p, q, b) => { const c = getConv(u, p.id); ensureMemberRow(c, u.id); const m = b.lastReadMessageId ? db.prepare('SELECT id, created_at FROM messages WHERE id=? AND conversation_id=?').get(String(b.lastReadMessageId), c.id) : lastMessage(c.id); db.prepare('UPDATE conversation_members SET last_read_message_id=?, last_read_at=? WHERE conversation_id=? AND user_id=?').run(m ? m.id : null, m ? m.created_at : now(), c.id, u.id); db.prepare("UPDATE notifications SET read_at=? WHERE recipient_id=? AND entity_type='message' AND entity_id=? AND read_at IS NULL").run(now(), u.id, c.id); publishToUsers([u.id], { type: 'unread_count_changed', conversationId: c.id, unread: 0 }); return { ok: true }; });
  /* ---------- messages (§12 cursor pagination) ---------- */
  route('GET', '/api/messages/conversations/:id/messages', (u, p, q) => { const c = getConv(u, p.id); const limit = Math.max(1, Math.min(100, parseInt(q.limit) || PAGE)); /* §12 cursor = created_at|id so same-second messages never get skipped */ const cur = q.before ? String(q.before).split('|') : null; const rows = cur ? db.prepare('SELECT * FROM messages WHERE conversation_id=? AND (created_at<? OR (created_at=? AND id<?)) ORDER BY created_at DESC, id DESC LIMIT ?').all(c.id, cur[0], cur[0], cur[1] || '', limit + 1) : db.prepare('SELECT * FROM messages WHERE conversation_id=? ORDER BY created_at DESC, id DESC LIMIT ?').all(c.id, limit + 1); const more = rows.length > limit; const page = rows.slice(0, limit).reverse(); return { items: page.map(msgOut), nextCursor: more && page.length ? page[0].created_at + '|' + page[0].id : null }; });
  route('GET', '/api/messages/conversations/:id/search', (u, p, q) => { const c = getConv(u, p.id); const term = String(q.q || '').toLowerCase().slice(0, 120); if (!term) return { items: [] }; return { items: db.prepare('SELECT * FROM messages WHERE conversation_id=? AND deleted_at IS NULL AND instr(lower(body),?)>0 ORDER BY created_at DESC LIMIT 50').all(c.id, term).map(msgOut) }; });
  route('GET', '/api/messages/conversations/:id/refs', (u,p,q)=>{ const c=getConv(u,p.id), kind=['media','files','tasks','links'].includes(q.kind)?q.kind:'links', limit=Math.max(1,Math.min(50,parseInt(q.limit)||32)), newest=q.sort!=='oldest', args=[c.id], where=['m.conversation_id=?','m.deleted_at IS NULL']; if(kind==='media')where.push("json_extract(j.value,'$.mediaKind') IN ('IMAGE','VIDEO')"); else if(kind==='files')where.push("json_extract(j.value,'$.type') IN ('FILE','ASSET') AND coalesce(json_extract(j.value,'$.mediaKind'),'') NOT IN ('IMAGE','VIDEO')"); else if(kind==='tasks')where.push("json_extract(j.value,'$.type')='TASK'"); else where.push("json_extract(j.value,'$.type') IN ('URL','DRIVE_LINK')"); if(kind==='media'&&['image','video'].includes(q.media)){where.push("json_extract(j.value,'$.mediaKind')=?");args.push(q.media.toUpperCase());} if(kind==='links'&&q.provider&&q.provider!=='all'){if(q.provider==='web')where.push("coalesce(json_extract(j.value,'$.provider'),'GENERIC')='GENERIC'");else{where.push("lower(coalesce(json_extract(j.value,'$.provider'),'')) LIKE ?");args.push('%'+String(q.provider).toLowerCase()+'%');}} const term=String(q.q||'').toLowerCase().slice(0,120);if(term){where.push("(instr(lower(m.body),?)>0 OR instr(lower(j.value),?)>0 OR instr(lower(m.sender_id),?)>0)");args.push(term,term,term);} const cur=q.before?String(q.before).split('|'):null, dir=newest?'DESC':'ASC', cmp=newest?'<': '>'; if(cur&&cur.length>=3){where.push(`(m.created_at ${cmp}? OR (m.created_at=? AND m.id ${cmp}?) OR (m.created_at=? AND m.id=? AND CAST(j.key AS INTEGER)>?))`);args.push(cur[0],cur[0],cur[1],cur[0],cur[1],parseInt(cur[2])||0);} const sql=`SELECT m.id message_id,m.sender_id,m.created_at,m.body,j.key ref_index,j.value ref_json FROM messages m,json_each(m.refs) j WHERE ${where.join(' AND ')} ORDER BY m.created_at ${dir},m.id ${dir},CAST(j.key AS INTEGER) ASC LIMIT ?`;args.push(limit+1);const rows=db.prepare(sql).all(...args),more=rows.length>limit,page=rows.slice(0,limit),last=page[page.length-1];return {items:page.map(r=>({messageId:r.message_id,senderId:r.sender_id,createdAt:r.created_at,body:(r.body||'').slice(0,240),ref:J(r.ref_json,{})})),nextCursor:more&&last?last.created_at+'|'+last.message_id+'|'+last.ref_index:null}; });
  route('GET','/api/messages/:id/context',(u,p)=>{const target=db.prepare('SELECT * FROM messages WHERE id=? AND deleted_at IS NULL').get(p.id);if(!target)error(404,'Message not found.');getConv(u,target.conversation_id);const rows=db.prepare('SELECT * FROM messages WHERE conversation_id=? AND deleted_at IS NULL AND (created_at<? OR (created_at=? AND id<=?)) ORDER BY created_at DESC,id DESC LIMIT 30').all(target.conversation_id,target.created_at,target.created_at,target.id).reverse();return {items:rows.map(msgOut),targetId:target.id};});
  const cleanRefs = refs => { let attachments=0; return (Array.isArray(refs) ? refs : []).slice(0, MAX_REFS).map(r => { const t = String(r.type || ''); if (!['TASK', 'PROJECT', 'ASSET', 'FILE', 'DRIVE_LINK', 'URL'].includes(t)) return null; if(t!=='URL'&&t!=='DRIVE_LINK'&&++attachments>MAX_ATTACH)return null; const o = { type: t }; if (r.entityId) o.entityId = String(r.entityId).slice(0, 60); if (r.url) { const url = normalizeUrl(String(r.url).slice(0, 2000)); if (!url) return null; o.url = url; o.normalizedUrl=normalizeUrl(r.normalizedUrl||url)||url; } ['provider', 'resourceType', 'resourceId', 'title', 'subtitle', 'description', 'hostname', 'faviconUrl', 'imageUrl', 'fallbackTitle', 'name', 'size', 'fileType', 'mimeType', 'driveId', 'source', 'projectName'].forEach(k => { if (r[k] !== undefined && r[k] !== null) o[k] = String(r[k]).slice(0, k==='description'?500:200); }); if(t==='FILE'){const mime=String(o.mimeType||'').toLowerCase();o.mediaKind=mime.startsWith('image/')?'IMAGE':mime.startsWith('video/')?'VIDEO':null;} if (r.createdFromMessage) o.createdFromMessage = true; if (r.preview && /^data:image\/(png|jpeg|webp|gif);base64,[A-Za-z0-9+/=]+$/.test(String(r.preview)) && String(r.preview).length < 400000) o.preview = String(r.preview); if (t === 'TASK' && !db.prepare('SELECT 1 FROM tasks WHERE id=? AND workspace_id=?').get(o.entityId, ws)) return null; return o; }).filter(Boolean); };
  const syncBodyRefs = (body, refs) => { const explicit=cleanRefs(refs).filter(r=>r.source!=='BODY'), seen=new Set(explicit.filter(r=>r.normalizedUrl||r.url).map(r=>r.normalizedUrl||r.url)); for(const r of refsFromBody(body)){if(!seen.has(r.normalizedUrl)&&explicit.length<MAX_REFS){seen.add(r.normalizedUrl);explicit.push(r);}}return explicit.slice(0,MAX_REFS); };
  route('POST', '/api/messages/conversations/:id/messages', (u, p, q, b) => { rateCheck(u); const c = getConv(u, p.id); if (!canSend(u)) error(403, 'Your role cannot send messages.'); if (c.archived_at) error(400, 'This conversation is archived.'); const body = checkBody(b.body); const refs = syncBodyRefs(body,b.refs); if (!body.trim() && !refs.length) error(400, 'Empty message.'); const members = memberIds(c); const mentions = (Array.isArray(b.mentions) ? b.mentions : []).slice(0, 30).map(m => ({ userId: String(m.userId || '').slice(0, 60), display: String(m.display || '').slice(0, 80) })).filter(m => m.userId === '@everyone' ? (cap(u, 'mention_everyone') || cap(u, 'manage_teams') || c.type === 'GROUP' || c.type === 'DM') : members.includes(m.userId)); const id = /^[-\w]{1,40}$/.test(String(b.id || '')) ? String(b.id) : uid('m'); const at = now(); const replyTo = b.replyTo && db.prepare('SELECT id FROM messages WHERE id=? AND conversation_id=?').get(String(b.replyTo), c.id) ? String(b.replyTo) : null;
    /* §57.2 one durable write, commit, then publish; notification fan-out is async */
    tx(db, () => { db.prepare('INSERT INTO messages(id,conversation_id,sender_id,type,body,mentions,refs,reply_to_message_id,created_at) VALUES(?,?,?,?,?,?,?,?,?)').run(id, c.id, u.id, 'TEXT', body, JSON.stringify(mentions), JSON.stringify(refs), replyTo, at); ensureMemberRow(c, u.id); db.prepare('UPDATE conversation_members SET last_read_message_id=?, last_read_at=? WHERE conversation_id=? AND user_id=?').run(id, at, c.id, u.id); });
    const m = msgOut(db.prepare('SELECT * FROM messages WHERE id=?').get(id)); publishToConversation(c, { type: 'message_created', conversationId: c.id, messageId: id, message: m }); queueLinkMetadata(c,id);
    setImmediate(() => { try { const everyone = mentions.some(x => x.userId === '@everyone'); const replyTarget = replyTo ? (db.prepare('SELECT sender_id FROM messages WHERE id=?').get(replyTo) || {}).sender_id : null; const firstRef=refs[0], summary=body.trim().slice(0,160)||(firstRef&&firstRef.mediaKind==='IMAGE'?'Sent a photo':firstRef&&firstRef.mediaKind==='VIDEO'?'Sent a video':firstRef&&firstRef.type==='FILE'?'Sent a file':firstRef?'Shared a link':'Sent a message'); members.filter(r => r !== u.id).forEach(r => { const st = memberState(c, r); if (st.notification_level === 'MUTED') return; const mentioned = everyone || mentions.some(x => x.userId === r); const k = mentioned ? 'chat_mention' : c.type === 'DM' ? 'chat_dm' : replyTarget === r ? 'chat_reply' : c.type === 'TEAM_DEFAULT' ? 'chat_team_general' : 'chat_group'; if (st.notification_level === 'MENTIONS' && k !== 'chat_mention' && k !== 'chat_dm' && k !== 'chat_reply') return; const nid = uid('nt'); writeNotif(db, ws, { id: nid, recipient: r, who: u.id, k, t: c.id, entityType: 'message', message: JSON.stringify({ msg: id, text: summary }) }); const notif = readNotifs(db, ws, r).find(n => n.id === nid); if (notif) publishToUsers([r], { type: 'notification_created', notification: Object.assign({}, notif, { msg: id, text: summary }) }); publishToUsers([r], { type: 'unread_count_changed', conversationId: c.id, unread: unreadFor(c, r) }); if (onNotification && (k === 'chat_mention' || k === 'chat_dm')) onNotification(nid); }); } catch (e) { console.error('chat notification fan-out', e.message); } });
    return m; });
  const getMsg = (u, id) => { const m = db.prepare('SELECT * FROM messages WHERE id=?').get(id); if (!m) error(404, 'Message not found.'); const c = getConv(u, m.conversation_id); return { m, c }; };
  route('PATCH', '/api/messages/:id', (u, p, q, b) => { const { m, c } = getMsg(u, p.id); if (m.sender_id !== u.id && !cap(u, 'manage_any_message')) error(403, 'You can only edit your own messages.'); const curRefs = J(m.refs, []); const body = b.body === undefined ? m.body : checkBody(b.body); const refs = syncBodyRefs(body,b.refs === undefined ? curRefs : b.refs); if (!body.trim() && !refs.length) error(400, 'Empty message.'); db.prepare('UPDATE messages SET body=?, refs=?, edited_at=? WHERE id=?').run(body, JSON.stringify(refs), now(), m.id); const out = msgOut(db.prepare('SELECT * FROM messages WHERE id=?').get(m.id)); publishToConversation(c, { type: 'message_updated', conversationId: c.id, messageId: m.id, message: out }); queueLinkMetadata(c,m.id); return out; });
  route('DELETE', '/api/messages/:id', (u, p) => { const { m, c } = getMsg(u, p.id); if (m.sender_id !== u.id && !cap(u, 'manage_any_message')) error(403, 'You can only delete your own messages.'); tx(db, () => { db.prepare('UPDATE messages SET deleted_at=? WHERE id=?').run(now(), m.id); db.prepare('DELETE FROM conversation_pins WHERE message_id=?').run(m.id); }); const out = msgOut(db.prepare('SELECT * FROM messages WHERE id=?').get(m.id)); publishToConversation(c, { type: 'message_deleted', conversationId: c.id, messageId: m.id, message: out }); return { ok: true }; });
  route('POST', '/api/messages/:id/reactions', (u, p, q, b) => { const { m, c } = getMsg(u, p.id); const emoji = String(b.emoji || '').slice(0, 8); if (!emoji) error(400, 'Choose an emoji.'); const ex = db.prepare('SELECT 1 FROM message_reactions WHERE message_id=? AND user_id=? AND emoji=?').get(m.id, u.id, emoji); if (ex) db.prepare('DELETE FROM message_reactions WHERE message_id=? AND user_id=? AND emoji=?').run(m.id, u.id, emoji); else db.prepare('INSERT INTO message_reactions VALUES(?,?,?,?)').run(m.id, u.id, emoji, now()); const out = msgOut(db.prepare('SELECT * FROM messages WHERE id=?').get(m.id)); publishToConversation(c, { type: 'reaction_changed', conversationId: c.id, messageId: m.id, message: out }); return { reactions: out.reactions }; });
  const canPin = (u, c) => cap(u, 'pin_message') || cap(u, 'manage_teams') || c.type === 'DM' || c.type === 'GROUP';
  route('POST', '/api/messages/:id/pin', (u, p) => { const { m, c } = getMsg(u, p.id); if (!canPin(u, c)) error(403, 'Your role cannot pin messages here.'); db.prepare('INSERT OR IGNORE INTO conversation_pins(id,conversation_id,message_id,pinned_by,created_at) VALUES(?,?,?,?,?)').run(uid('pin'), c.id, m.id, u.id, now()); const out = convOut(c, u.id); publishToUsers(memberIds(c), { type: 'conversation_updated', conversation: out }); return { pins: out.pins }; });
  route('DELETE', '/api/messages/:id/pin', (u, p) => { const { m, c } = getMsg(u, p.id); if (!canPin(u, c)) error(403, 'Your role cannot pin messages here.'); db.prepare('DELETE FROM conversation_pins WHERE conversation_id=? AND message_id=?').run(c.id, m.id); const out = convOut(c, u.id); publishToUsers(memberIds(c), { type: 'conversation_updated', conversation: out }); return { pins: out.pins }; });
  return { ensureTeamDefaults, publishToUsers, memberIds, clientsCount: () => clients.size, isOnline: userId => Array.from(clients.values()).some(c => c.userId === userId) };
};
