<script>
/* ============================================================
   ANALYTICS — server-computed from the same tables (§65); demo fallback when offline. Feeds the exports.
   ============================================================ */
function demoAnalytics(){
  var n=Math.max(1,Math.min(52,(EXPORT&&EXPORT.weeks)||+S.range||8)),end=EXPORT?dateOf(EXPORT.to):new Date(TODAY),start=new Date(end);start.setDate(start.getDate()-((start.getDay()+6)%7)-7*(n-1));start.setHours(0,0,0,0);
  var rows=(EXPORT?exportTasks():TASKS).filter(function(t){return !t._draft&&!t.tutorial;}),a={weeks:[],created:[],completed:[],overdue:[],avgDays:[],revisionRate:[],approvalHrs:[],timeInStatus:[],byTeam:[],byProject:[],demo:!API.on};
  var when=function(o){return new Date(o.createdAt||isoAgo(o.ago||0)).getTime();},doneAt=function(t){if(!isClosed(t))return null;return t.completedAt?new Date(t.completedAt).getTime():closedAt(t);},avg=function(v){return v.length?v.reduce(function(x,y){return x+y;},0)/v.length:null;},round=function(v){return v==null?null:Math.round(v*10)/10;};
  for(var i=0;i<n;i++){var lo=new Date(start);lo.setDate(start.getDate()+7*i);var hi=new Date(lo);hi.setDate(lo.getDate()+7);var inWeek=function(v){return v!=null&&v>=lo.getTime()&&v<hi.getTime();};a.weeks.push(uiMo(lo.getMonth())+" "+lo.getDate());a.created.push(rows.filter(function(t){return inWeek(when(t));}).length);var completed=rows.filter(function(t){return inWeek(doneAt(t));});a.completed.push(completed.length);a.avgDays.push(round(avg(completed.map(function(t){return (doneAt(t)-when(t))/86400000;}).filter(function(d){return d>=0;}))));/* a task can't finish before it was created — such rows are bad data, not a negative duration */a.overdue.push(rows.filter(function(t){var d=dateOf(t.due),done=doneAt(t);return inWeek(+d)&&+d<+TODAY&&(done==null||done>=+d+86400000);}).length);var uploaded=0,revised=0,hours=[];rows.forEach(function(t){(t.versions||[]).forEach(function(v){if(inWeek(when(v)))uploaded++;var decided=v.decidedAt?+new Date(v.decidedAt):v.decidedAgo!=null?Date.now()-v.decidedAgo*60000:null;if(v.state==="revision"&&inWeek(decided))revised++;if(v.state==="approved"&&inWeek(decided))hours.push((decided-when(v))/3600000);});});a.revisionRate.push(uploaded?revised/uploaded:null);a.approvalHrs.push(round(avg(hours)));}
  var buckets={};WS.workflow.forEach(function(st){buckets[st.id]=[];});rows.forEach(function(t){var moves=(t.activity||[]).filter(function(x){return x.k==="moved";}).sort(function(x,y){return when(x)-when(y);});for(var j=1;j<moves.length;j++){var prev=moves[j-1];if(prev.a&&buckets[prev.a.to])buckets[prev.a.to].push((when(moves[j])-when(prev))/86400000);}});a.timeInStatus=WS.workflow.map(function(st){return {id:st.id,name:st.name,days:round(avg(buckets[st.id])),samples:buckets[st.id].length};});
  a.byTeam=activeTeams().map(function(t){var w=teamWorkload(t.id);if(EXPORT){var members=w.ids.filter(function(id){return rows.some(function(x){return isAssignee(x,id);});});w.cap=members.reduce(function(n,id){return n+(person(id).cap||0);},0);w.assigned=members.reduce(function(n,id){return n+Math.round(rows.filter(function(x){return !isClosed(x)&&isAssignee(x,id);}).reduce(function(h,x){return h+(+x.effort||0)/assigneesOf(x).length;},0));},0);w.pct=w.cap?Math.round(w.assigned/w.cap*100):0;}var open=rows.filter(function(x){return x.team===t.id&&!isClosed(x)&&!projArchived(x.proj);});return {id:t.id,name:t.name,color:t.color,open:open.length,workloadHours:open.reduce(function(x,t){return x+(+t.effort||0);},0),completed:rows.filter(function(x){return x.team===t.id&&isClosed(x);}).length,capacity:w.cap,assigned:w.assigned,utilization:w.pct};});
  a.byProject=liveProjects().filter(function(p){return p.status!=="done";}).map(function(p){var open=rows.filter(function(t){return t.proj===p.id&&!isClosed(t);}),over=open.filter(function(t){return t.due<0;}).length,progress=projectProgress(p,rows);return {id:p.id,name:p.name,progress:progress,remainingHours:open.reduce(function(n,t){return n+(+t.effort||0);},0),open:open.length,overdue:over,daysLeft:p.due,risk:over||p.due<0?"high":p.due<=7&&progress<70?"medium":"low"};});if(EXPORT){a.byTeam=a.byTeam.filter(function(t){return rows.some(function(x){return x.team===t.id;});});a.byProject=a.byProject.filter(function(p){return rows.some(function(t){return t.proj===p.id;});});}return a;
}
function loadAnalytics(cb){ if (!API.on){ AN=demoAnalytics(); return cb(); } apiFetch("GET","/api/analytics?weeks="+Math.max(1,Math.min(52,+S.range||8))).then(function(d){ d.byProject=(d.byProject||[]).map(function(row){ var p=project(row.id); if(p)row.progress=projectProgress(p); return row; }); AN=d; cb(); }).catch(function(e){ AN={error:e.message}; cb(); }); }
function metrics(){ var an=(EXPORT&&EXPORT.an)||AN||demoAnalytics(); var r=(EXPORT&&EXPORT.an)?EXPORT.weeks:S.range; var sl=function(a){ return (a||[]).slice(-r); }; var num=function(a){ return a.filter(function(v){ return v!=null; }); }; var sum=function(a){ return num(a).reduce(function(x,y){ return x+y; },0); }; var avg=function(a){ a=num(a); return a.length?sum(a)/a.length:0; };
  var all=EXPORT?exportTasks():TASKS, open=EXPORT?all.filter(function(t){return !isClosed(t);}):openTasks(); var ids=Object.keys(PEOPLE).filter(function(k){ return !PEOPLE[k].stakeholder&&(!EXPORT||all.some(function(t){return isAssignee(t,k);})); }); var cap=0, asg=0; ids.forEach(function(id){ cap+=person(id).cap; asg+=EXPORT?Math.round(open.filter(function(t){return isAssignee(t,id);}).reduce(function(n,t){return n+(+t.effort||0)/assigneesOf(t).length;},0)):assigned(id); });
  var withV=all.filter(function(t){ return t.versions.length; }); var revd=withV.filter(function(t){ return t.versions.some(function(v){ return v.state==="revision"; }); });
  return { weeks:sl(an.weeks), created:sl(an.created), completed:sl(an.completed), overdue:sl(an.overdue), avgDays:sl(an.avgDays).map(function(v){ return v==null?0:v; }), revisionRate:sl(an.revisionRate).map(function(v){ return v==null?0:v; }), approvalHrs:sl(an.approvalHrs).map(function(v){ return v==null?0:v; }), timeInStatus:an.timeInStatus||[], byTeam:an.byTeam||[], byProject:an.byProject||[],
    totalCreated:sum(sl(an.created)), totalCompleted:sum(sl(an.completed)), openNow:open.length, overdueNow:open.filter(function(t){ return t.due<0; }).length, inReview:open.filter(isReview).length,
    avgCompletion:avg(sl(an.avgDays)).toFixed(1), revRate:Math.round(avg(sl(an.revisionRate))*100), liveRevRate:withV.length?Math.round(revd.length/withV.length*100):0, approvalRate:withV.length?Math.round(withV.filter(function(t){ return t.versions[t.versions.length-1].state==="approved"; }).length/withV.length*100):0,
    avgApproval:Math.round(avg(sl(an.approvalHrs))), utilization:cap?Math.round(asg/cap*100):0, cap:cap, asg:asg, blocked:open.filter(isTaskBlocked), topBlockers:open.map(function(t){return {task:t,count:blockingTasksOf(t).filter(function(x){return !isClosed(x);}).length};}).filter(function(x){return x.count;}).sort(function(a,b){return b.count-a.count;}).slice(0,5), demo:!!an.demo }; }
function svgBars(labels,series,opts){ opts=opts||{}; var W=520,H=180,pl=30,pb=24,pt=10; var max=0; series.forEach(function(s){ s.v.forEach(function(v){ if (v>max) max=v; }); }); max=max||1; if (opts.max) max=opts.max; var n=labels.length; var gw=(W-pl-8)/n; var bw=Math.min(22,(gw-8)/series.length);
  var h='<svg class="chart" viewBox="0 0 '+W+' '+H+'"><g class="grid">'; for (var g=0;g<=4;g++){ var y=pt+(H-pt-pb)*(1-g/4); h+='<line x1="'+pl+'" x2="'+W+'" y1="'+y+'" y2="'+y+'"/><text x="'+(pl-6)+'" y="'+(y+3)+'" text-anchor="end">'+(opts.pct?Math.round(max*g/4*100)+"%":Math.round(max*g/4*10)/10)+'</text>'; } h+='</g>';
  labels.forEach(function(l,i){ var x0=pl+gw*i+(gw-bw*series.length)/2; series.forEach(function(s,j){ var v=s.v[i]||0; var bh=(H-pt-pb)*(v/max); h+='<rect class="'+s.c+'" x="'+(x0+j*bw)+'" y="'+(H-pb-bh)+'" width="'+(bw-2)+'" height="'+bh+'" rx="3"><title>'+esc(l)+' · '+esc(s.n)+': '+(opts.pct?Math.round(v*100)+"%":v)+'</title></rect>'; if (opts.values&&series.length===1) h+='<text class="val" x="'+(x0+bw/2-1)+'" y="'+(H-pb-bh-3)+'" text-anchor="middle">'+(opts.pct?Math.round(v*100)+"%":v)+'</text>'; }); h+='<text x="'+(pl+gw*i+gw/2)+'" y="'+(H-6)+'" text-anchor="middle">'+esc(l)+'</text>'; });
  return h+'</svg>'; }
function svgLine(labels,series,opts){ opts=opts||{}; var W=520,H=180,pl=30,pb=24,pt=12; var max=0; series.forEach(function(s){ s.v.forEach(function(v){ if (v>max) max=v; }); }); max=(max||1)*1.15; var n=labels.length; var xs=function(i){ return pl+(W-pl-30)*(n>1?i/(n-1):0.5); }; var ys=function(v){ return pt+(H-pt-pb)*(1-v/max); };
  var h='<svg class="chart" viewBox="0 0 '+W+' '+H+'"><g class="grid">'; for (var g=0;g<=4;g++){ var y=pt+(H-pt-pb)*(1-g/4); h+='<line x1="'+pl+'" x2="'+W+'" y1="'+y+'" y2="'+y+'"/><text x="'+(pl-6)+'" y="'+(y+3)+'" text-anchor="end">'+(opts.pct?Math.round(max*g/4*100)+"%":Math.round(max*g/4*10)/10)+'</text>'; } h+='</g>';
  series.forEach(function(s,j){ var pts=s.v.map(function(v,i){ return xs(i)+","+ys(v||0); }); if (j===0&&opts.area) h+='<path class="area" d="M'+xs(0)+','+ys(0)+' L'+pts.join(" L")+' L'+xs(n-1)+','+ys(0)+' Z"/>'; h+='<polyline class="'+s.c+'" points="'+pts.join(" ")+'"/>'; s.v.forEach(function(v,i){ h+='<circle class="dot" cx="'+xs(i)+'" cy="'+ys(v||0)+'" r="3"><title>'+esc(labels[i])+' · '+esc(s.n)+': '+(opts.pct?Math.round((v||0)*100)+"%":v)+'</title></circle>'; }); });
  labels.forEach(function(l,i){ h+='<text x="'+xs(i)+'" y="'+(H-6)+'" text-anchor="middle">'+esc(l)+'</text>'; }); return h+'</svg>'; }
function hbars(rows,fmtv){ var max=0; rows.forEach(function(r){ if (r.v>max) max=r.v; }); max=max||1; return rows.map(function(r){ return '<div class="hbar" '+(r.click?'style="cursor:pointer" onclick="'+r.click+'"':'')+'><span style="white-space:nowrap;overflow:hidden;text-overflow:ellipsis;display:flex;align-items:center;gap:6px">'+(r.color?'<span class="tdot" style="--tc:'+r.color+'"></span>':'')+esc(r.k)+'</span><div class="track" style="'+(r.color?'--tc:'+r.color:'')+'"><i style="width:'+Math.round(r.v/max*100)+'%'+(r.cls?';background:var(--color-'+r.cls+')':'')+'"></i></div><span class="v">'+fmtv(r.v)+(r.extra||"")+'</span></div>'; }).join(""); }
function legend(items){ return '<div class="legend">'+items.map(function(x){ return '<span><i style="background:var(--color-'+x[1]+')"></i>'+x[0]+'</span>'; }).join("")+'</div>'; }
function renderAnalytics(){ if (!canI.viewAnalytics()){ document.getElementById("content").innerHTML='<div class="pagehead"><div><h1>Analytics</h1></div></div><div class="panel">'+emptyBox("Analytics are for leads and admins","Ask a creative lead for the report — or switch user in the top-right menu to see it.",I.lock)+'</div>'; return; } if (!AN){ document.getElementById("content").innerHTML=skeleton(); return loadAnalytics(function(){ if (S.screen==="analytics") renderAnalytics(); }); }
  if(AN.error){document.getElementById("content").innerHTML='<div class="pagehead"><h1>'+tr("Analytics")+'</h1></div><div class="panel">'+emptyBox(tr("Could not load analytics"),esc(AN.error),I.analytics,'<button class="btn" onclick="AN=null;renderScreen(false)">'+tr("Retry")+'</button>')+'</div>';return;}
  var m=metrics(); var risk={high:"danger",medium:"warning",low:"success"};
  var h='<div class="pagehead m-head an-head"><div><h1>Analytics</h1><div class="muted" style="margin-top:4px">'+(m.demo?"Demo · ":"")+m.weeks[0]+' → '+m.weeks[m.weeks.length-1]+'</div></div><div class="actions">'+segHtml([["4","4 wks"],["8","8 wks"]],String(S.range),"setRange")+'<label class="pillsel desktop-only"><span>Timeline</span><input type="number" min="1" max="52" value="'+S.range+'" onchange="setRange(this.value)" style="width:48px;border:0;background:transparent;font-weight:700;outline:none"><span>wks</span></label><button class="btn desktop-only" onclick="AN=null;renderScreen(false)">'+I.sync+'Refresh</button><button class="btn an-export" onclick="exportModal(\'xlsx\')">'+I.download+'Excel</button><button class="btn primary an-export" onclick="exportModal(\'ppt\')">'+I.download+'<span class="desktop-only">PowerPoint report</span><span class="mobile-only">PPT</span></button></div></div>';
  h+='<div class="kpis kpis-4">'+kpi("good",m.totalCompleted,tr("Tasks completed"),tr("last")+" "+S.range+" "+tr("weeks"),"",I.check,"green")+kpi("",m.totalCreated,tr("Tasks created"),tr("last")+" "+S.range+" "+tr("weeks"),"",I.plus,"ink")+kpi(m.overdueNow?"danger":"good",m.overdueNow,tr("Overdue now"),tr("of")+" "+m.openNow+" "+tr("open"),"",I.bell,m.overdueNow?"red":"green")+kpi("",m.avgCompletion+"<small>d</small>",tr("Avg completion"),tr("brief → approved"),"",I.calendar,"")+kpi(m.liveRevRate>35?"warn":"",m.liveRevRate+"<small>%</small>",tr("Revision rate"),tr("tasks sent back"),"",I.edit,"")+kpi("accent",m.approvalRate+"<small>%</small>",tr("Approval rate"),tr("latest version approved"),"",I.eye,"blue")+kpi("",m.avgApproval+"<small>h</small>",tr("Approval time"),tr("review → decision"),"",I.sync,"")+kpi(m.utilization>100?"danger":"accent",m.utilization+"<small>%</small>",tr("Team utilization"),m.asg+"h / "+m.cap+"h","",I.team,"lime")+'</div>';
  h+='<div class="grid g-1-1">'+panel("Throughput — created vs completed",null,'<div class="panel-body pad">'+svgBars(m.weeks,[{n:"Created",v:m.created,c:"b2"},{n:"Completed",v:m.completed,c:"b1"}])+'</div>'+legend([["Created","secondary"],["Completed","primary"]]),null,null,I.analytics)+panel("Overdue tasks per week",null,'<div class="panel-body pad">'+svgBars(m.weeks,[{n:"Overdue",v:m.overdue,c:"b3"}],{values:true})+'</div>',null,null,I.bell)+'</div>';
  h+='<div class="grid g-1-1">'+panel("Average completion time (days)",null,'<div class="panel-body pad">'+svgLine(m.weeks,[{n:"Days",v:m.avgDays,c:"l1"}],{area:true})+'</div>',null,null,I.calendar)+panel("Revision rate",null,'<div class="panel-body pad">'+svgLine(m.weeks,[{n:"Revision rate",v:m.revisionRate,c:"l1"}],{pct:true,area:true})+'</div>'+legend([["Revision requests ÷ versions uploaded","primary"]]),null,null,I.edit)+'</div>';
  h+='<div class="grid g-1-1-1">'+panel("Time in status (days)",null,hbars(m.timeInStatus.filter(function(s){ return s.days!=null; }).map(function(s){ return {k:s.name,v:s.days,extra:'<span class="hint"> · n='+s.samples+'</span>'}; }),function(v){ return v.toFixed(1)+"d"; })||emptyBox("Not enough transitions yet",""),null,null,I.kanban)+panel("Teams — utilization",null,hbars(m.byTeam.map(function(t){ return {k:t.name,v:t.utilization,color:teamColorCss(t.color),click:"go('teams','"+t.id+"')",extra:'<span class="hint"> · '+t.open+' open</span>'}; }),function(v){ return v+"%"; }),null,null,I.team)+panel("Top blockers",m.blocked.length,m.topBlockers.length?hbars(m.topBlockers.map(function(x){return {k:x.task.title,v:x.count,click:"openTask('"+x.task.id+"')",extra:'<span class="hint"> · '+x.task.id+'</span>'};}),function(v){return v+" downstream";}):emptyBox("No current blockers","All active tasks are ready to move."),null,null,I.tasks)+'</div>';
  h+='<div class="grid g-1-1">'+panel("Project progress & remaining work",null,hbars(m.byProject.map(function(p){ return {k:p.name,v:p.progress,cls:"success",click:"go('projects','"+p.id+"')",extra:'<span class="hint"> · '+p.remainingHours+'h left</span>'}; }),function(v){ return v+"%"; }),null,null,I.projects)+panel("Deadline risk",null,m.byProject.map(function(p){ return '<div class="row" onclick="go(\'projects\',\''+p.id+'\')"><span class="badge" style="background:var(--color-'+risk[p.risk]+');color:#fff">'+p.risk+'</span><div style="min-width:0"><div class="t">'+esc(p.name)+'</div><div class="m">'+p.open+' open · '+p.overdue+' overdue · '+(p.daysLeft==null?"no deadline":p.daysLeft<0?(-p.daysLeft)+"d past deadline":p.daysLeft+"d left")+'</div></div><span class="pct">'+p.progress+'%</span></div>'; }).join("")||emptyBox("No active projects",""),null,null,I.bell)+'</div>';
  h+=panel("Pipeline snapshot",null,hbars(WS.workflow.map(function(s){ return {k:s.name,v:boardTasks().filter(function(t){ return t.status===s.id; }).length,click:"S.filters.status='"+s.id+"';S.taskScope='all';go('tasks','list')"}; }),function(v){ return String(v); }),null,null,I.kanban);
  document.getElementById("content").innerHTML=h; }
function setRange(v){ S.range=Math.max(1,Math.min(52,+v||8)); AN=null; renderScreen(false); }
</script>
