<script>
/* ============================================================
   ASSETS — library, folders, cloud storage links · BRAND LIBRARY (§60–61)
   ============================================================ */
function driveOnly(){ var g=byId(WS.cloud||[],"gdrive"); if (!g){ g={id:"gdrive",name:"Google Drive",connected:false,account:"",folder:"",lastSync:0,color:"#1FA463",config:{}}; } WS.cloud=[g]; return g; }
function cloudOf(){ return driveOnly(); }
/* v37: was also called detectProvider, and messages.js (loaded later) replaced it with a
   function returning an object — every "is this a Drive link?" check failed. */
function isDriveUrl(url){ return driveKind(url)==="gdrive"; }
function driveKind(url){ return /(^https:\/\/)?(drive\.google\.com|docs\.google\.com)\//.test(String(url||"")) ? "gdrive" : "local"; }
var ASSET_TYPES=["logo","color","font","icon","image","template","document","guideline","video","other"];
function assetsFiltered(){ var q=S.assetQuery.toLowerCase(); return ASSETS.filter(function(a){ if (S.assetFolder==="brand"&&!a.brand) return false; if (S.assetFolder!=="all"&&S.assetFolder!=="cloud"&&S.assetFolder!=="brand"&&a.folder!==S.assetFolder) return false; if (S.assetFolder==="cloud"&&a.source==="local") return false; if (q&&a.name.toLowerCase().indexOf(q)<0&&a.tags.join(" ").toLowerCase().indexOf(q)<0) return false; return true; }); }
function renderAssets(){ driveOnly(); var h='<div class="pagehead m-head"><div><h1>'+tr("Assets")+'</h1><div class="muted" style="margin-top:4px">'+ASSETS.length+' '+tr("assets")+' · '+ASSETS.filter(function(a){return a.brand;}).length+' '+tr("brand assets")+' · '+ASSETS.filter(function(a){return a.source!=="local";}).length+' '+tr("linked from Google Drive")+'</div></div><div class="actions"><div class="ptabs"><button class="tab'+(S.assetTab==="library"?" on":"")+'" onclick="S.assetTab=\'library\';renderScreen(false)">'+tr("Asset library")+'</button><button class="tab'+(S.assetTab==="brand"?" on":"")+'" onclick="S.assetTab=\'brand\';renderScreen(false)">'+tr("Brand library")+'</button></div>'+(canI.manageAssets()?'<button class="btn m-icon" aria-label="'+attr(tr("Link Google Drive"))+'" onclick="linkCloudModal(\'asset\')">'+driveIcon()+'<span class="m-label">'+tr("Link Google Drive")+'</span></button><button class="btn desktop-only" onclick="go(\'settings\',\'integrations\')">'+I.settings+tr("Google Drive settings")+'</button><button class="btn primary m-primary" aria-label="'+attr(tr("Upload asset"))+'" onclick="uploadAssetModal()">'+I.up+tr("Upload asset")+'</button>':'')+'</div></div>';
  h+=S.assetTab==="brand"?brandLibrary():assetLibrary(); document.getElementById("content").innerHTML=h; }
function assetLibrary(){ var list=assetsFiltered(); var cnt=function(f){ return ASSETS.filter(function(a){ return f==="all"?true:f==="cloud"?a.source!=="local":f==="brand"?a.brand:a.folder===f; }).length; };
  var h='<div class="assets"><div class="asset-side"><div class="folders"><button class="'+(S.assetFolder==="all"?"on":"")+'" onclick="S.assetFolder=\'all\';renderScreen(false)">'+I.assets+'All assets<span class="cnt">'+cnt("all")+'</span></button><button class="'+(S.assetFolder==="brand"?"on":"")+'" onclick="S.assetFolder=\'brand\';renderScreen(false)">'+I.star.replace("<svg",'<svg class="i"')+'Brand assets<span class="cnt">'+cnt("brand")+'</span></button><button class="'+(S.assetFolder==="cloud"?"on":"")+'" onclick="S.assetFolder=\'cloud\';renderScreen(false)">'+driveIcon()+'Cloud-linked<span class="cnt">'+cnt("cloud")+'</span></button><div class="fsep"></div>'+ASSET_FOLDERS.map(function(f){ return '<button class="'+(S.assetFolder===f.id?"on":"")+'" onclick="S.assetFolder=\''+f.id+'\';renderScreen(false)">'+I.projects+esc(f.name)+'<span class="cnt">'+cnt(f.id)+'</span></button>'; }).join("")+(canI.manageAssets()?'<button onclick="newFolderModal()" style="color:var(--color-primary)">'+I.plus.replace("<svg",'<svg class="i"')+'New folder</button>':'')+'</div>';
  h+='<div class="panel" style="margin-top:14px"><div class="panel-head"><span class="sq">'+I.cloud+'</span><h2>Storage</h2></div><div class="panel-body pad" style="display:flex;flex-direction:column;gap:8px">'+WS.cloud.map(function(c){ return '<button class="storage-account" onclick="go(\'settings\',\'integrations\')" title="Open Google Drive settings"><span class="drive-storage-logo">'+driveIcon()+'</span><span style="flex:1;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;text-align:left">'+esc(c.name)+'</span>'+(c.connected?'<span class="badge ok">on</span>':'<span class="badge">off</span>')+I.settings+'</button>'; }).join("")+'</div></div></div>';
  var fopts=[["all",tr("All assets")],["brand",tr("Brand assets")],["cloud",tr("Cloud-linked")]].concat(ASSET_FOLDERS.map(function(f){ return [f.id,f.name]; }));
  h+='<div><div class="toolbar asset-toolbar" style="margin-bottom:12px"><select class="asset-folder-select mobile-only" aria-label="'+attr(tr("Folder"))+'" onchange="S.assetFolder=this.value;renderScreen(false)">'+fopts.map(function(o){ return '<option value="'+attr(o[0])+'"'+(S.assetFolder===o[0]?" selected":"")+'>'+esc(o[1])+' ('+cnt(o[0])+')</option>'; }).join("")+'</select><input type="text" placeholder="'+tr("Filter by name or tag…")+'" value="'+attr(S.assetQuery)+'" oninput="S.assetQuery=this.value;renderAssetsBody()" style="flex:1;max-width:320px"><span class="hint" id="assetCount">'+list.length+' '+tr("shown")+'</span><span class="spacer"></span><div class="seg"><button class="'+(S.assetView==="grid"?"on":"")+'" onclick="S.assetView=\'grid\';renderScreen(false)">'+tr("Grid")+'</button><button class="'+(S.assetView==="list"?"on":"")+'" onclick="S.assetView=\'list\';renderScreen(false)">'+tr("List")+'</button></div></div><div id="assetsBody">'+assetsBody(list)+'</div></div></div>'; return h; }
function renderAssetsBody(){ var list=assetsFiltered(),el=document.getElementById("assetsBody"),count=document.getElementById("assetCount"); if(el)el.innerHTML=assetsBody(list); if(count)count.textContent=list.length+" "+tr("shown"); }
function assetsBody(list){ if (!list.length) return '<div class="panel">'+emptyBox("No assets here","Upload a file or link one from Google Drive.",driveIcon(),canI.manageAssets()?'<button class="btn primary sm" style="margin-top:6px" onclick="linkCloudModal(\'asset\')">'+driveIcon()+'Link Google Drive</button>':'')+'</div>';
  if (S.assetView==="list") return '<div class="panel"><div class="tbl-wrap"><table class="tbl"><thead><tr><th>Name</th><th>Type</th><th>Folder</th><th>Source</th><th>Size</th><th>Version</th><th>Updated</th></tr></thead><tbody>'+list.map(function(a){ return '<tr onclick="openAsset(\''+a.id+'\')"><td class="t"><span class="cell-flex"><span class="ficon" style="background:'+a.color+';width:26px;height:26px;font-size:8px">'+typeExt(a)+'</span>'+esc(a.name)+(a.brand?' <span class="badge">brand</span>':'')+'</span></td><td>'+esc(a.type)+'</td><td>'+esc((byId(ASSET_FOLDERS,a.folder)||{name:"—"}).name)+'</td><td>'+srcBadge(srcOf(a))+'</td><td class="mono">'+esc(a.size)+'</td><td class="mono">v'+a.ver+'</td><td class="mono">'+ago(a.ago)+'</td></tr>'; }).join("")+'</tbody></table></div></div>';
  return '<div class="agrid">'+list.map(function(a){ var s=SRC[srcOf(a)]; return '<div class="acard" onclick="openAsset(\''+a.id+'\')"><div class="apv" style="background:'+a.color+(a.img?';background-image:url('+a.img+')':'')+'">'+(a.source!=="local"?'<span class="src" style="color:'+s.c+'">'+driveIcon()+s.l+'</span>':'')+(a.brand?'<span class="star">'+I.star.replace("<svg",'<svg width="14" height="14" fill="currentColor" stroke="currentColor"')+'</span>':'')+(a.img?'':'<span class="ext">'+typeExt(a).toUpperCase()+'</span>')+'</div><div class="ab"><div class="at" title="'+attr(a.name)+'">'+esc(a.name)+'</div><div class="am"><span class="mono">v'+a.ver+'</span><span>·</span><span>'+esc(a.size)+'</span><span>·</span><span>'+ago(a.ago)+'</span></div><div class="chips" style="margin-top:2px">'+a.tags.slice(0,3).map(function(t){ return '<span class="badge">'+esc(t)+'</span>'; }).join("")+'</div></div></div>'; }).join("")+'</div>'; }
function openAsset(id){ var a=asset(id); var cl=cloudOf(a.source); var used=TASKS.filter(function(t){ return t.files.some(function(f){ return f.name===a.name; }); }); var ed=canI.manageAssets(); var ro=ed?"":" disabled";
  var body='<div style="height:180px;border-radius:var(--radius);background:'+a.color+(a.img?';background-image:url('+a.img+');background-size:cover;background-position:center':'')+';display:grid;place-items:center;color:#fff;font-family:var(--font-mono);font-weight:700">'+(a.img?'':typeExt(a).toUpperCase())+'</div>'+'<div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap">'+(a.img||/drive\.google/.test(a.url||"")?'<button class="btn sm ink" onclick="previewModal({title:\''+attr(a.name)+'\',img:asset(\''+id+'\').img,driveId:(asset(\''+id+'\').url.match(/\\/d\\/([^\\/]+)/)||[])[1],url:asset(\''+id+'\').url})">'+I.eye+'Preview</button>':'')+'</div>'+(ed?'<div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap"><button class="btn sm" onclick="pickThumb(\''+id+'\')">'+I.up+(a.img?"Change thumbnail":"Add thumbnail")+'</button>'+(a.img?'<button class="btn sm ghost" onclick="assetSet(\''+id+'\',\'img\',null);openAsset(\''+id+'\')">Remove</button>':'')+'<span class="hint">JPG, PNG, or WebP. Recommended ratio: 3:2.</span></div>':'')+
    '<div class="meta" style="margin:0"><div><div class="k">Type</div><div class="v"><select'+ro+' onchange="assetSet(\''+id+'\',\'type\',this.value)">'+ASSET_TYPES.map(function(t){ return '<option value="'+attr(t)+'"'+(a.type===t?" selected":"")+'>'+esc(t)+'</option>'; }).join("")+'</select></div></div><div><div class="k">Folder</div><div class="v"><select'+ro+' onchange="assetSet(\''+id+'\',\'folder\',this.value)">'+ASSET_FOLDERS.map(function(f){ return '<option value="'+f.id+'"'+(a.folder===f.id?" selected":"")+'>'+esc(f.name)+'</option>'; }).join("")+'</select></div></div><div><div class="k">Brand asset</div><div class="v"><input'+ro+' type="checkbox" style="width:16px;height:16px" '+(a.brand?"checked":"")+' onchange="assetSet(\''+id+'\',\'brand\',this.checked)"><span class="hint">show in Brand library</span></div></div><div><div class="k">Source</div><div class="v">'+srcBadge(srcOf(a))+'</div></div><div><div class="k">Version</div><div class="v mono">v'+a.ver+' · '+esc(a.size)+'</div></div><div><div class="k">Uploaded by</div><div class="v">'+av(a.by)+esc(first(a.by))+'</div></div><div><div class="k">Updated</div><div class="v mono">'+ago(a.ago)+'</div></div></div>'+
    (a.url?'<div class="field"><label>Cloud location</label><div style="display:flex;gap:8px"><input value="'+attr(a.url)+'" readonly style="font-family:var(--font-mono);font-size:12px"><button class="btn" onclick="openExternal(\''+attr(a.url)+'\')">'+I.ext+'Open</button></div>'+(cl&&cl.connected?'<div class="hint" style="margin-top:6px">Linked via '+esc(cl.name)+' · '+esc(cl.account)+'</div>':'')+'</div>':'')+
    fieldHtml("as_desc","Description",'<input'+ro+' id="as_desc" value="'+attr(a.description||"")+'" onchange="assetSet(\''+id+'\',\'description\',this.value)">')+fieldHtml("as_tags","Tags",tagPicker("as_tags_"+id,a.tags||[],function(value){ assetSet(id,"tags",value); },{readonly:!!ro}))+
    '<div><div class="eyebrow" style="margin-bottom:6px">Used in '+used.length+' task'+(used.length===1?"":"s")+'</div>'+(used.length?'<div class="agenda">'+used.map(function(t){ return taskRow(t); }).join("")+'</div>':'<div class="hint">Attach it from a task’s Files tab.</div>')+'</div>';
  openModal(esc(a.name),body,(ed?'<button class="btn danger-soft" onclick="deleteAsset(\''+id+'\')">'+I.trash+'Delete</button>':'')+'<span class="spacer"></span>'+(ed?'<button class="btn" onclick="newVersionAsset(\''+id+'\')">'+I.up+'New version</button>':'')+'<button class="btn primary" onclick="closeModal();renderScreen(false)">Done</button>',true); }
function pickThumb(id){ var inp=document.getElementById("fileInput"); inp.accept="image/*"; inp.onchange=function(){ var f=inp.files[0]; inp.value=""; if (!f) return; shrinkImage(f,1200,800,function(dataUrl){ assetSet(id,"img",dataUrl); toast("Thumbnail updated"); openAsset(id); }); }; inp.click(); }
function shrinkImage(file,maxW,maxH,cb,onError){ var fail=function(){var e=new Error("Could not read this image. Choose a PNG, JPG, or WebP file.");if(onError)onError(e);else toast(e.message,"bad");};var rd=new FileReader();rd.onerror=fail;rd.onload=function(){var img=new Image();img.onerror=fail;img.onload=function(){try{var r=Math.min(1,maxW/img.width,maxH/img.height),cv=document.createElement("canvas");cv.width=Math.max(1,Math.round(img.width*r));cv.height=Math.max(1,Math.round(img.height*r));cv.getContext("2d").drawImage(img,0,0,cv.width,cv.height);var out=cv.toDataURL("image/png");if(out.length>390000){out=cv.toDataURL("image/webp",0.8);while(out.length>390000&&cv.width>100){var next=document.createElement("canvas");next.width=Math.round(cv.width*0.8);next.height=Math.round(cv.height*0.8);next.getContext("2d").drawImage(cv,0,0,next.width,next.height);cv=next;out=cv.toDataURL("image/webp",0.75);}}if(out.length>390000)return fail();cb(out);}catch(e){fail();}};img.src=rd.result;};rd.readAsDataURL(file); }
function assetSet(id,k,v){ var a=asset(id); a[k]=v; persistAsset(a,false); }
function deleteAsset(id){ closeModal(); confirmModal("Delete asset?","Linked cloud files are unlinked, not deleted from the provider.",function(){ deleteAssetById(id); toast("Asset removed","bad"); },true); }
function newVersionAsset(id){ var inp=document.getElementById("fileInput"); inp.accept="*/*"; inp.onchange=function(){var f=inp.files[0];inp.value="";if(!f)return;uploadAny(f).then(function(u){var a=asset(id);if(!a)return; a.ver++;a.ago=0;a.source=u.source;a.url=u.url;a.img=u.preview||null;a.size=u.size;return persistAsset(a,false).then(function(saved){ if(saved===false)return false;toast("Version uploaded");openAsset(id);});}).catch(function(e){toast(e.message,"bad");});};inp.click(); }
function newFolderModal(){ openModal("New folder",fieldHtml("nf_name","Folder name",'<input id="nf_name" placeholder="e.g. Motion">')+fieldHtml("nf_type","Type",selectHtml("nf_type",ASSET_TYPES,"other")),'<button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="if(require([\'nf_name\'])){var f={id:uid(\'f\'),name:val(\'nf_name\'),type:val(\'nf_type\'),sort:ASSET_FOLDERS.length+1};ASSET_FOLDERS.push(f);closeModal();renderScreen(false);persistFolder(f)}">Create</button>'); }
function uploadAssetModal(){ window._assetImg=null; window._assetFile=null; window._assetUp=null; window._assetPending=false; window._assetSession=(window._assetSession||0)+1; openModal("Upload asset",'<div class="field"><label>File</label><div style="display:flex;gap:8px;align-items:center"><button class="btn" onclick="pickAssetFile()">'+I.up+'Choose file</button><span class="hint" id="ua_file">No file chosen</span></div></div><div id="ua_preview"></div><div class="hint">Images are saved as previews. Other files require Google Drive.</div>'+fieldHtml("ua_name","Name",'<input id="ua_name" placeholder="Display name">')+'<div class="field-row">'+fieldHtml("ua_type","Type",selectHtml("ua_type",ASSET_TYPES,"image"))+fieldHtml("ua_folder","Folder",selectHtml("ua_folder",ASSET_FOLDERS.map(function(f){ return [f.id,f.name]; }),S.assetFolder!=="all"&&S.assetFolder!=="cloud"&&S.assetFolder!=="brand"?S.assetFolder:"photo"))+'</div>'+fieldHtml("ua_tags","Tags",tagPicker("ua_tags",[],""))+'<label style="display:flex;gap:8px;align-items:center;font-size:var(--fs-sm)"><input type="checkbox" id="ua_brand"> Brand asset (show in Brand library)</label>','<button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveAsset()">Upload</button>'); }
function pickAssetFile(){ var inp=document.getElementById("fileInput"); inp.accept="*/*"; inp.onchange=function(){ var f=inp.files[0]; inp.value=""; if(!f)return; assetFileChosen(f); }; inp.click(); }
/* v19.9 shared by the file picker and clipboard paste */
function assetFileChosen(f){ if(!f||!document.getElementById("ua_file")||!document.getElementById("modalWrap").classList.contains("open")) return; var session=window._assetSession, token=window._assetPick=(window._assetPick||0)+1; window._assetFile=f; window._assetUp=null; window._assetImg=null; window._assetPending=true; document.getElementById("ua_preview").innerHTML=""; document.getElementById("ua_file").textContent=f.name+" · Uploading…"; var n=document.getElementById("ua_name"); if(!n.value)n.value=f.name;
  uploadAny(f).then(function(u){ if(session!==window._assetSession||token!==window._assetPick)return; window._assetUp=u; window._assetImg=u.preview||null; var pv=document.getElementById("ua_preview"); if(pv)pv.innerHTML=u.preview?'<img src="'+attr(u.preview)+'" style="max-width:100%;max-height:180px;border-radius:8px">':""; var el=document.getElementById("ua_file"); if(el)el.textContent=f.name+" · "+u.size+(u.driveId?" · Google Drive":""); }).catch(function(e){ if(session!==window._assetSession||token!==window._assetPick)return; window._assetUp=null; var el=document.getElementById("ua_file"); if(el)el.textContent="Upload failed"; toast(e.message,"bad"); }).finally(function(){if(session===window._assetSession&&token===window._assetPick)window._assetPending=false;}); }
function saveAsset(){ if (!require(["ua_name"])) return; if(window._assetPending) return toast("Wait for the upload to finish","bad"); if(!window._assetFile||!window._assetUp) return toast("Choose a file first","bad"); var f=window._assetFile; var cols=["#7C3AED","#0F766E","#B45309","#1D4ED8","#BE185D","#2D6A4F"]; var a={id:uid("as"),name:val("ua_name"),type:val("ua_type"),folder:val("ua_folder"),tags:tagPickerValues("ua_tags"),size:f?(f.size/1048576).toFixed(1)+" MB":"—",ver:1,source:window._assetUp&&window._assetUp.driveId?"gdrive":"local",url:window._assetUp?window._assetUp.url:"",ago:0,color:cols[ASSETS.length%cols.length],by:ME,brand:document.getElementById("ua_brand").checked,description:""}; if (window._assetImg) a.img=window._assetImg; ASSETS.unshift(a); closeModal(); renderScreen(false); persistAsset(a,true).then(function(saved){if(saved!==false)toast("Asset uploaded");}); }
function linkCloudModal(target){ var c=driveOnly(); openModal(driveIcon()+" Link from Google Drive",'<p class="hint">Paste a Google Drive, Docs, Sheets, or Slides share link. The file stays in Drive; ZenCrevia stores the link and shows a preview whenever Drive allows embedding.</p>'+fieldHtml("lc_url","Google Drive share link",'<input id="lc_url" placeholder="https://drive.google.com/file/d/…">')+fieldHtml("lc_name","Display name",'<input id="lc_name" placeholder="e.g. Campaign image selects">')+(target==="asset"?'<div class="field-row">'+fieldHtml("lc_type","Type",selectHtml("lc_type",ASSET_TYPES,"document"))+fieldHtml("lc_folder","Folder",selectHtml("lc_folder",ASSET_FOLDERS.map(function(f){ return [f.id,f.name]; }),"doc"))+'</div>'+fieldHtml("lc_tags","Tags",tagPicker("lc_tags",[],"")):'')+'<div class="hint">'+(c.connected?'Drive is connected as '+esc(c.account||"your Google account"):'Connect Drive once in Settings before uploading files automatically.')+' <a href="#" onclick="closeModal();go(\'settings\',\'integrations\');return false" style="color:var(--color-primary);font-weight:600">Open Google Drive settings</a></div>','<button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveCloudLink(\''+target+'\')">Link and preview</button>'); }
function saveCloudLink(target){ if (!require(["lc_url","lc_name"])) return; var url=val("lc_url"); if (!isDriveUrl(url)) return toast("Use a Google Drive, Docs, Sheets, or Slides share link","bad"); var c=driveOnly();
  if (target==="asset"){ var a={id:uid("as"),name:val("lc_name"),type:val("lc_type"),folder:val("lc_folder"),tags:tagPickerValues("lc_tags"),size:"—",ver:1,source:"gdrive",url:url,ago:0,color:SRC.gdrive.c,by:ME,brand:false,description:""}; ASSETS.unshift(a); closeModal(); toast("Linked from Google Drive"); renderScreen(false); persistAsset(a,true); }
  else { var tk=task(S.drawerTask); var name=val("lc_name"); closeModal(); editTaskWith(tk,function(t){ t.files.push(F(name,"document","gdrive","—",0,url)); log(t,"file",{name:name}); }).then(function(saved){ if(saved===false)return false; toast("Google Drive file linked"); }); } }
function saveGDrive(signIn){ var c=cloudOf("gdrive"), draft={clientId:val("gd_client"),folderId:val("gd_folder"),account:val("cc_acc"),autoUpload:document.getElementById("gd_auto").classList.contains("on"),publicLinks:document.getElementById("gd_public").classList.contains("on")}; if(draft.publicLinks&&!((c.config||{}).publicLinks===true)) return confirmModal("Make every new upload public?","Anyone who receives a file link could open it without signing in. Use this only for approved non-sensitive files.",function(){saveGDriveApply(signIn,draft);},true); saveGDriveApply(signIn,draft); }
function saveGDriveApply(signIn,draft){ var c=cloudOf("gdrive"); if((c.config||{}).clientId!==draft.clientId){GD.token=null;GD.exp=0;c.connected=false;} c.config={clientId:draft.clientId,folderId:draft.folderId,autoUpload:draft.autoUpload,publicLinks:draft.publicLinks===true}; c.account=draft.account||c.account; c.folder=c.config.folderId?"Drive folder "+c.config.folderId:"My Drive"; if (!c.config.clientId) c.connected=false; persistWS(); closeModal(); if (S.screen==="assets"||S.screen==="settings") renderScreen(false); if (signIn&&c.config.clientId){ GD.token=null; gdToken().then(function(saved){ if(saved===false)return false; toast("Google Drive connected"); renderScreen(false); }).catch(function(e){ toast("Google sign-in failed: "+e.message,"bad"); }); } else toast("Google Drive settings saved"); }
function editCloud(id){ if (id==="gdrive") return editGDrive(); var c=cloudOf(id); openModal((c.connected?"Edit ":"Connect ")+esc(c.name),fieldHtml("cc_acc","Account / bucket",'<input id="cc_acc" value="'+attr(c.account)+'" placeholder="'+(id==="s3"?"bucket-name (region)":"name@company.com")+'">')+fieldHtml("cc_folder","Root folder / prefix",'<input id="cc_folder" value="'+attr(c.folder)+'" placeholder="'+(id==="s3"?"s3://bucket/path":"/ZenCrevia")+'">')+(id==="s3"?fieldHtml("cc_key","Access key",'<input id="cc_key" type="password" placeholder="Stored server-side, never in the browser">'):'<div class="hint">In production this opens the provider OAuth consent screen; the token is stored server-side.</div>'),'<button class="btn" onclick="cloudSettingsModal()">Back</button><button class="btn primary" onclick="if(require([\'cc_acc\'])){var c=cloudOf(\''+id+'\');c.connected=true;c.account=val(\'cc_acc\');c.folder=val(\'cc_folder\');c.lastSync=0;persistWS();toast(c.name+\' connected\');cloudSettingsModal();if(S.screen===\'assets\'||S.screen===\'settings\')renderScreen(false)}">'+(c.connected?"Save":"Connect")+'</button>'); }
function syncCloud(){ editGDrive(); }
function disconnectCloud(id){ GD.token=null; GD.exp=0; var c=cloudOf(id); c.connected=false; persistWS(); toast(c.name+" disconnected","bad"); cloudSettingsModal(); if (S.screen==="assets"||S.screen==="settings") renderScreen(false); }

/* Google Drive is the single storage integration in this workspace. */
var DRIVE_LOGO_DATA="__GOOGLE_DRIVE_LOGO_DATA__";
function driveIcon(){ return '<img class="drive-logo" src="'+DRIVE_LOGO_DATA+'" alt="Google Drive">'; }
function editGDrive(){ var c=driveOnly(), cfg=c.config||{}; openModal("Connect Google Drive",'<div class="drive-modal-intro">'+driveIcon()+'<div><b>One connection for all workspace uploads</b><span>Use the Client ID from your Google Cloud web application. Your account grants access through Google’s own sign-in screen.</span></div></div><div class="drive-permission"><b>Who can see private uploads?</b><span>Share the selected Drive folder with each teammate or a Google Group. Signed-in people with folder access can open previews; ZenCrevia membership alone does not grant Drive access.</span></div>'+fieldHtml("gd_client","OAuth Client ID",'<input id="gd_client" value="'+attr(cfg.clientId||"")+'" placeholder="1234567890-abc.apps.googleusercontent.com" style="font-family:var(--font-mono);font-size:12px">')+'<div class="field-row">'+fieldHtml("gd_folder","Drive folder ID (recommended)",'<input id="gd_folder" value="'+attr(cfg.folderId||"")+'" placeholder="The ID after /folders/ in the Drive URL" style="font-family:var(--font-mono);font-size:12px">')+fieldHtml("cc_acc","Account label",'<input id="cc_acc" value="'+attr(c.account||"")+'" placeholder="team@company.com">')+'</div><div class="pref"><div class="pl"><b>Upload new files to Drive</b><span>New assets and task uploads are sent to the selected Drive folder.</span></div><button class="switch'+(cfg.autoUpload!==false?" on":"")+'" id="gd_auto" onclick="this.classList.toggle(\'on\')"></button></div><div class="pref"><div class="pl"><b>Anyone with the link</b><span>Off by default. Turn this on only for files approved to open without a Google sign-in.</span></div><button class="switch'+(cfg.publicLinks===true?" on":"")+'" id="gd_public" onclick="this.classList.toggle(\'on\')"></button></div>','<button class="btn" onclick="cloudSettingsModal()">Back</button><button class="btn" onclick="saveGDrive(true)">'+I.cloud+'Save &amp; sign in</button><button class="btn primary" onclick="saveGDrive(false)">Save</button>'); }

function cloudSettingsModal(){
  var c=driveOnly(), ed=canI.manageWorkspace();
  var step=function(n,title,text){ return '<div class="drive-step"><b>'+n+'</b><div><strong>'+esc(tr(title))+'</strong><span>'+esc(tr(text))+'</span></div></div>'; };
  var body='<div class="drive-modal-intro">'+driveIcon()+'<div><b>Google Drive setup for beginners</b><span>Follow each step in order. Original files stay in Drive; ZenCrevia keeps the link and preview reference.</span></div></div>'
    +'<div class="drive-before"><b>Prepare first</b><span>You need a Google account with access to the team folder, the exact dashboard URL, and permission to create a project in Google Cloud Console.</span><span class="mono">Local test: http://localhost:3000</span></div>'
    +'<div class="drive-steps">'
    +step(1,'Create a Google Cloud project','Open Google Cloud Console. Create a project owned by the organization, name it for this workspace, and select it.')
    +step(2,'Enable Google Drive API','Open APIs & Services, then Library. Find Google Drive API and enable it. The connection cannot upload or read Drive files without this API.')
    +step(3,'Set up the consent screen','Open OAuth consent screen. Choose the correct audience and enter the app name, support email, and developer email. While testing, add every account that will connect as a test user.')
    +step(4,'Create the Web OAuth Client ID','Open Credentials, create an OAuth client ID, and choose Web application. Add the exact dashboard origin under Authorized JavaScript origins, including the protocol and port but no page path.')
    +step(5,'Choose and share the Drive folder','Create a dedicated team folder and copy the Folder ID from its URL. Share the folder with each teammate or a managed Google Group. Give uploaders Editor access and viewers Viewer access.')
    +step(6,'Connect from ZenCrevia','Open Configure Google Drive. Paste the Client ID and Folder ID, enter an account label, then choose Save & sign in. Use a Google account that can access the team folder.')
    +step(7,'Upload a test file','Upload a harmless file from a task. Confirm that it appears in the selected Drive folder and that its preview opens from ZenCrevia.')
    +step(8,'Verify another person can open it','Ask one teammate to open the same task and file. If the task opens but the file does not, add their Google account or group to the Drive folder.')
    +step(9,'Keep public access exceptional','Leave Anyone with the link off for normal work. Add external reviewers explicitly in Drive. Only publish an approved, non-sensitive file that must open without Google sign-in.')
    +'</div>'
    +'<div class="drive-preview-note"><b>What happens after connection?</b><span>Assets, task Files, and Versions can upload to the selected Drive folder. A ZenCrevia member without Google Drive permission can still see task details, but the file preview or Drive link will not open for them.</span></div>'
    +'<div class="drive-troubleshoot"><b>Quick troubleshooting</b><span><strong>Login fails:</strong> Client ID or authorized origin is not exact. <strong>Upload does not enter the folder:</strong> enable Drive API, check the Folder ID, and make sure the account is an Editor. <strong>Preview is blank:</strong> share the file with the signed-in account or change the file’s Drive sharing setting.</span></div>'
    +'<div class="approval '+(c.connected?"ok":"")+'"><div class="h">'+driveIcon()+' Connection status</div><p>'+(c.connected?'Connected as <b>'+esc(c.account||"Google account")+'</b>.':'Not connected yet. Complete the steps above, then choose Configure Google Drive.')+'</p></div>';
  openModal('Google Drive setup',body,ed?'<button class="btn" onclick="editGDrive()">'+I.settings+'Configure Google Drive</button><span class="spacer"></span><button class="btn primary" onclick="closeModal()">Done</button>':'<button class="btn primary" onclick="closeModal()">Close</button>',true);
}

/* ---------- BRAND LIBRARY (§61) — logo, colors, typography, photography, icons, voice & tone, guidelines, templates ---------- */
function brandLibrary(){ var b=WS.brand||{}; var ed=canI.manageWorkspace(); var byType=function(t){ return ASSETS.filter(function(a){ return a.brand&&a.type===t; }); };
  var cards=function(list){ return list.length?'<div class="agrid" style="padding:0 var(--sp-4) var(--sp-4)">'+list.map(function(a){ return '<div class="acard" onclick="openAsset(\''+a.id+'\')"><div class="apv" style="background:'+a.color+(a.img?';background-image:url('+a.img+')':'')+'">'+(a.img?'':'<span class="ext">'+typeExt(a).toUpperCase()+'</span>')+'</div><div class="ab"><div class="at">'+esc(a.name)+'</div><div class="am"><span class="mono">v'+a.ver+'</span><span>·</span>'+srcBadge(srcOf(a))+'</div></div></div>'; }).join("")+'</div>':'<div class="hint" style="padding:0 var(--sp-4) var(--sp-3)">Mark assets as “brand asset” to show them here.</div>'; };
  var h='<div class="grid g-1-1">';
  h+='<section class="panel"><div class="panel-head"><span class="sq ink">'+I.assets+'</span><h2>Logo</h2><span class="spacer"></span>'+(ed?'<span class="link" onclick="brandEdit(\'logoNotes\',\'Logo usage notes\')">Edit notes</span>':'')+'</div><div class="panel-body pad"><div style="display:flex;gap:16px;align-items:center;margin-bottom:12px"><div class="ws-logo" style="width:72px;height:72px;font-size:24px;border-radius:20px">'+(WS.logoImg?'<img src="'+WS.logoImg+'">':esc(WS.logo))+'</div><div style="flex:1"><div style="font-weight:700;font-size:16px">'+esc(WS.name)+'</div><div class="muted" style="margin-top:4px;white-space:pre-line">'+esc(b.logoNotes||"Add usage notes: clear space, minimum size, backgrounds.")+'</div></div></div></div>'+cards(byType("logo"))+'</section>';
  h+='<section class="panel"><div class="panel-head"><span class="sq lime">'+I.edit+'</span><h2>Colors</h2><span class="spacer"></span>'+(ed?'<span class="link" onclick="brandColorModal()">+ Color</span>':'')+'</div><div class="panel-body pad"><div class="bcolors">'+(b.palette||[]).map(function(c,i){ return '<div class="bcolor" onclick="'+(ed?'brandColorModal('+i+')':'copyText(\''+c.hex+'\')')+'"><div class="sw2" style="background:'+c.hex+'"></div><div class="bn">'+esc(c.name)+'</div><div class="bh">'+esc(c.hex)+'</div></div>'; }).join("")+'</div></div>'+cards(byType("color"))+'</section>';
  h+='<section class="panel"><div class="panel-head"><span class="sq">'+TICONS.type+'</span><h2>Typography</h2><span class="spacer"></span>'+(ed?'<span class="link" onclick="brandTypeModal()">Edit names</span>':'')+'</div><div class="panel-body pad" style="display:flex;flex-direction:column;gap:8px"><div class="pref" style="padding:6px 0"><div class="pl"><b>Headlines</b><span>'+esc(b.headlineFont||"—")+'</span></div></div><div class="pref" style="padding:6px 0"><div class="pl"><b>Body</b><span>'+esc(b.bodyFont||"—")+'</span></div></div>'+(b.cjkFont?'<div class="pref" style="padding:6px 0"><div class="pl"><b>CJK</b><span>'+esc(b.cjkFont)+'</span></div></div>':'')+(canI.manageAssets()?'<div><button class="btn sm" onclick="uploadFontAsset()">'+I.up+'Upload font (.zip / .ttf / .otf / .woff)</button></div>':'')+'</div>'+cards(byType("font"))+'</section>';
  h+='<section class="panel"><div class="panel-head"><span class="sq">'+TICONS.camera+'</span><h2>Photography</h2><span class="spacer"></span>'+(ed?'<span class="link" onclick="brandEdit(\'photography\',\'Photography direction\')">Edit</span>':'')+'</div><div class="panel-body pad"><p style="white-space:pre-line">'+esc(b.photography||"Describe the photographic style.")+'</p></div>'+cards(byType("image"))+'</section>';
  h+='<section class="panel"><div class="panel-head"><span class="sq">'+TICONS.megaphone+'</span><h2>Voice &amp; tone</h2><span class="spacer"></span>'+(ed?'<span class="link" onclick="brandEdit(\'voice\',\'Voice & tone\')">Edit</span>':'')+'</div><div class="panel-body pad"><p style="white-space:pre-line">'+esc(b.voice||"Describe how the brand speaks.")+'</p></div></section>';
  h+='<section class="panel"><div class="panel-head"><span class="sq">'+I.knowledge+'</span><h2>Guidelines &amp; icons</h2></div>'+cards(byType("guideline").concat(byType("icon")))+'</section>';
  h+='<section class="panel" style="grid-column:1/-1"><div class="panel-head"><span class="sq">'+I.projects+'</span><h2>Templates</h2><span class="hint">Available while writing briefs and tasks</span></div>'+cards(byType("template"))+'</section>';
  return h+'</div>'; }
function copyText(t){ if(!navigator.clipboard)return toast("Copy this value: "+t); return navigator.clipboard.writeText(t).then(function(saved){ if(saved===false)return false;toast("Copied");}).catch(function(){toast("Copy this value: "+t,"bad");}); }
function brandEdit(k,label){ openModal(label,fieldHtml("be_v",label,'<textarea id="be_v" style="min-height:120px">'+esc(WS.brand[k]||"")+'</textarea>'),'<button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="WS.brand[\''+k+'\']=val(\'be_v\');closeModal();renderScreen(false);persistWS();toast(\'Brand library updated\')">Save</button>'); }
function brandColorModal(i){ var c=i!=null?WS.brand.palette[i]:{name:"",hex:"#B45309"}; openModal(i!=null?"Edit color":"Add color",'<div class="field-row">'+fieldHtml("bc_name","Name",'<input id="bc_name" value="'+attr(c.name)+'">')+fieldHtml("bc_hex","Hex",'<div style="display:flex;gap:8px"><input type="color" id="bc_pick" value="'+c.hex+'" oninput="document.getElementById(\'bc_hex\').value=this.value"><input id="bc_hex" value="'+attr(c.hex)+'" style="font-family:var(--font-mono)"></div>')+'</div>',(i!=null?'<button class="btn danger-soft" onclick="WS.brand.palette.splice('+i+',1);closeModal();renderScreen(false);persistWS()">Remove</button>':'')+'<span class="spacer"></span><button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="if(require([\'bc_name\',\'bc_hex\'])){var p=WS.brand.palette=WS.brand.palette||[];var o={name:val(\'bc_name\'),hex:val(\'bc_hex\')};'+(i!=null?'p['+i+']=o;':'p.push(o);')+'closeModal();renderScreen(false);persistWS()}">Save</button>'); }
function uploadFontAsset(){uploadAssetModal();document.getElementById("ua_type").value="font";document.getElementById("ua_folder").value=byId(ASSET_FOLDERS,"font")?"font":(ASSET_FOLDERS[0]||{}).id;document.getElementById("ua_brand").checked=true;}
function brandTypeModal(){ var b=WS.brand; openModal("Typography",fieldHtml("bt_h","Headline font",'<input id="bt_h" value="'+attr(b.headlineFont||"")+'">')+fieldHtml("bt_b","Body font",'<input id="bt_b" value="'+attr(b.bodyFont||"")+'">')+fieldHtml("bt_c","CJK font (optional)",'<input id="bt_c" value="'+attr(b.cjkFont||"")+'">'),'<button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="WS.brand.headlineFont=val(\'bt_h\');WS.brand.bodyFont=val(\'bt_b\');WS.brand.cjkFont=val(\'bt_c\');closeModal();renderScreen(false);persistWS()">Save</button>'); }
</script>
