<script>
/* ============================================================
   AUTH SCREEN — sign in / register (server mode) · demo user picker (offline mode)
   ============================================================ */
var AUTH={tab:"login"};
function showLogin(msg){ document.body.classList.add("auth"); closeDrawer(); closePops(); closeModal(); if(API.on&&!SESSION.canRegister&&AUTH.tab==="register")AUTH.tab="login"; var ws=SESSION.ws||{name:WS.name,logo:WS.logo,logoImg:WS.logoImg}, lang=languagePicker();
  var demoUsers=Object.keys(PEOPLE).map(function(id){ var p=PEOPLE[id]; var r=byId(ROLES,p.perm); return '<button class="demo-user-card" onclick="demoLogin(\''+id+'\')">'+av(id,"lg")+'<span class="demo-user-info"><span class="demo-user-name">'+esc(p.name)+'</span><span class="demo-user-meta">'+esc(p.role)+' · '+esc(r?r.name:p.perm)+'</span></span><span class="btn xs demo-user-continue">Continue</span></button>'; }).join("");
  var form=AUTH.tab==="login"?'<div class="field"><label>Email</label><input id="au_email" type="email" placeholder="you@company.com" autocomplete="username" onkeydown="if(event.key===\'Enter\')doLogin()"></div><div class="field"><label>Password</label><input id="au_pw" type="password" placeholder="••••••••••••" autocomplete="current-password" onkeydown="if(event.key===\'Enter\')doLogin()"></div><div class="err" id="au_err"></div><button class="btn primary" style="width:100%;justify-content:center;padding:11px" onclick="doLogin()">Sign in</button><p class="hint" style="margin-top:12px;text-align:center"><button type="button" class="linkbtn auth-forgot" onclick="AUTH.tab=\'forgot\';showLogin()">Forgot password?</button></p><p class="hint" style="margin-top:6px;text-align:center">Contact your workspace administrator if you do not have an account.</p>':
    AUTH.tab==="forgot"?authForgotForm():AUTH.tab==="reset"?authResetForm():
    '<div class="field-row"><div class="field"><label>Full name</label><input id="au_name" placeholder="Dian Sastro" autocomplete="name"></div><div class="field"><label>Job title</label><input id="au_title" placeholder="Designer"></div></div><div class="field"><label>Email</label><input id="au_email" type="email" placeholder="you@company.com" autocomplete="username"></div><div class="field-row"><div class="field"><label>Password (min 12)</label><input id="au_pw" type="password" autocomplete="new-password"></div><div class="field"><label>Team</label>'+selectHtml("au_team",[["","Choose later"]].concat(activeTeams().map(function(t){ return [t.id,t.name]; })),"")+'</div></div>'+(ws.joinCodeRequired!==false?'<div class="field"><label>Workspace join code</label><input id="au_code" placeholder="Ask your admin" onkeydown="if(event.key===\'Enter\')doRegister()"><div class="hint" style="margin-top:4px">An admin can change your role after registration.</div></div>':'')+'<div class="err" id="au_err"></div><button class="btn primary" style="width:100%;justify-content:center;padding:11px" onclick="doRegister()">Create account</button>';
  document.getElementById("content").innerHTML='<div class="authwrap"><div class="authcard"><div style="display:flex;align-items:center;gap:12px;margin-bottom:14px"><div class="ws-logo" style="width:44px;height:44px;border-radius:14px;font-size:16px">'+(ws.logoImg?'<img src="'+ws.logoImg+'">':esc(ws.logo||"ZC"))+'</div><div><div style="font-weight:800;font-size:18px;letter-spacing:-.02em">'+esc(ws.name||"ZenCrevia")+'</div><div class="hint">ZenCrevia · '+tr("Brand Mode")+'</div></div></div><div class="auth-language"><span>'+tr("Language")+'</span>'+lang+'</div>'+
    (API.on?(SESSION.canRegister&&(AUTH.tab==="login"||AUTH.tab==="register")?'<div class="seg" style="margin-bottom:18px;width:100%"><button style="flex:1" class="'+(AUTH.tab==="login"?"on":"")+'" onclick="AUTH.tab=\'login\';showLogin()">Log in</button><button style="flex:1" class="'+(AUTH.tab==="register"?"on":"")+'" onclick="AUTH.tab=\'register\';showLogin()">Register</button></div>':'')+(msg&&msg!=="Please sign in"?'<div class="errbox" style="margin-bottom:14px">'+esc(msg)+'</div>':'')+'<div class="authform">'+form+'</div>':
    '<div class="errbox" style="margin-bottom:14px;background:var(--color-warning-soft);color:var(--color-warning)">Demo mode. Choose a user to try the dashboard. Changes are not saved.</div><div class="demo-user-list">'+demoUsers+'</div>')+
    '</div></div>'; localizeVisibleText(document.getElementById("content")); }
function demoLogin(id){ ME=id; SESSION.user={id:id,perm:person(id).perm,name:person(id).name}; restoreLanguagePreference(); document.body.classList.remove("auth"); setConn(); applyShell(); S.screen="home"; renderScreen(false); setTimeout(showOnboardingIfNeeded,180); }
function authErr(m){ var e=document.getElementById("au_err"); if (e){ e.textContent=m; e.style.display="block"; } }
function doLogin(){ var email=val("au_email"), pw=document.getElementById("au_pw").value; if (!email||!pw) return authErr("Enter your email and password"); apiFetch("POST","/api/auth/login",{email:email,password:pw}).then(function(r){ SESSION.user=r.user; ME=r.user.id; try { localStorage.removeItem("cos.actAs"); } catch(e){} return afterLogin(); }).then(function(){ toast("Welcome back, "+first(ME)); }).catch(function(e){ authErr(e.message); }); }
function doRegister(){ var name=val("au_name"), email=val("au_email"), pw=document.getElementById("au_pw").value; if (!name||!email||!pw) return authErr("Name, email and password are required"); if (pw.length<12) return authErr("Password must be at least 12 characters"); apiFetch("POST","/api/auth/register",{name:name,email:email,password:pw,jobTitle:val("au_title"),teamId:val("au_team"),joinCode:val("au_code")}).then(function(r){ SESSION.user=r.user; ME=r.user.id; return afterLogin(); }).then(function(){ toast("Account created — welcome, "+first(ME)); }).catch(function(e){ authErr(e.message); }); }
function changePasswordModal(){ openModal("Change password",fieldHtml("cp_cur","Current password",'<input id="cp_cur" type="password" autocomplete="current-password">')+fieldHtml("cp_new","New password (min 12)",'<input id="cp_new" type="password" autocomplete="new-password">')+fieldHtml("cp_new2","Repeat new password",'<input id="cp_new2" type="password" autocomplete="new-password">'),'<button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="var a=document.getElementById(\'cp_new\').value,b=document.getElementById(\'cp_new2\').value;if(a!==b)return toast(\'Passwords do not match\',\'bad\');apiFetch(\'POST\',\'/api/auth/password\',{current:document.getElementById(\'cp_cur\').value,password:a}).then(function(){closeModal();toast(\'Password changed\')}).catch(function(e){toast(e.message,\'bad\')})">Change password</button>'); }
</script>
