<script>
/* Guides are design metadata; only DOM overlays render them, never the compositor. */
var AI_GUIDE_SELECTED=null,AI_GUIDE_DRAG=null,AI_GUIDE_SNAP=[];
function aiGuides(){return (Array.isArray(AIF.guides)?AIF.guides:[]).filter(function(g){return g&&['x','y'].includes(g.axis)&&Number.isFinite(g.position);}).slice(0,100);}
function aiGuideAtPointer(axis,e,rect,sz){var p=(axis==='x'?(e.clientX-rect.left)/rect.width*sz.w:(e.clientY-rect.top)/rect.height*sz.h);return Math.round(p*10)/10;}
function aiSnapToGuides(bounds,dx,dy,zoom,bypass){var result={dx:dx,dy:dy,guides:[]};if(!bounds||bypass||AIF.showGuides===false||AIF.snapGuides===false)return result;var tolerance=6/Math.max(.01,zoom),sz=aiActiveSize();['x','y'].forEach(function(axis){var delta=axis==='x'?dx:dy,start=bounds[axis],length=axis==='x'?bounds.w:bounds.h,best=tolerance+1,correction=0,matched=null;aiGuides().filter(function(g){return g.axis===axis&&g.position>=0&&g.position<=(axis==='x'?sz.w:sz.h);}).forEach(function(g){[start,start+length/2,start+length].forEach(function(anchor){var d=g.position-anchor-delta;if(Math.abs(d)<=tolerance&&Math.abs(d)<best){best=Math.abs(d);correction=d;matched=g.id;}});});result[axis==='x'?'dx':'dy']=delta+correction;if(matched)result.guides.push(matched);});return result;}
function aiDrawGuides(){var v=aiViewElements();if(!v)return;if(AIF.editMode===false||AIF.showGuides===false){v.wrap.querySelectorAll('.ai-guide').forEach(function(n){n.remove();});return;}var z=v.wrap.getBoundingClientRect().width/v.cv.width,list=aiGuides().filter(function(g){return !AI_GUIDE_DRAG||g.id!==AI_GUIDE_DRAG.id;});if(AI_GUIDE_DRAG)list.push(AI_GUIDE_DRAG);v.wrap.querySelectorAll('.ai-guide').forEach(function(n){if(!list.some(function(g){return g.id===n.dataset.guideId&&g.position>=0&&g.position<=(g.axis==='x'?v.cv.width:v.cv.height);}))n.remove();});list.forEach(function(g){if(g.position<0||g.position>(g.axis==='x'?v.cv.width:v.cv.height))return;var b=Array.from(v.wrap.querySelectorAll('.ai-guide')).find(function(n){return n.dataset.guideId===g.id;}),fresh=!b,selected=g.id===AI_GUIDE_SELECTED;if(!b)b=document.createElement('button');b.dataset.guideId=g.id;b.type='button';b.className='ai-guide ai-guide-'+g.axis+(selected?' selected':'')+(AI_GUIDE_SNAP.includes(g.id)?' snapped':'');b.style[g.axis==='x'?'left':'top']=(g.position*z)+'px';b.setAttribute('aria-label',tr(g.axis==='x'?'Vertical guide':'Horizontal guide')+' '+g.position+' px');b.title=tr('Drag to move. Delete to remove.');b.innerHTML='<span>'+g.position+' px</span>';if(fresh){b.addEventListener('pointerdown',function(e){aiGuideDragStart(e,g.axis,g.id);});b.addEventListener('click',function(e){e.stopPropagation();AI_GUIDE_SELECTED=g.id;aiDrawGuides();});b.addEventListener('dblclick',function(e){e.stopPropagation();aiGuideSettings(g.id);});v.wrap.append(b);}});}
function aiGuideCommit(axis,id,position,inside){var list=aiGuides(),existing=list.find(function(g){return g.id===id;});if(!inside&&!existing)return;if(inside&&existing&&existing.position===position)return;aiHistoryBefore();if(!inside){AIF.guides=list.filter(function(g){return g.id!==id;});AI_GUIDE_SELECTED=null;}else{AIF.guides=list.filter(function(g){return g.id!==id;}).concat([{id:id,axis:axis,position:position}]);AI_GUIDE_SELECTED=id;}}
function aiGuideDragStart(e,axis,id){if(e.button!==0||AI_VIEW.space||AIF.editMode===false)return;var v=aiViewElements();if(!v)return;if(!id&&aiGuides().length>=AI_SAFETY_CEILING.guides)return toast((tr('Guide limit reached.')+' '+AI_SAFETY_CEILING.guides),'bad');e.preventDefault();e.stopImmediatePropagation();var rect=v.wrap.getBoundingClientRect(),sz={w:v.cv.width,h:v.cv.height},existing=aiGuides().find(function(g){return g.id===id;}),start=aiGuideAtPointer(axis,e,rect,sz),offset=existing?existing.position-start:0;id=id||uid('guide');AI_GUIDE_SELECTED=id;aiSetSelection([]);aiShowSelectionHandle(v.wrap,v.cv);AI_GUIDE_DRAG={id:id,axis:axis,position:existing?existing.position:start};function move(ev){ev.preventDefault();AI_GUIDE_DRAG.position=Math.round((aiGuideAtPointer(axis,ev,rect,sz)+offset)*10)/10;aiDrawGuides();}function finish(ev,cancel){if(!AI_GUIDE_DRAG)return;var p=AI_GUIDE_DRAG.position,viewport=v.el.getBoundingClientRect(),inside=ev&&ev.clientX>=viewport.left&&ev.clientX<=viewport.right&&ev.clientY>=viewport.top&&ev.clientY<=viewport.bottom&&p>=0&&p<=(axis==='x'?sz.w:sz.h);AI_GUIDE_DRAG=null;window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);window.removeEventListener('pointercancel',abort);window.removeEventListener('keydown',key,true);window.removeEventListener('blur',abort);if(!cancel)aiGuideCommit(axis,id,p,inside);else AI_GUIDE_SELECTED=existing?id:null;aiDrawGuides();aiRefreshProperties();}function up(ev){move(ev);finish(ev,false);}function abort(){finish(null,true);}function key(ev){if(ev.key==='Escape'){ev.preventDefault();ev.stopImmediatePropagation();abort();}}window.addEventListener('pointermove',move,{passive:false});window.addEventListener('pointerup',up);window.addEventListener('pointercancel',abort);window.addEventListener('keydown',key,true);window.addEventListener('blur',abort);aiDrawGuides();}
function aiDeleteGuide(){if(!aiGuides().some(function(g){return g.id===AI_GUIDE_SELECTED;}))return;aiHistoryBefore();AIF.guides=aiGuides().filter(function(g){return g.id!==AI_GUIDE_SELECTED;});AI_GUIDE_SELECTED=null;aiDrawGuides();}
function aiAddGuide(axis){if(aiGuides().length>=AI_SAFETY_CEILING.guides)return toast((tr('Guide limit reached.')+' '+AI_SAFETY_CEILING.guides),'bad');var sz=aiActiveSize(),id=uid('guide');aiGuideCommit(axis,id,(axis==='x'?sz.w:sz.h)/2,true);AIF.showGuides=true;closeModal();aiDrawGuides();}
function aiGuideSettings(id){var guide=aiGuides().find(function(g){return g.id===id;});openModal('Guides','<p>'+tr('Drag from the top ruler for a horizontal guide, or from the left ruler for a vertical guide.')+'</p><label class="ai-guide-option"><input type="checkbox" '+(AIF.showGuides!==false?'checked':'')+' onchange="AIF.showGuides=this.checked;aiDrawGuides()">'+tr('Show guides')+'</label><label class="ai-guide-option"><input type="checkbox" '+(AIF.snapGuides!==false?'checked':'')+' onchange="AIF.snapGuides=this.checked">'+tr('Snap layers to guides')+'</label>'+(guide?'<div class="field"><label for="aiGuidePosition">'+tr('Guide position (px)')+'</label><input id="aiGuidePosition" type="number" min="0" max="'+(guide.axis==='x'?aiActiveSize().w:aiActiveSize().h)+'" step="0.1" value="'+guide.position+'"></div><button class="btn" onclick="aiGuidePositionSave(\''+guide.id+'\')">'+tr('Apply position')+'</button>':'')+'<div class="ai-guide-add"><button class="btn" onclick="aiAddGuide(\'x\')">'+tr('Add vertical guide')+'</button><button class="btn" onclick="aiAddGuide(\'y\')">'+tr('Add horizontal guide')+'</button></div><p class="hint">'+tr('Drag a guide outside the canvas area to remove it. Hold Alt while moving layers to ignore snapping.')+'</p>','<button class="btn danger-soft" '+(!aiGuides().length?'disabled':'')+' onclick="aiHistoryBefore();AIF.guides=[];AI_GUIDE_SELECTED=null;closeModal();aiDrawGuides()">'+tr('Clear guides')+'</button><button class="btn primary" onclick="closeModal()">'+tr('Done')+'</button>');}
function aiGuidePositionSave(id){var g=aiGuides().find(function(g){return g.id===id;}),p=Number(val('aiGuidePosition'));if(!g||!Number.isFinite(p)||p<0||p>(g.axis==='x'?aiActiveSize().w:aiActiveSize().h))return toast(tr('Enter a position within the canvas.'),'bad');aiGuideCommit(g.axis,id,Math.round(p*10)/10,true);closeModal();aiDrawGuides();}
var aiGuidesRulerDraw=aiRulerDraw;
aiRulerDraw=function(){aiGuidesRulerDraw();var v=aiViewElements(),frame=v&&v.el.closest('.ai-canvas-frame');if(frame)frame.querySelectorAll('.ai-ruler-x,.ai-ruler-y').forEach(function(ruler){if(ruler.dataset.guidesBound)return;ruler.dataset.guidesBound='true';var axis=ruler.classList.contains('ai-ruler-x')?'y':'x';ruler.title=tr(axis==='y'?'Drag down to add a horizontal guide':'Drag right to add a vertical guide');ruler.addEventListener('pointerdown',function(e){AIF.showGuides=true;aiGuideDragStart(e,axis);});});aiDrawGuides();};
var aiGuidesZoomUI=aiCanvasZoomUI;
aiCanvasZoomUI=function(percent){aiGuidesZoomUI(percent);var bar=document.querySelector('.ai-canvas-toolbar');if(bar&&!bar.querySelector('#aiGuidesButton')){var b=document.createElement('button');b.id='aiGuidesButton';b.className='btn ai-view-pill';b.textContent=tr('Guides');b.onclick=function(){aiGuideSettings();};bar.append(b);}};
var aiGuidesKeys=aiMultiKeydown;
aiMultiKeydown=function(e){var key=e.key.toLowerCase();if(AI_GUIDE_SELECTED&&aiGuides().some(function(g){return g.id===AI_GUIDE_SELECTED;})&&['delete','backspace','escape'].includes(key)){e.preventDefault();e.stopImmediatePropagation();if(key==='escape'){AI_GUIDE_SELECTED=null;aiDrawGuides();}else aiDeleteGuide();return true;}return aiGuidesKeys(e);};
var aiGuidesChooseLayer=aiChooseLayer;
aiChooseLayer=function(id,e,toggle){AI_GUIDE_SELECTED=null;aiGuidesChooseLayer(id,e,toggle);};
var aiGuidesSetSelection=aiSetSelection;
aiSetSelection=function(ids){if(ids.length)AI_GUIDE_SELECTED=null;aiGuidesSetSelection(ids);};
var aiGuidesCanvasClick=aiCanvasEditAt;
aiCanvasEditAt=function(e,cv){AI_GUIDE_SELECTED=null;aiGuidesCanvasClick(e,cv);aiDrawGuides();};
var aiGuidesHelp=aiShortcutHelp;
aiShortcutHelp=function(){aiGuidesHelp();var el=document.getElementById('aiShortcutHelp');if(el)el.insertAdjacentHTML('beforeend','<p><b>'+tr('Guides')+'</b><br>'+tr('Drag from the top ruler for a horizontal guide, or from the left ruler for a vertical guide.')+'<br>'+tr('Drag a guide outside the canvas area to remove it. Hold Alt while moving layers to ignore snapping.')+'<br>'+tr('Select a guide, then press Delete. Double-click a guide to enter its position. Guides are never exported.')+'</p>');};
Object.assign(UI_ID,{'Guides':'Garis bantu','Vertical guide':'Garis bantu vertikal','Horizontal guide':'Garis bantu horizontal','Drag to move. Delete to remove.':'Seret untuk memindahkan. Delete untuk menghapus.','Maximum 100 guides.':'Maksimal 100 garis bantu.','Show guides':'Tampilkan garis bantu','Snap layers to guides':'Tempelkan layer ke garis bantu','Guide position (px)':'Posisi garis bantu (px)','Apply position':'Terapkan posisi','Add vertical guide':'Tambah garis vertikal','Add horizontal guide':'Tambah garis horizontal','Clear guides':'Hapus semua garis','Enter a position within the canvas.':'Masukkan posisi di dalam kanvas.','Drag down to add a horizontal guide':'Tarik ke bawah untuk menambah garis horizontal','Drag right to add a vertical guide':'Tarik ke kanan untuk menambah garis vertikal','Drag from the top ruler for a horizontal guide, or from the left ruler for a vertical guide.':'Tarik dari penggaris atas untuk garis horizontal, atau dari penggaris kiri untuk garis vertikal.','Drag a guide outside the canvas area to remove it. Hold Alt while moving layers to ignore snapping.':'Seret garis keluar area kanvas untuk menghapusnya. Tahan Alt saat menggeser layer untuk melewati snap.','Select a guide, then press Delete. Double-click a guide to enter its position. Guides are never exported.':'Pilih garis lalu tekan Delete. Klik dua kali untuk mengisi posisi. Garis bantu tidak ikut diekspor.'});
</script>
