<script>
/* ============================================================
   v18.1 EMOJI
   Emoji are Unicode (open standard). Graphics come from Twemoji
   (open source: code MIT, artwork CC-BY 4.0, github.com/jdecked/twemoji),
   loaded per emoji as SVG from jsDelivr when the browser is online and
   falling back to the OS emoji font when it is not — so the standalone
   demo and an offline workspace both keep working. One picker serves the
   composer, message reactions and the quick reaction bar.
   ============================================================ */
var EMOJI_CDN="https://cdn.jsdelivr.net/gh/jdecked/twemoji@15.1.0/assets/svg/";
var EMOJI_MODE=(function(){ try{ return localStorage.getItem("cos.emoji.mode")||"twemoji"; }catch(e){ return "twemoji"; } })();
var EMOJI_RECENT_KEY="cos.emoji.recent";
/* [emoji, keywords (en id)] grouped by category; keywords kept short on purpose */
var EMOJI_CATEGORIES=[
  ["smileys","Smileys",[["😀","grin senyum"],["😃","smile senyum"],["😄","happy senang"],["😁","beam grin"],["😆","laugh tawa"],["😅","sweat laugh"],["🤣","rofl ngakak"],["😂","joy tawa"],["🙂","slight smile"],["🙃","upside"],["😉","wink kedip"],["😊","blush senyum"],["😇","angel halo"],["🥰","love hearts"],["😍","heart eyes cinta"],["🤩","star struck"],["😘","kiss cium"],["😗","kiss"],["😚","kiss"],["😙","kiss"],["🥲","tear smile"],["😋","yum enak"],["😛","tongue lidah"],["😜","wink tongue"],["🤪","zany"],["😝","squint tongue"],["🤑","money uang"],["🤗","hug peluk"],["🤭","giggle"],["🤫","shush diam"],["🤔","thinking mikir"],["🫡","salute"],["🤐","zipper"],["🤨","raised eyebrow"],["😐","neutral datar"],["😑","expressionless"],["😶","no mouth"],["😏","smirk"],["😒","unamused"],["🙄","eye roll"],["😬","grimace"],["😮‍💨","exhale"],["🤥","lying"],["😌","relieved lega"],["😔","pensive sedih"],["😪","sleepy ngantuk"],["🤤","drool"],["😴","sleep tidur"],["😷","mask masker"],["🤒","sick sakit"],["🤕","hurt"],["🤢","nausea"],["🤮","vomit"],["🤧","sneeze"],["🥵","hot panas"],["🥶","cold dingin"],["🥴","woozy"],["😵","dizzy pusing"],["🤯","mind blown"],["🤠","cowboy"],["🥳","party pesta"],["🥸","disguise"],["😎","cool sunglasses"],["🤓","nerd"],["🧐","monocle"],["😕","confused bingung"],["🫤","diagonal"],["😟","worried khawatir"],["🙁","frown"],["☹️","frown"],["😮","open mouth"],["😯","hushed"],["😲","astonished"],["😳","flushed malu"],["🥺","pleading"],["🥹","holding tears"],["😦","frowning"],["😧","anguished"],["😨","fearful takut"],["😰","anxious cemas"],["😥","sad relieved"],["😢","cry nangis"],["😭","sob nangis"],["😱","scream"],["😖","confounded"],["😣","persevere"],["😞","disappointed kecewa"],["😓","downcast"],["😩","weary lelah"],["😫","tired capek"],["🥱","yawn"],["😤","triumph"],["😡","angry marah"],["😠","angry marah"],["🤬","cursing"],["😈","devil"],["💀","skull"],["💩","poop"],["🤡","clown"],["👻","ghost hantu"],["👽","alien"],["🤖","robot"],["😺","cat"],["😸","cat grin"],["😹","cat joy"],["😻","cat love"],["🙈","see no evil"],["🙉","hear no evil"],["🙊","speak no evil"]]],
  ["gestures","People",[["👋","wave halo"],["🤚","raised back"],["🖐️","hand"],["✋","stop"],["🖖","vulcan"],["👌","ok oke"],["🤌","pinched"],["🤏","pinch"],["✌️","peace"],["🤞","crossed fingers semoga"],["🫰","finger heart"],["🤟","love you"],["🤘","rock"],["🤙","call me"],["👈","left"],["👉","right"],["👆","up"],["🖕","middle"],["👇","down"],["☝️","index up"],["👍","thumbs up setuju bagus"],["👎","thumbs down"],["✊","fist"],["👊","punch"],["🤛","left fist"],["🤜","right fist"],["👏","clap tepuk"],["🙌","raised hands hore"],["🫶","heart hands"],["👐","open hands"],["🤲","palms up"],["🤝","handshake deal"],["🙏","pray thanks terima kasih tolong"],["✍️","writing"],["💅","nail"],["🤳","selfie"],["💪","muscle strong semangat"],["🦾","mechanical arm"],["🧠","brain"],["👀","eyes lihat"],["👁️","eye"],["👄","mouth"],["🫀","heart"],["👶","baby"],["🧒","child"],["👦","boy"],["👧","girl"],["🧑","person"],["👨","man"],["👩","woman"],["🧓","older"],["👨‍💻","technologist coding"],["👩‍💻","technologist coding"],["👨‍🎨","artist"],["👩‍🎨","artist"],["🧑‍💼","office"],["🕵️","detective"],["🙋","raising hand"],["🙇","bow"],["🤷","shrug"],["🤦","facepalm"],["💁","tipping hand"],["🙅","no"],["🙆","ok"],["🧘","meditate"],["🏃","run lari"],["🚶","walk"],["💃","dance"],["🕺","dance"],["👯","bunny ears"],["👫","couple"],["👥","busts team"],["🗣️","speaking"]]],
  ["nature","Nature",[["🐶","dog anjing"],["🐱","cat kucing"],["🐭","mouse"],["🐹","hamster"],["🐰","rabbit kelinci"],["🦊","fox"],["🐻","bear"],["🐼","panda"],["🐨","koala"],["🐯","tiger"],["🦁","lion"],["🐮","cow"],["🐷","pig"],["🐸","frog"],["🐵","monkey"],["🐔","chicken ayam"],["🐧","penguin"],["🐦","bird burung"],["🦆","duck"],["🦅","eagle"],["🦉","owl"],["🦋","butterfly"],["🐛","bug"],["🐝","bee"],["🐞","ladybug"],["🐢","turtle"],["🐍","snake"],["🐙","octopus"],["🦑","squid"],["🐟","fish ikan"],["🐬","dolphin"],["🐳","whale"],["🦈","shark"],["🐊","crocodile"],["🦒","giraffe"],["🐘","elephant gajah"],["🦏","rhino"],["🐪","camel"],["🦘","kangaroo"],["🐉","dragon naga"],["🌵","cactus"],["🎄","tree"],["🌲","evergreen"],["🌴","palm"],["🌱","seedling"],["🌿","herb"],["☘️","shamrock"],["🍀","clover luck"],["🍁","maple"],["🍂","leaves"],["🍃","leaf"],["🌸","blossom"],["🌹","rose mawar"],["🌺","hibiscus"],["🌻","sunflower"],["🌼","flower bunga"],["🌷","tulip"],["🌍","earth bumi"],["🌙","moon bulan"],["⭐","star bintang"],["🌟","glowing star"],["✨","sparkles kilau"],["⚡","lightning"],["🔥","fire api panas"],["🌈","rainbow"],["☀️","sun"],["⛅","cloud"],["🌧️","rain hujan"],["⛈️","storm"],["❄️","snow"],["💧","drop"],["🌊","wave"]]],
  ["food","Food",[["🍏","green apple"],["🍎","apple apel"],["🍐","pear"],["🍊","orange jeruk"],["🍋","lemon"],["🍌","banana pisang"],["🍉","watermelon"],["🍇","grapes"],["🍓","strawberry"],["🫐","blueberry"],["🍒","cherry"],["🍑","peach"],["🥭","mango"],["🍍","pineapple nanas"],["🥥","coconut"],["🥑","avocado"],["🍆","eggplant"],["🥦","broccoli"],["🌽","corn"],["🌶️","chili pedas"],["🥐","croissant"],["🍞","bread roti"],["🧀","cheese"],["🍗","chicken"],["🍔","burger"],["🍟","fries"],["🍕","pizza"],["🌮","taco"],["🍜","noodle mie"],["🍣","sushi"],["🍚","rice nasi"],["🍛","curry"],["🍲","stew"],["🥗","salad"],["🍿","popcorn"],["🍩","donut"],["🍪","cookie"],["🎂","cake kue ulang tahun"],["🍰","cake"],["🧁","cupcake"],["🍫","chocolate"],["🍬","candy"],["☕","coffee kopi"],["🍵","tea teh"],["🧋","boba"],["🥤","cup"],["🍺","beer"],["🍻","cheers"],["🥂","clink"],["🍷","wine"]]],
  ["activity","Activity",[["⚽","soccer bola"],["🏀","basketball"],["🏈","football"],["⚾","baseball"],["🎾","tennis"],["🏐","volleyball"],["🏓","ping pong"],["🏸","badminton"],["🥊","boxing"],["🥋","martial"],["⛳","golf"],["🏆","trophy juara"],["🥇","gold medal"],["🥈","silver"],["🥉","bronze"],["🏅","medal"],["🎖️","military"],["🎗️","ribbon"],["🎫","ticket"],["🎪","circus"],["🎭","theater"],["🎨","art palette desain"],["🎬","clapper film"],["🎤","mic"],["🎧","headphone"],["🎼","score"],["🎹","piano"],["🥁","drum"],["🎷","sax"],["🎺","trumpet"],["🎸","guitar"],["🎻","violin"],["🎲","dice"],["♟️","chess"],["🎯","target bullseye"],["🎳","bowling"],["🎮","game"],["🕹️","joystick"],["🧩","puzzle"]]],
  ["travel","Travel",[["🚗","car mobil"],["🚕","taxi"],["🚌","bus"],["🏎️","race"],["🚓","police"],["🚑","ambulance"],["🚒","fire truck"],["🚚","truck"],["🛵","scooter"],["🏍️","motorcycle motor"],["🚲","bike sepeda"],["🛴","kick scooter"],["🚆","train kereta"],["🚇","metro mrt"],["✈️","airplane pesawat"],["🚀","rocket launch luncur"],["🛸","ufo"],["🚁","helicopter"],["⛵","sailboat"],["🚢","ship kapal"],["⚓","anchor"],["🏠","house rumah"],["🏢","office kantor"],["🏥","hospital"],["🏦","bank"],["🏫","school"],["🏬","store"],["🏭","factory"],["🕌","mosque masjid"],["⛪","church"],["🗼","tower"],["🗽","liberty"],["🏰","castle"],["🏖️","beach pantai"],["🏝️","island"],["🏔️","mountain gunung"],["🌋","volcano"],["🗺️","map peta"],["🧭","compass"],["🛣️","road"]]],
  ["objects","Objects",[["⌚","watch"],["📱","phone hp"],["💻","laptop"],["🖥️","desktop"],["🖨️","printer"],["⌨️","keyboard"],["🖱️","mouse"],["💾","floppy save"],["💿","cd"],["📷","camera"],["📸","flash"],["🎥","movie"],["📺","tv"],["📻","radio"],["🔋","battery"],["🔌","plug"],["💡","idea lampu ide"],["🔦","flashlight"],["🕯️","candle"],["💰","money bag uang"],["💵","dollar"],["💳","card"],["💎","gem"],["⚖️","scale"],["🔧","wrench"],["🔨","hammer"],["⚙️","gear setting"],["🔩","bolt"],["🧲","magnet"],["🧪","test tube"],["🔬","microscope"],["🔭","telescope"],["💊","pill"],["🩹","bandage"],["🧹","broom"],["🧺","basket"],["🧻","paper"],["🛒","cart"],["🎁","gift hadiah"],["🎈","balloon"],["🎉","party tada selamat"],["🎊","confetti"],["🎀","ribbon"],["🪄","magic wand"],["📦","package paket"],["📫","mailbox"],["✉️","envelope email"],["📩","incoming"],["📝","memo note catatan"],["📄","page doc"],["📊","chart bar"],["📈","chart up naik"],["📉","chart down turun"],["📋","clipboard"],["📌","pin"],["📍","location lokasi"],["📎","paperclip"],["🖇️","clips"],["📏","ruler"],["✂️","scissors"],["🗂️","dividers"],["📁","folder"],["📂","open folder"],["🗓️","calendar"],["📅","date tanggal"],["⏰","alarm"],["⏳","hourglass"],["⌛","time"],["🔒","lock"],["🔓","unlock"],["🔑","key"],["🔔","bell notif"],["🔕","mute"],["📣","megaphone"],["📢","loudspeaker"],["🔍","search cari"],["🔎","magnifier"],["🏷️","tag label"],["🧾","receipt"],["✏️","pencil"],["🖌️","brush kuas"],["🖍️","crayon"],["🎨","palette"],["🗑️","trash"]]],
  ["symbols","Symbols",[["❤️","heart love cinta"],["🧡","orange heart"],["💛","yellow heart"],["💚","green heart"],["💙","blue heart"],["💜","purple heart"],["🖤","black heart"],["🤍","white heart"],["🤎","brown heart"],["💔","broken heart"],["❣️","exclamation heart"],["💕","two hearts"],["💞","revolving"],["💓","beating"],["💗","growing"],["💖","sparkling"],["💘","cupid"],["💝","gift heart"],["💯","hundred 100"],["💢","anger"],["💥","boom"],["💫","dizzy"],["💦","sweat"],["💨","dash"],["🕳️","hole"],["💬","speech chat"],["👁️‍🗨️","eye speech"],["🗨️","left speech"],["🗯️","anger bubble"],["💭","thought"],["💤","zzz"],["✅","check done selesai ok"],["☑️","ballot"],["✔️","check mark"],["❌","cross x salah"],["❎","cross"],["➕","plus"],["➖","minus"],["➗","divide"],["✖️","multiply"],["♾️","infinity"],["❓","question tanya"],["❗","exclamation"],["⚠️","warning peringatan"],["🚫","prohibited"],["🔞","18"],["♻️","recycle"],["✳️","asterisk"],["❇️","sparkle"],["🔅","dim"],["🔆","bright"],["🔴","red circle"],["🟠","orange circle"],["🟡","yellow circle"],["🟢","green circle"],["🔵","blue circle"],["🟣","purple circle"],["⚫","black circle"],["⚪","white circle"],["🔶","orange diamond"],["🔷","blue diamond"],["⬆️","up"],["⬇️","down"],["➡️","right"],["⬅️","left"],["🔄","refresh"],["🔁","repeat"],["▶️","play"],["⏸️","pause"],["⏹️","stop"],["⏩","fast forward"],["🔊","loud"],["🔇","muted"],["📶","signal"],["🆕","new baru"],["🆗","ok"],["🆙","up"],["🆒","cool"],["🆓","free gratis"],["🏁","finish"],["🚩","flag"],["🏳️","white flag"],["🏴","black flag"],["🇮🇩","indonesia"]]]
];
var EMOJI_QUICK=["👍","❤️","😂","🎉","👀","✅","🙏","✨"];
var EMOJI_INDEX=null;
function emojiIndex(){ if(EMOJI_INDEX) return EMOJI_INDEX; EMOJI_INDEX=[]; EMOJI_CATEGORIES.forEach(function(c){ c[2].forEach(function(e){ EMOJI_INDEX.push({e:e[0],k:e[1].toLowerCase(),cat:c[0]}); }); }); return EMOJI_INDEX; }
/* Twemoji file names: code points in hex joined by "-", U+FE0F dropped unless it is a keycap (Twemoji convention). */
function emojiCode(e){ var cps=[]; for(var i=0;i<e.length;i++){ var c=e.codePointAt(i); if(c>0xffff) i++; cps.push(c); } if(cps.indexOf(0x20e3)<0) cps=cps.filter(function(c){ return c!==0xfe0f; }); return cps.map(function(c){ return c.toString(16); }).join("-"); }
function emojiHtml(e,cls){ if(EMOJI_MODE!=="twemoji"||!navigator.onLine) return '<span class="emj'+(cls?" "+cls:"")+'">'+esc(e)+'</span>'; return '<img class="emj'+(cls?" "+cls:"")+'" src="'+EMOJI_CDN+emojiCode(e)+'.svg" alt="'+attr(e)+'" draggable="false" loading="lazy" onerror="this.replaceWith(document.createTextNode(this.alt))">'; }
function emojiRecent(){ try{ return JSON.parse(localStorage.getItem(EMOJI_RECENT_KEY)||"[]"); }catch(e){ return []; } }
function emojiRemember(e){ var r=emojiRecent().filter(function(x){ return x!==e; }); r.unshift(e); try{ localStorage.setItem(EMOJI_RECENT_KEY,JSON.stringify(r.slice(0,24))); }catch(x){} }
var EMOJI_PICK={cb:null,cat:"recent",q:""};
/* emojiPicker(anchor, onPick(emoji)) — one picker for the composer and reactions. */
function emojiPicker(anchor,onPick){ EMOJI_PICK.cb=onPick; EMOJI_PICK.q=""; EMOJI_PICK.cat=emojiRecent().length?"recent":"smileys"; openMenu("ctxMenu",anchor,emojiPickerHtml(),"left"); var m=document.getElementById("ctxMenu"); m.classList.add("emoji-menu"); setTimeout(function(){ var i=m.querySelector(".emoji-search"); if(i) i.focus(); place(m,anchor); },10); }
function emojiPickerHtml(){ var q=EMOJI_PICK.q.trim().toLowerCase(), cat=EMOJI_PICK.cat, tabs=[["recent","🕘",tr("Recent")]].concat(EMOJI_CATEGORIES.map(function(c){ return [c[0],c[2][0][0],tr(c[1])]; }));
  var items=q?emojiIndex().filter(function(x){ return x.k.indexOf(q)>=0||x.e===q; }).slice(0,96):cat==="recent"?emojiRecent().map(function(e){ return {e:e}; }):((EMOJI_CATEGORIES.filter(function(c){ return c[0]===cat; })[0]||EMOJI_CATEGORIES[0])[2].map(function(e){ return {e:e[0]}; }));
  return '<div class="emoji-head"><input class="emoji-search" placeholder="'+attr(tr("Search emoji…"))+'" value="'+attr(EMOJI_PICK.q)+'" oninput="EMOJI_PICK.q=this.value;emojiRefresh()" onkeydown="if(event.key===\'Escape\'){closePops()}if(event.key===\'Enter\'){var b=this.closest(\'.emoji-menu\').querySelector(\'.emoji-grid button\');if(b)b.click()}"></div>'
    +'<div class="emoji-tabs">'+tabs.map(function(t){ return '<button class="'+(cat===t[0]&&!q?"on":"")+'" title="'+attr(t[2])+'" onclick="EMOJI_PICK.cat=\''+t[0]+'\';EMOJI_PICK.q=\'\';emojiRefresh()">'+emojiHtml(t[1])+'</button>'; }).join("")+'</div>'
    +'<div class="emoji-grid">'+(items.length?items.map(function(x){ return '<button title="'+attr(x.e)+'" onclick="emojiChoose(\''+attr(x.e)+'\')">'+emojiHtml(x.e)+'</button>'; }).join(""):'<div class="ep-empty">'+tr(cat==="recent"&&!q?"No recent emoji yet":"No emoji found")+'</div>')+'</div>'
    +'<div class="emoji-foot"><span>'+(EMOJI_MODE==="twemoji"?'Twemoji · CC-BY 4.0':tr("System emoji"))+'</span><button class="btn xs ghost" onclick="EMOJI_MODE=EMOJI_MODE===\'twemoji\'?\'native\':\'twemoji\';try{localStorage.setItem(\'cos.emoji.mode\',EMOJI_MODE)}catch(e){}emojiRefresh()">'+tr(EMOJI_MODE==="twemoji"?"Use system emoji":"Use Twemoji")+'</button></div>'; }
function emojiRefresh(){ var m=document.getElementById("ctxMenu"); if(!m||!m.classList.contains("emoji-menu")) return; var i=m.querySelector(".emoji-search"), pos=i?i.selectionStart:0, focused=document.activeElement===i; m.innerHTML=emojiPickerHtml(); if(focused){ var n=m.querySelector(".emoji-search"); n.focus(); n.setSelectionRange(pos,pos); } if(m._anchor) place(m,m._anchor); }
function emojiChoose(e){ emojiRemember(e); var cb=EMOJI_PICK.cb; closePops(); var m=document.getElementById("ctxMenu"); if(m) m.classList.remove("emoji-menu"); if(cb) cb(e); }
Object.assign(UI_ID,{"Recent":"Terbaru","Smileys":"Ekspresi","People":"Orang","Nature":"Alam","Food":"Makanan","Activity":"Aktivitas","Travel":"Tempat","Objects":"Objek","Symbols":"Simbol","Search emoji…":"Cari emoji…","No recent emoji yet":"Belum ada emoji terbaru","No emoji found":"Emoji tidak ditemukan","System emoji":"Emoji sistem","Use system emoji":"Pakai emoji sistem","Use Twemoji":"Pakai Twemoji"});
</script>
