<script>
/* ============================================================
   KNOWLEDGE BASE — folders, favorites, pinning, search, markdown (§62)
   ============================================================ */
function mdToHtml(md){ var lines=md.split("\n"); var out=[], inList=null, inTable=false; var inline=function(s){ return esc(s).replace(/`([^`]+)`/g,"<code>$1</code>").replace(/\*\*([^*]+)\*\*/g,"<b>$1</b>").replace(/\*([^*]+)\*/g,"<i>$1</i>").replace(/\[([^\]]+)\]\(([^)]+)\)/g,'<a href="$2" target="_blank" style="color:var(--color-primary);text-decoration:underline">$1</a>'); };
  var closeList=function(){ if (inList){ out.push("</"+inList+">"); inList=null; } }; var closeTable=function(){ if (inTable){ out.push("</tbody></table>"); inTable=false; } };
  lines.forEach(function(l){ if (/^\|/.test(l)){ closeList(); var cells=l.replace(/^\||\|$/g,"").split("|").map(function(c){ return c.trim(); }); if (/^\|?\s*-+/.test(l)) return; if (!inTable){ inTable=true; out.push("<table><thead><tr>"+cells.map(function(c){ return "<th>"+inline(c)+"</th>"; }).join("")+"</tr></thead><tbody>"); } else out.push("<tr>"+cells.map(function(c){ return "<td>"+inline(c)+"</td>"; }).join("")+"</tr>"); return; } closeTable();
    var m; if ((m=l.match(/^(#{1,3})\s+(.*)/))){ closeList(); out.push("<h"+m[1].length+">"+inline(m[2])+"</h"+m[1].length+">"); } else if ((m=l.match(/^[-*]\s+(.*)/))){ if (inList!=="ul"){ closeList(); inList="ul"; out.push("<ul>"); } out.push("<li>"+inline(m[1])+"</li>"); } else if ((m=l.match(/^\d+\.\s+(.*)/))){ if (inList!=="ol"){ closeList(); inList="ol"; out.push("<ol>"); } out.push("<li>"+inline(m[1])+"</li>"); } else if ((m=l.match(/^>\s?(.*)/))){ closeList(); out.push("<blockquote>"+inline(m[1])+"</blockquote>"); } else if (!l.trim()){ closeList(); } else { closeList(); out.push("<p>"+inline(l)+"</p>"); } });
  closeList(); closeTable(); return out.join("\n"); }
/* The built-in wiki is documentation, so it has a complete curated Indonesian reader view.
   Custom pages keep the language written by their author. */
var KB_ID={
  k1:{folder:"Mulai di sini",title:"Dari permintaan kreatif hingga persetujuan — alur kerja",body:"# Cara kerja mengalir\n\nSetiap pekerjaan mengikuti alur yang sama agar semua orang tahu posisi pekerjaannya.\n\n1. **Permintaan** — Tim Marketing mengirim permintaan kreatif.\n2. **Brief** — Lead mengubahnya menjadi brief kreatif yang terstruktur.\n3. **Produksi** — Penanggung jawab mengunggah versi pekerjaan.\n4. **Review** — Reviewer menyetujui atau meminta revisi dengan masukan yang jelas.\n5. **Pengiriman** — File yang sudah disetujui masuk ke daftar pengiriman.\n\n> Patokan sederhana: jika belum ada di ZenCrevia, berarti belum menjadi tugas."},
  k2:{folder:"SOP Kepatuhan",title:"Hal yang akan ditolak oleh compliance",body:"# Hal yang akan ditolak oleh compliance\n\nKirim materi ke tahap **Compliance** sebelum dipublikasikan. Hal-hal berikut hampir selalu dikembalikan:\n\n1. Angka apa pun yang ditampilkan sebagai imbal hasil yang diharapkan.\n2. Kata *pasti*, *dijamin*, *bebas risiko*, atau padanannya dalam bahasa Inggris.\n3. Tangkapan layar P/L akun nyata, walau sudah diburamkan.\n4. Disclaimer risiko di bawah 11 pt atau kontrasnya kurang dari 4,5:1.\n5. Lockup regulator tidak ada di bagian footer.\n6. Testimoni yang menyebut nominal profit.\n\nJika ragu: jelaskan produknya, bukan hasil yang dijanjikan."},
  k2b:{folder:"SOP Desain",title:"Etika saat melakukan review",body:"# Etika saat melakukan review\n\n- Lakukan review maksimal **satu hari kerja**.\n- Gunakan anotasi gambar untuk masukan posisi; gunakan komentar untuk arahan.\n- Satu putaran revisi untuk setiap versi — kumpulkan masukanmu sekaligus.\n- Komentar internal tetap bersifat internal. Komentar yang terlihat pemangku kepentingan ditulis untuk mereka.\n- Semua materi publik tetap melewati **Compliance** setelah review internal, bukan sebagai penggantinya."},
  k3:{folder:"Panduan Brand",title:"Warna",body:"# Warna\n\nWarna utama **HSB Navy** `#0B2A5B`. Gunakan signal blue `#1F4FD8` dan paper `#F4F6FA` sebagai pendamping.\n\n- Hijau `#16A34A` dan merah `#DC2626` adalah **warna market saja** — untuk naik dan turun. Jangan digunakan hanya sebagai dekorasi.\n- Disclaimer risiko harus memiliki kontras 4,5:1 pada latar apa pun. Tidak ada pengecualian."},
  k4:{folder:"Panduan Brand",title:"Tipografi",body:"# Tipografi\n\nJudul: **Poppins** (600/700).\nTeks isi: **Inter**.\nAngka pada grafik dan tabel harga: selalu gunakan **Inter tabular figures**.\n\n| Peran | Ukuran | Leading |\n|---|---|---|\n| Display | 64–96 | 0,95 |\n| Judul | 32–48 | 1,05 |\n| Teks isi | 15–17 | 1,5 |\n| Disclaimer | min. 11 | 1,35 |"},
  k5:{folder:"SOP Desain",title:"Fotografi",body:"# Fotografi\n\nGunakan orang nyata yang bekerja di meja atau memakai ponsel, dengan cahaya siang yang sejuk. Hindari tumpukan uang, mobil mewah, dan visual stok bertema “sukses” — ketiganya akan ditolak oleh compliance. Grafik adalah ilustrasi; jangan pernah memakai tangkapan layar akun nyata."},
  k6:{folder:"Penamaan File",title:"Aturan penamaan",body:"# Aturan penamaan\n\n`{project}-{deliverable}-v{n}.{ext}`\n\nContoh:\n\n- `hsbpro-hero-v2.psd`\n- `standee-branch12-v1.ai`\n\nFile final menggunakan akhiran `-FINAL` dan disalin ke folder pengiriman."},
  k7:{folder:"Panduan Ekspor",title:"Ekspor untuk web dan aplikasi",body:"# Ekspor untuk web dan aplikasi\n\n- Hero: 1920×720 WebP, ≤ 350 KB\n- App splash: 1170×2532 PNG @2x\n- Selalu ekspor varian 2x dan 1x; beri nama `@2x` dan `@1x`."},
  k8:{folder:"Spesifikasi Sosial",title:"Instagram dan TikTok",body:"# Instagram dan TikTok\n\n| Format | Ukuran | Area aman |\n|---|---|---|\n| Feed | 1080×1350 | 80 px di sisi kiri dan kanan |\n| Story / Reels | 1080×1920 | 250 px atas, 340 px bawah |\n| TikTok | 1080×1920 | 300 px bawah |"},
  k9:{folder:"SOP Video",title:"Pengiriman Reels dan TikTok",body:"# Pengiriman Reels dan TikTok\n\n- Master: ProRes 422, 1080×1920, 30 fps.\n- Kirim H.264 ≤ 30 MB dengan caption yang sudah menyatu di video.\n- Buat pembuka dengan suara pada detik pertama; end card logo berdurasi 1,5 detik."},
  k10:{folder:"Mulai di sini",title:"Sinkronisasi kreatif mingguan",body:"# Sinkronisasi kreatif mingguan\n\nSetiap Senin pukul 10.00. Agenda berasal dari dashboard: tugas terlambat lebih dulu, lalu yang membutuhkan review, kemudian beban kerja."}
};
function kbView(k){ var original=byId(CREATIVE_OS_DEMO.knowledge,k.id), t=k.translations&&k.translations.id; if(UI_LANG==="id"&&t&&(t.title||t.body||t.folder))return Object.assign({},k,{title:t.title||k.title,body:t.body||k.body,folder:t.folder||k.folder}); var builtin=UI_LANG==="id"&&original&&k.title===original.title&&k.body===original.body&&k.folder===original.folder&&KB_ID[k.id]; return builtin?Object.assign({},k,builtin):k; }
function kbFolderView(f){if(UI_LANG!=="id")return f.name;if(f.nameId)return f.nameId;var sample=CREATIVE_OS_DEMO.knowledge.filter(function(k){return k.folder===f.name&&KB_ID[k.id];})[0];return sample?KB_ID[sample.id].folder:f.name;}
function kbFolderRecords(){ var out=(KNOWLEDGE_FOLDERS||[]).slice(); KNOWLEDGE.forEach(function(k){if(!out.some(function(f){return f.name===k.folder;}))out.push({id:"legacy_"+k.folder,name:k.folder,nameId:"",sort:999});}); return out.sort(function(a,b){return kbFolderView(a).localeCompare(kbFolderView(b));}); }
function kbFolders(){return kbFolderRecords().map(kbFolderView);}
function kbFolderForPage(k){var f=kbFolderRecords().filter(function(x){return x.name===k.folder;})[0];return f?kbFolderView(f):kbView(k).folder;}
function kbFolderPicker(inputId,value,labelId){var f=kbFolderRecords().filter(function(x){return x.name===value;})[0],label=f?kbFolderView(f):(value||tr("Choose folder"));return '<input type="hidden" id="'+inputId+'" value="'+attr(value||"")+'"><button type="button" class="kb-folder-trigger" data-menu onclick="kbFolderMenu(this,\''+inputId+'\',\''+(labelId||inputId+"_label")+'\')"><span id="'+(labelId||inputId+"_label")+'">'+esc(label)+'</span>'+I.chevd+'</button>';}
function kbFolderMenu(anchor,inputId,labelId){var rows=kbFolderRecords().map(function(f){return '<button class="kb-folder-option" data-search="'+attr((f.name+" "+(f.nameId||"")).toLowerCase())+'" onclick="kbChooseFolder(\''+inputId+'\',\''+labelId+'\',\''+attr(f.id)+'\')"><span>'+esc(kbFolderView(f))+'</span>'+(f.nameId&&f.name!==f.nameId?'<small>'+esc(UI_LANG==="id"?f.name:f.nameId)+'</small>':'')+'</button>';}).join("");var searchIcon='<svg class="i" viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="M20 20l-4-4"/></svg>';ctxMenu(anchor,'<div class="kb-folder-search">'+searchIcon+'<input autofocus aria-label="'+attr(tr("Search folders"))+'" placeholder="'+attr(tr("Search folders…"))+'" oninput="kbFilterFolders(this.value)"></div><div class="kb-folder-options">'+(rows||'<div class="hint" style="padding:10px">'+tr("No folders yet")+'</div>')+'</div><div class="kb-folder-foot"><button onclick="kbFolderNewInline(\''+inputId+'\',\''+labelId+'\')">'+I.plus+tr("Add new folder")+'</button></div>',"anchor");}
function kbFilterFolders(q){q=String(q||"").toLowerCase();document.querySelectorAll("#ctxMenu .kb-folder-option").forEach(function(b){b.hidden=b.getAttribute("data-search").indexOf(q)<0;});}
function kbChooseFolder(inputId,labelId,id){var f=byId(KNOWLEDGE_FOLDERS,id)||kbFolderRecords().filter(function(x){return x.id===id;})[0];if(!f)return;var input=document.getElementById(inputId),label=document.getElementById(labelId);if(input)input.value=f.name;if(label)label.textContent=kbFolderView(f);closePops();}
function kbFolderNewInline(inputId,labelId){var m=document.getElementById("ctxMenu");m.innerHTML='<div class="mh">'+tr("New folder")+'</div><div class="kb-folder-new"><label>English<input id="kfn_en" placeholder="Design SOP"></label><label>Indonesia<input id="kfn_id" placeholder="SOP Desain"></label><div><button class="btn sm" onclick="kbFolderMenu(document.querySelector(\'[onclick*=kbFolderMenu]\')||document.body,\''+inputId+'\',\''+labelId+'\')">'+tr("Cancel")+'</button><button class="btn sm primary" onclick="kbCreateFolder(\''+inputId+'\',\''+labelId+'\')">'+tr("Add folder")+'</button></div></div>';var i=document.getElementById("kfn_en");if(i)i.focus();}
function kbCreateFolder(inputId,labelId){var name=val("kfn_en").trim(),nameId=val("kfn_id").trim();if(!name&&!nameId)return toast(tr("Folder name is required"),"bad");name=name||nameId;var f={id:uid("kf"),name:name,nameId:nameId,sort:KNOWLEDGE_FOLDERS.length+1};KNOWLEDGE_FOLDERS.push(f);var input=document.getElementById(inputId),label=document.getElementById(labelId);if(input)input.value=f.name;if(label)label.textContent=kbFolderView(f);closePops();persistKnowledgeFolder(f);toast(tr("Folder added"));}
function deleteKnowledgeFolder(id){var f=byId(KNOWLEDGE_FOLDERS,id);if(!f)return;var n=KNOWLEDGE.filter(function(k){return k.folder===f.name;}).length;confirmModal(tr("Delete folder?"),n?fmt(tr("{n} pages will move to General."),{n:n}):tr("The empty folder will be removed."),function(){deleteKnowledgeFolderById(id);toast(tr("Folder deleted"),"bad");},true);}
function searchKnowledge(input){var at=input.selectionStart;S.kbQuery=input.value;renderScreen(false);var el=document.getElementById("kbSearch");if(el){el.focus();el.setSelectionRange(at,at);}}
function renderKnowledge(){ var pages=KNOWLEDGE.map(kbView), q=(S.kbQuery||"").toLowerCase(); var match=function(k){var raw=page(k.id),trn=raw&&raw.translations&&raw.translations.id||{};return !q||[k.title,k.body,k.folder,raw&&raw.title,raw&&raw.body,trn.title,trn.body,trn.folder].some(function(v){return String(v||"").toLowerCase().indexOf(q)>=0;});}; if (!S.kbPage||!page(S.kbPage)) S.kbPage=(KNOWLEDGE[0]||{}).id; var rawCur=page(S.kbPage), cur=rawCur&&kbView(rawCur), ed=canI.manageKnowledge();
  var item=function(k){ return '<button class="'+(S.kbPage===k.id?"on":"")+'" onclick="S.kbPage=\''+k.id+'\';S.kbEdit=false;renderScreen(false)"><svg class="kbs'+(k.fav?" on":"")+'" viewBox="0 0 24 24"><path d="M12 3l2.8 5.8 6.2.9-4.5 4.4 1.1 6.3L12 17.5 6.4 20.4l1.1-6.3L3 9.7l6.2-.9z"/></svg><span style="overflow:hidden;text-overflow:ellipsis">'+esc(k.title)+'</span></button>'; };
  var pinned=pages.filter(function(k){ return k.pinned&&match(k); }), favs=pages.filter(function(k){ return k.fav&&match(k); });
  var tree='<div class="kb-tree"><div style="padding:4px 6px 8px"><input type="text" id="kbSearch" placeholder="Search pages…" value="'+attr(S.kbQuery)+'" oninput="searchKnowledge(this)" style="width:100%;border:1px solid var(--color-border);border-radius:var(--pill);padding:6px 12px;font-size:var(--fs-sm);outline:none"></div>'+(pinned.length?'<div class="sec">'+I.pin.replace("<svg",'<svg width="12" height="12" stroke="currentColor" fill="none" stroke-width="2"')+'Pinned</div>'+pinned.map(item).join(""):'')+(favs.length?'<div class="sec">Favorites</div>'+favs.map(item).join(""):'')+kbFolderRecords().map(function(f){var ps=pages.filter(function(k){return page(k.id).folder===f.name&&match(k);});if(!ps.length&&q)return "";return '<div class="sec kb-folder-sec"><span>'+esc(kbFolderView(f))+'</span>'+(ed&&String(f.id).indexOf("legacy_")!==0?'<button title="'+attr(tr("Delete folder"))+'" onclick="deleteKnowledgeFolder(\''+f.id+'\')">'+I.trash+'</button>':'')+'</div>'+ps.map(item).join("");}).join("")+(ed?'<button onclick="newPageModal()" class="kb-tree-add">'+I.plus.replace("<svg",'<svg class="kbs"')+tr("New page")+'</button>':'')+'</div>';
  var main; if (!cur) main='<div class="panel">'+emptyBox("No pages yet","Create the first page of your creative wiki.",I.knowledge)+'</div>';
  else if (S.kbEdit){var idt=rawCur.translations&&rawCur.translations.id||{};main='<div class="panel"><div class="panel-head"><b>'+tr("Bilingual content")+'</b><span class="spacer"></span><button class="btn" onclick="S.kbEdit=false;renderScreen(false)">'+tr("Cancel")+'</button><button class="btn primary" onclick="savePage()">'+tr("Save")+'</button></div><div class="panel-body pad"><div class="kb-bi-grid"><section><div class="kb-lang">🇺🇸 English</div>'+fieldHtml("kb_title","Title",'<input id="kb_title" value="'+attr(rawCur.title)+'">')+fieldHtml("kb_folder_wrap","Folder",kbFolderPicker("kb_folder",rawCur.folder,"kb_folder_label"))+fieldHtml("kb_body_wrap","Content",'<textarea class="md-edit" id="kb_body">'+esc(rawCur.body)+'</textarea>')+'</section><section><div class="kb-lang">🇮🇩 Indonesia</div>'+fieldHtml("kb_title_id","Judul",'<input id="kb_title_id" value="'+attr(idt.title||"")+'" placeholder="'+attr(rawCur.title)+'">')+fieldHtml("kb_folder_id_wrap","Folder",'<input id="kb_folder_id" value="'+attr(idt.folder||"")+'" placeholder="'+attr(kbFolderForPage(rawCur))+'">')+fieldHtml("kb_body_id_wrap","Konten",'<textarea class="md-edit" id="kb_body_id" placeholder="'+attr(tr("Optional — English is used as fallback"))+'">'+esc(idt.body||"")+'</textarea>')+'</section></div><div class="hint" style="margin-top:8px">Markdown: # headings, **bold**, - lists, > quotes, | tables |, [links](url)</div></div></div>';}
  else main='<div class="panel"><div class="panel-head"><span class="hint">'+esc(cur.folder)+' · '+esc(person(cur.by).name)+' · '+tr("updated")+' '+ago(cur.ago)+'</span><span class="spacer"></span><button class="iconbtn flat" title="Favorite" onclick="togglePage(\''+cur.id+'\',\'fav\')" style="color:'+(cur.fav?"var(--color-warning)":"inherit")+'">'+I.star.replace("<svg",'<svg '+(cur.fav?'fill="currentColor"':''))+'</button><button class="iconbtn flat" title="Pin" onclick="togglePage(\''+cur.id+'\',\'pinned\')" style="color:'+(cur.pinned?"var(--color-primary)":"inherit")+'">'+I.pin+'</button>'+(ed?'<button class="btn sm" onclick="S.kbEdit=true;renderScreen(false)">'+I.edit+'Edit</button><button class="btn sm ghost" aria-label="'+attr(tr("Delete page"))+'" onclick="deletePage(\''+cur.id+'\')">'+I.trash+'</button>':'')+'</div><div class="panel-body pad"><div class="md">'+mdToHtml(cur.body)+'</div></div></div>';
  var mobile='<div class="kb-mobile"><select onchange="S.kbPage=this.value;S.kbEdit=false;renderScreen(false)">'+(pinned.length?'<optgroup label="Pinned">'+pinned.map(function(k){ return '<option value="'+k.id+'"'+(S.kbPage===k.id?" selected":"")+'>'+esc(k.title)+'</option>'; }).join("")+'</optgroup>':'')+kbFolderRecords().map(function(f){var ps=pages.filter(function(k){return page(k.id).folder===f.name&&match(k);});return ps.length?'<optgroup label="'+attr(kbFolderView(f))+'">'+ps.map(function(k){return '<option value="'+k.id+'"'+(S.kbPage===k.id?" selected":"")+'>'+esc(k.title)+(k.fav?" ★":"")+'</option>';}).join("")+'</optgroup>':'';}).join("")+'</select><button class="iconbtn" title="Search" onclick="var q=prompt(\'Search pages\',S.kbQuery||\'\');if(q!==null){S.kbQuery=q;renderScreen(false)}"><svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="M20 20l-3.5-3.5"/></svg></button>'+(ed?'<button class="iconbtn" title="New page" onclick="newPageModal()">'+I.plus+'</button>':'')+'</div>';
  document.getElementById("content").innerHTML='<div class="pagehead m-head"><div><h1>Knowledge</h1><div class="muted" style="margin-top:4px">'+pages.length+' '+tr("pages")+' · '+kbFolders(pages).length+' '+tr("folders")+' · '+(UI_LANG==="id"?"SOP, spesifikasi, dan panduan":"SOPs, specs and guidelines")+'</div></div><div class="actions">'+(ed?'<button class="btn primary m-primary" aria-label="'+attr(tr("New page"))+'" onclick="newPageModal()">'+I.plus+'New page</button>':'')+'</div></div>'+mobile+'<div class="kb">'+tree+'<div>'+main+'</div></div>'; }
function togglePage(id,k){ var p=page(id); p[k]=!p[k]; renderScreen(false); persistPage(p,false); }
function savePage(){var p=page(S.kbPage),title=val("kb_title").trim();if(!title)return toast(tr("Title is required"),"bad");p.title=title;p.folder=val("kb_folder")||"General";p.body=document.getElementById("kb_body").value;p.translations=p.translations||{};p.translations.id={title:val("kb_title_id").trim(),folder:val("kb_folder_id").trim(),body:document.getElementById("kb_body_id").value};p.ago=0;p.by=ME;S.kbEdit=false;toast("Page saved");renderScreen(false);persistPage(p,false);}
function createKnowledgePage(){var title=val("np_title").trim(),titleId=val("np_title_id").trim();if(!title&&!titleId)return toast(tr("Title is required"),"bad");title=title||titleId;var p={id:uid("k"),folder:val("np_folder")||"General",title:title,by:ME,ago:0,body:val("np_body")||("# "+title+"\n\nStart writing…"),translations:{id:{title:titleId,folder:val("np_folder_id").trim(),body:val("np_body_id")}},fav:false,pinned:false};KNOWLEDGE.push(p);S.kbPage=p.id;S.kbEdit=false;closeModal();renderScreen(false);persistPage(p,true);toast(tr("Page created"));}
function newPageModal(){var first=kbFolderRecords()[0];openModal("New page",'<div class="kb-bi-grid"><section><div class="kb-lang">🇺🇸 English</div>'+fieldHtml("np_title","Title",'<input id="np_title" placeholder="e.g. Print production checklist">')+fieldHtml("np_folder_wrap","Folder",kbFolderPicker("np_folder",first?first.name:"General","np_folder_label"))+fieldHtml("np_body_wrap","Content",'<textarea id="np_body" placeholder="# Heading\n\nStart writing…"></textarea>')+'</section><section><div class="kb-lang">🇮🇩 Indonesia</div>'+fieldHtml("np_title_id","Judul",'<input id="np_title_id" placeholder="mis. Checklist produksi cetak">')+fieldHtml("np_folder_id","Nama folder Indonesia",'<input id="np_folder_id" placeholder="opsional">')+fieldHtml("np_body_id","Konten",'<textarea id="np_body_id" placeholder="# Judul\n\nMulai menulis…"></textarea>')+'</section></div>','<button class="btn" onclick="closeModal()">'+tr("Cancel")+'</button><button class="btn primary" onclick="createKnowledgePage()">'+tr("Create")+'</button>',true);}
function deletePage(id){ confirmModal("Delete page?","This cannot be undone.",function(){ deletePageById(id); S.kbPage=null; toast("Page deleted","bad"); renderScreen(false); },true); }
</script>
