<script>
/* ============================================================
   PROJECTS — list + detail (Overview · Board · List · Grid · Calendar · Timeline · Files · Activity · Settings) (§42–43)
   ============================================================ */
function projStatusBadge(p){ return p.status==="risk"?'<span class="badge revision">'+tr("At risk")+'</span>':p.status==="done"?'<span class="badge approved">'+tr("Done")+'</span>':p.status==="archived"?'<span class="badge done">'+tr("Archived")+'</span>':'<span class="badge prog">'+tr("Active")+'</span>'; }
function projectRiskInfo(p){ var open=projOpen(p), over=open.filter(function(t){return t.due<0;}).length, parts=[]; if(p.due<0) parts.push(Math.abs(p.due)+"d past deadline"); if(over) parts.push(over+" task"+(over===1?"":"s")+" overdue"); if(!parts.length&&p.due<=7&&p.status==="risk") parts.push("deadline is within "+Math.max(0,p.due)+"d"); if(!parts.length&&p.status==="risk") parts.push("needs an owner review"); return parts.join(" · "); }
function archiveProject(id,restore){ var p=project(id); p.status=restore?"done":"archived"; if (!restore) p.archivedAt=new Date().toISOString(); else p.archivedAt=null; logWorkspace(restore?"project_restored":"project_archived","project",id,{project:id,what:p.name}); toast(restore?"Project restored":"Project archived — still accessible under Archived"); refresh(); if (API.on) apiFetch("POST","/api/projects/"+id+"/archive",{restore:!!restore}).then(function(list){ PROJECTS=list.map(hProject); refresh(); }).catch(function(e){ fail(e); reloadAll(); }); }
function renderProjects(){ if (S.projectId) return renderProject(S.projectId);
  var h='<div class="pagehead m-head"><div><h1>'+tr("Projects")+'</h1><div class="muted" style="margin-top:4px">'+PROJECTS.length+' '+tr("projects")+' · '+PROJECTS.filter(function(p){return p.status==="risk";}).length+' '+tr("at risk")+'<span class="desktop-only"> · '+tr("drag rows to reorder")+'</span></div></div><div class="actions"><button class="btn desktop-only" onclick="exportModal(\'xlsx\')">'+I.download+'Excel</button>'+(canI.createProject()?'<button class="btn primary m-primary" aria-label="'+attr(tr("New project"))+'" onclick="newProjectModal()">'+I.plus+tr("New project")+'</button>':'')+'</div></div>';
  var arch=PROJECTS.filter(function(p){ return p.status==="archived"; }); S.projView=S.projView||"active"; var rows=S.projView==="active"?liveProjects():S.projView==="archived"?arch:PROJECTS;
  h+='<div class="toolbar"><div class="seg"><button class="'+(S.projView==="active"?"on":"")+'" onclick="S.projView=\'active\';renderScreen(false)">'+tr("Active")+' <span class="cnt">'+liveProjects().length+'</span></button><button class="'+(S.projView==="archived"?"on":"")+'" onclick="S.projView=\'archived\';renderScreen(false)">'+tr("Archived")+' <span class="cnt">'+arch.length+'</span></button><button class="'+(S.projView==="all"?"on":"")+'" onclick="S.projView=\'all\';renderScreen(false)">'+tr("All")+'</button></div><span class="hint desktop-only">'+tr("Done projects are archived automatically the month after completion; archived ones stay fully accessible.")+'</span></div>';
  /* v29 empty state: a clean workspace showed a bare table header with no guidance */
  /* v38.1 #11: this branch returned the HTML instead of drawing it, so an empty workspace kept showing
     the previous screen (Home) under the Projects tab and the "New project" button never appeared */
  if(!rows.length){ document.getElementById("content").innerHTML=h+'<div class="panel">'+emptyBox(S.projView==="archived"?tr("No archived projects"):tr("No projects yet"),S.projView==="archived"?tr("Completed projects move here automatically the month after they finish."):tr("Projects group related tasks, milestones and final assets. Create the first one to start planning."),I.folder||I.plus,(S.projView!=="archived"&&canI.createProject&&canI.createProject())?'<button class="btn primary" onclick="newProjectModal()">'+I.plus+tr("New project")+'</button>':'')+'</div>'; return; }
  h+='<div class="panel"><div class="tbl-wrap"><table class="tbl proj-tbl"><thead><tr><th></th><th>'+tr("Project")+'</th><th>'+tr("Owner")+'</th><th>'+tr("Teams")+'</th><th>'+tr("People")+'</th><th>'+tr("Status")+'</th><th>'+tr("Tasks")+'</th><th>'+tr("Deadline")+'</th><th style="min-width:160px">'+tr("Progress")+'</th></tr></thead><tbody>'+rows.slice().sort(function(a,b){ return (a.sort||0)-(b.sort||0); }).map(function(p){ var open=projOpen(p); var over=open.filter(function(t){return t.due<0;}).length, riskText=projectRiskInfo(p), progress=projectProgress(p); return '<tr draggable="true" data-pid="'+p.id+'" ondragstart="pStart(event,\''+p.id+'\')" ondragover="event.preventDefault();this.classList.add(\'drop-before\')" ondragleave="this.classList.remove(\'drop-before\')" ondrop="pDrop(event,\''+p.id+'\')" onclick="go(\'projects\',\''+p.id+'\')"><td class="drag-h">'+I.drag+'</td><td class="t"><div>'+esc(p.name)+'</div><div class="tiny muted" style="font-weight:400">'+esc(p.description)+'</div></td><td><span class="cell-flex">'+av(p.owner)+esc(first(p.owner))+'</span></td><td><span style="display:flex;gap:4px;flex-wrap:wrap">'+(p.teams||[]).map(function(t){ return teamBadge(t); }).join("")+'</span></td><td><span class="av-stack">'+p.team.slice(0,4).map(function(m){ return av(m); }).join("")+'</span></td><td>'+projStatusBadge(p)+(p.status==="risk"?'<div class="tiny" style="color:var(--color-danger);margin-top:4px;max-width:180px">'+esc(riskText)+'</div>':'')+'</td><td class="mono">'+open.length+' '+tr("open")+(over?' <span style="color:var(--color-danger)">· '+over+' '+tr("overdue")+'</span>':'')+'</td><td><span class="due '+(p.due<0&&p.status!=="done"&&p.status!=="archived"?"over":"")+'">'+dueDate(p.due)+(p.status==="done"||p.status==="archived"?' · '+tr("completed"):' · '+dueTxt(p.due))+'</span></td><td><div style="display:flex;align-items:center;gap:8px"><div class="pbar '+(p.status==="risk"?"bad":"")+'" style="flex:1"><i style="width:'+progress+'%"></i></div><span class="pct">'+progress+'%</span></div></td></tr>'; }).join("")+'</tbody></table></div></div>';
  document.getElementById("content").innerHTML=h; }
var PDRAG=null; function pStart(e,id){ PDRAG=id; e.dataTransfer.effectAllowed="move"; }
function pDrop(e,targetId){ e.preventDefault(); document.querySelectorAll(".drop-before").forEach(function(x){ x.classList.remove("drop-before"); }); var id=PDRAG; PDRAG=null; if (!id||id===targetId) return; var order=PROJECTS.slice().sort(function(a,b){ return (a.sort||0)-(b.sort||0); }); var mv=byId(order,id); order.splice(order.indexOf(mv),1); order.splice(order.findIndex(function(p){ return p.id===targetId; }),0,mv); order.forEach(function(p,i){ p.sort=i+1; }); renderScreen(false); if (API.on) apiFetch("POST","/api/projects/reorder",{ids:order.map(function(p){ return p.id; })}).catch(function(e){ fail(e); reloadAll(); }); }
function beginProjectTextEdit(id){ S.projectTextEdit=id; renderScreen(false); setTimeout(function(){ var el=document.getElementById("pj_desc"); if(el)el.focus(); },0); }
function cancelProjectTextEdit(){ S.projectTextEdit=null; renderScreen(false); }
function projectProgressBreakdown(info){ var parts=[]; if(info.taskPct!=null)parts.push(tr("Tasks")+" "+info.taskPct+"% · "+info.taskDone+"/"+info.taskTotal+(info.totalEffort?" · "+info.doneEffort+"/"+info.totalEffort+"h":"")); if(info.milestonePct!=null)parts.push(tr("Milestones")+" "+info.milestonePct+"% · "+info.milestoneDone+"/"+info.milestoneTotal); return parts.length?parts.join("<span>+</span>"):tr("Progress starts when tasks or milestones are added"); }
function projectDescriptionPanel(p,ed){ var editing=ed&&S.projectTextEdit===p.id, body="", action="", progress=projectProgressInfo(p);
  if(!editing){
    body='<div class="project-description-view"><div class="project-copy-section"><div class="eyebrow">Description</div><div class="project-copy'+(p.description?'':' empty')+'">'+(p.description?esc(p.description):tr("Not set"))+'</div></div><div class="project-copy-section"><div class="eyebrow">Objective / project brief</div><div class="project-copy'+(p.brief?'':' empty')+'">'+(p.brief?esc(p.brief):tr("Not set"))+'</div></div><div class="project-progress-view"><span>'+tr("Progress")+'</span><div class="pbar"><i style="width:'+progress.value+'%"></i></div><b>'+progress.value+'%</b><div class="project-progress-breakdown">'+projectProgressBreakdown(progress)+'</div></div></div>';
    action=ed?'<button class="btn sm" onclick="beginProjectTextEdit(\''+p.id+'\')">'+I.edit+tr("Edit")+'</button>':'';
  } else {
    body='<div class="project-description-edit"><div class="eyebrow">Description</div><textarea class="desc" id="pj_desc" placeholder="What is this project about?" style="min-height:60px">'+esc(p.description||"")+'</textarea><div class="eyebrow" style="margin:12px 0 6px">Objective / project brief</div><textarea class="desc" id="pj_brief" placeholder="Objective, channels, budget, constraints…" style="min-height:110px">'+esc(p.brief||"")+'</textarea><div class="project-progress-auto"><b>'+tr("Automatic progress")+' · '+progress.value+'%</b><span>'+projectProgressBreakdown(progress)+'</span></div><div class="project-description-actions"><span class="spacer"></span><button class="btn sm" onclick="cancelProjectTextEdit()">'+tr("Cancel")+'</button><button class="btn sm primary" onclick="saveProjectText(\''+p.id+'\')">'+I.check+tr("Save")+'</button></div></div>';
  }
  return panel("Description & objective",null,body,null,action,I.knowledge,"project-description-panel"+(editing?" editing":""));
}
function renderProject(id){ var p=project(id); if (!p){ S.projectId=null; return renderProjects(); } var ts=sortTasks(TASKS.filter(function(t){ return t.proj===id; })); var open=ts.filter(function(t){ return !isClosed(t); }); var over=open.filter(function(t){ return t.due<0; }); var inrev=open.filter(function(t){ return isReview(t); }); var hours=0; open.forEach(function(t){ hours+=t.effort; }); var ed=canI.createProject()||p.owner===ME, progress=projectProgress(p);
  var tabs=[["overview","Overview"],["board","Board"],["list","List"],["grid","Grid"],["calendar","Calendar"],["timeline","Timeline"],["assets","Assets"],["files","Files"],["activity","Activity"],["settings","Settings"]];
  var h='<div><button class="btn ghost sm" onclick="go(\'projects\')">'+I.back+'All projects</button></div><div class="pagehead project-pagehead"><div><div class="date">'+esc(first(p.owner))+' · '+dueDate(p.start)+' → '+dueDate(p.due)+'</div><h1 '+(ed?'contenteditable="true"':'')+' spellcheck="false" onblur="editProject(\''+id+'\',\'name\',this.textContent)">'+esc(p.name)+'</h1><div style="margin-top:6px;display:flex;gap:8px;align-items:center;flex-wrap:wrap">'+projStatusBadge(p)+(p.teams||[]).map(function(t){ return teamBadge(t); }).join("")+p.tags.map(function(t){ return '<span class="badge">'+esc(t)+'</span>'; }).join("")+'</div></div><div class="actions">'+(ed?'<label class="pillsel"><span>Status</span><select onchange="editProject(\''+id+'\',\'status\',this.value)"><option value="active"'+(p.status==="active"?" selected":"")+'>Active</option><option value="risk"'+(p.status==="risk"?" selected":"")+'>At risk</option><option value="done"'+(p.status==="done"?" selected":"")+'>Done</option><option value="archived"'+(p.status==="archived"?" selected":"")+'>Archived</option></select></label>':'')+(canI.createTask()?'<button class="btn primary project-new-task" aria-label="'+attr(tr("New task"))+'" onclick="newTaskModal({proj:\''+id+'\'})">'+I.plus+'<span>New task</span></button>':'')+'</div></div>';
  if (p.status==="archived") h+='<div class="errbox" style="background:var(--color-surface-sunken);color:var(--color-text-primary)">'+I.check+' This project is archived — it stays readable and its tasks are hidden from boards unless the “Archived” filter is on. '+(ed?'<button class="btn sm" onclick="archiveProject(\''+id+'\',true)">'+I.sync+'Restore project</button>':'')+'</div>';
  if (p.status==="risk") h+='<div class="errbox">'+I.bell+'<div><b>Project needs attention.</b><br><span class="tiny">'+esc(projectRiskInfo(p))+'</span></div><span class="spacer"></span><button class="btn sm" onclick="S.filters={status:\'\',kind:\'\',assignee:\'\',reviewer:\'\',proj:\''+id+'\',prio:\'\',team:\'\',tag:\'\',dependency:\'\',due:\'overdue\',archived:\'\',hidden:\'\'};S.taskScope=\'all\';go(\'tasks\',\'list\')">Review overdue tasks</button></div>';
  h+='<div class="ptabs">'+tabs.map(function(t){ return '<button data-tab="'+t[0]+'" class="tab'+(S.projectTab===t[0]?" on":"")+'" onclick="S.projectTab=\''+t[0]+'\';renderScreen(false)">'+t[1]+'</button>'; }).join("")+'</div>';
  var tb=S.projectTab;
  if (tb==="overview"){ h+='<div class="kpis kpis-4">'+kpi("accent",open.length,"Open tasks","in this project","S.projectTab='board';renderScreen(false)",I.tasks,"blue")+kpi("",inrev.length,"In review","need a decision","",I.eye,"ink")+kpi(over.length?"danger":"good",over.length,"Overdue",over.length?"act now":"all clear","",I.bell,over.length?"red":"green")+kpi("",hours+"h","Remaining effort","estimated · progress "+progress+"%","",I.analytics,"lime")+'</div>';
    h+='<div class="grid g-2-1">'+projectDescriptionPanel(p,ed)+panel("Milestones",p.milestones.length,milestoneRows(p)+(ed?'<div class="panel-foot"><button class="btn sm" onclick="addMilestoneModal(\''+id+'\')">'+I.plus+'Add milestone</button></div>':''),null,null,I.calendar)+'</div>';
    h+=projAssetPanel(p,ts,true);
    h+='<div class="grid g-2-1">'+panel("Open tasks",open.length,open.length?open.map(function(t){ return taskRow(t); }).join(""):emptyBox("No open tasks","Everything in this project is closed."),null,null,I.tasks)+panel("Team",p.team.length,p.team.map(function(m){ var pp=person(m); return '<div class="member" onclick="go(\'team\',\''+m+'\')">'+av(m,"lg")+'<div><div class="t" style="font-weight:600">'+esc(pp.name)+'</div><div class="tiny muted">'+esc(pp.role)+' · '+teamBadge(primaryTeam(m))+'</div></div><span class="mono tiny muted">'+ts.filter(function(t){return isAssignee(t,m)&&!isClosed(t);}).length+' open</span></div>'; }).join(""),null,null,I.team)+'</div>'; }
  else if (tb==="board"||tb==="list"||tb==="grid"||tb==="calendar"||tb==="timeline"){ var saved=S.taskScope, sv=S.taskView; S.taskScope="all"; S.taskView=tb==="board"?"kanban":tb; h+=filterBar({noScope:true,noProject:true}); h+=taskViewBody(filteredTasks()); S.taskScope=saved; S.taskView=sv; }
  else if (tb==="assets"){ h+=projAssetPanel(p,ts,false); }
  else if (tb==="files"){ var files=[]; ts.forEach(function(t){ t.files.forEach(function(f){ files.push({f:f,t:t}); }); t.versions.forEach(function(v){ files.push({v:v,t:t}); }); }); h+=panel("Files & versions",files.length,files.length?'<div class="panel-body pad">'+files.map(function(x){ if (x.v){ return '<div class="file"><span class="thumb" style="width:40px;height:32px;background:'+x.v.color+'">V'+x.v.n+'</span><div style="min-width:0"><div class="t">'+esc(x.t.title)+' · Version '+x.v.n+'</div><div class="m"><span class="mono">'+esc(x.t.id)+'</span><span>·</span><span>'+esc(person(x.v.by).name)+'</span><span>·</span><span>'+ago(x.v.ago)+'</span></div></div>'+fileTaskActions(x.t,verBadge(x.v))+'</div>'; } return '<div class="file">'+fileIcon(x.f)+'<div style="min-width:0"><div class="t">'+esc(x.f.name)+'</div><div class="m">'+srcBadge(srcOf(x.f))+'<span>'+esc(x.t.id)+' · '+esc(x.f.size)+' · '+ago(x.f.ago)+'</span></div></div>'+fileTaskActions(x.t,"")+'</div>'; }).join("")+'</div>':emptyBox("No files yet","Files attached to tasks in this project appear here.",I.cloud),null,null,I.cloud); }
  else if (tb==="activity") h+=panel("Activity",null,activityRows(ACTIVITY.filter(function(a){ var t=a.a.task?task(a.a.task):null; return (t&&t.proj===id)||a.a.project===id; }),30)||emptyBox("No activity yet",""),null,null,I.sync);
  else h+=projectSettings(p,ed);
  document.getElementById("content").innerHTML=h; }
S.assetScope=S.assetScope||"done";
function projAssetPanel(p,ts,compact){
  var scope=S.assetScope; var pool=ts.filter(function(t){ return taskAssetLinks(t).length||assetCount(t); });
  var list=scope==="done"?pool.filter(isClosed):pool;
  var total=assetsProduced(ts), delivered=assetsProduced(ts.filter(isClosed)), links=assetLinks(list).length;
  var seg='<div class="seg"><button class="'+(scope==="done"?"on":"")+'" onclick="S.assetScope=\'done\';renderScreen(false)">Done only</button><button class="'+(scope==="all"?"on":"")+'" onclick="S.assetScope=\'all\';renderScreen(false)">All tasks</button></div>';
  var body=list.length?list.map(function(t){ var fin=finalAssetLink(t); var ls=taskAssetLinks(t);
      return '<div class="alink project-asset-row" style="align-items:flex-start" role="button" tabindex="0" aria-label="'+attr(tr("Open")+" "+t.id)+'" onclick="openTask(\''+t.id+'\')" onkeydown="if((event.key===\'Enter\'||event.key===\' \')&&event.target===this){event.preventDefault();openTask(\''+t.id+'\')}"><span class="ficon" style="background:'+(isClosed(t)?"var(--color-success)":"var(--color-ink)")+'">'+(isClosed(t)?"OK":"WIP")+'</span>'
        +'<div style="min-width:0;flex:1"><div class="t">'+esc(t.title)+'</div>'
        +'<div class="m"><span class="mono">'+t.id+'</span>'+teamBadge(t.team)+statusBadge(t.status)+assetBadge(t)+(ls.length?'<span>'+ls.length+' link'+(ls.length===1?"":"s")+'</span>':'<span class="hint">no link yet</span>')+'</div>'
        +(fin?'<div class="u">'+esc(fin.url)+'</div>':'')+'</div>'
        +'<div style="display:flex;gap:4px;flex-wrap:wrap;justify-content:flex-end">'+(fin?'<button class="btn xs primary" onclick="event.stopPropagation();openExternal(\''+attr(fin.url)+'\')">'+I.ext+(fin.kind==="version"?"Final V"+fin.v:"Open")+'</button>':'')+'<button class="btn xs" onclick="event.stopPropagation();openTask(\''+t.id+'\');setTab(\'files\')">'+I.assets.replace('class="i"','')+(ls.length>1?"All "+ls.length:"Task")+'</button></div></div>'; }).join("")
    :emptyBox(scope==="done"?"No delivered assets yet":"No assets linked yet","Set “Assets produced” on a task and attach the final file or cloud link \u2014 it shows up here.",I.link);
  return panel("Final assets"+(compact?"":" \u00b7 "+p.name),links,body,null,seg+'<span class="badge">'+delivered+' delivered</span><span class="badge">'+total+' total</span>',I.assets.replace('class="i"',''));
}
function projectSettings(p,ed){ if (!ed) return '<div class="panel">'+emptyBox("Read-only","Only the project owner or a creative lead can change project settings.",I.lock)+'</div>'; var id=p.id;
  return '<section class="panel"><div class="panel-head"><span class="sq">'+I.settings+'</span><h2>Project settings</h2></div><div class="panel-body pad">'+fieldHtml("ep_name","Name",'<input id="ep_name" value="'+attr(p.name)+'">')+'<div class="field-row">'+fieldHtml("ep_owner","Owner",selectHtml("ep_owner",peopleOpts(),p.owner))+fieldHtml("ep_status","Status",selectHtml("ep_status",[["active","Active"],["risk","At risk"],["done","Done"],["archived","Archived"]],p.status))+'</div><div class="field-row">'+fieldHtml("ep_start","Start",'<input id="ep_start" type="date" value="'+iso(p.start)+'">')+fieldHtml("ep_due","Deadline",'<input id="ep_due" type="date" value="'+iso(p.due)+'">')+'</div>'+fieldHtml("ep_tags","Tags",tagPicker("ep_tags",p.tags||[],"",{readonly:!canI.createProject()}))+fieldHtml("ep_teams","Teams",'<div class="chips">'+activeTeams().map(function(t){ return '<label class="chipx" style="cursor:pointer;--tc:'+teamColorCss(t.color)+'"><input type="checkbox" data-pteam="'+t.id+'"'+((p.teams||[]).indexOf(t.id)>=0?" checked":"")+'> <span class="tdot"></span> '+esc(t.name)+'</label>'; }).join("")+'</div>')+fieldHtml("ep_team","Members",'<div class="chips">'+peopleOpts().map(function(o){ return '<label class="chipx" style="cursor:pointer"><input type="checkbox" data-team="'+o[0]+'"'+(p.team.indexOf(o[0])>=0?" checked":"")+'> '+esc(o[1])+'</label>'; }).join("")+'</div>')+'</div><div class="panel-foot">'+(canI.createProject()?'<button class="btn danger-soft" onclick="deleteProject(\''+id+'\')">'+I.trash+'Delete project</button>':'')+'<span class="spacer"></span><button class="btn primary" onclick="saveProject(\''+id+'\')">Save changes</button></div></section>'; }
function milestoneRows(p){ if (!p.milestones.length) return emptyBox("No milestones","Add the checkpoints that matter."); return p.milestones.slice().sort(function(a,b){ return a.due-b.due; }).map(function(m){ var i=p.milestones.indexOf(m); return '<div class="ms"><span class="chk'+(m.done?" on":"")+'" onclick="toggleMs(\''+p.id+'\','+i+')">'+(m.done?I.check:'')+'</span><div class="t'+(m.done?" done":"")+'" style="font-weight:600">'+esc(m.name)+'</div><span class="due '+(!m.done&&m.due<0?"over":(!m.done&&m.due===0?"today":""))+'">'+dueDate(m.due)+' · '+dueTxt(m.due)+'</span>'+(canI.editProject?'':'')+'<button class="iconbtn flat" style="width:26px;height:26px" title="Edit milestone" onclick="editMilestoneModal(\''+p.id+'\','+i+')">'+I.edit+'</button></div>'; }).join(""); }
function editMilestoneModal(pid,i){ var p=project(pid); var m=p.milestones[i]; openModal("Edit milestone",fieldHtml("ms_name","Name",'<input id="ms_name" value="'+attr(m.name)+'">')+fieldHtml("ms_due","Due",'<input id="ms_due" type="date" value="'+iso(m.due)+'">')+'<label style="display:flex;gap:8px;align-items:center;font-size:var(--fs-sm)"><input type="checkbox" id="ms_done" '+(m.done?"checked":"")+'> Completed</label>','<button class="btn danger-soft" onclick="var p=project(\''+pid+'\');p.milestones.splice('+i+',1);updateMilestoneProgress(p);closeModal();renderScreen(false);persistProject(p,false);toast(\'Milestone removed\',\'bad\')">'+I.trash+'Delete</button><span class="spacer"></span><button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="if(require([\'ms_name\'])){var p=project(\''+pid+'\');var m=p.milestones['+i+'];m.name=val(\'ms_name\');m.due=offsetFromIso(val(\'ms_due\'));m.done=document.getElementById(\'ms_done\').checked;updateMilestoneProgress(p);closeModal();renderScreen(false);persistProject(p,false).then(function(saved){ if(saved===false)return false;toast(\'Milestone saved\')})}">Save</button>'); }
function updateMilestoneProgress(p){p.progress=projectProgress(p);}
function toggleMs(pid,i){ var p=project(pid); p.milestones[i].done=!p.milestones[i].done; updateMilestoneProgress(p); renderScreen(false); persistProject(p,false); }
/* §506-524 review status and task navigation are two different jobs. A file
   row keeps its Open task action whatever the version's review state is. */
function fileTaskActions(tk,statusHtml){
  var live=tk&&task(tk.id);
  if(!live) return '<div class="file-actions">'+statusHtml+(tk?'<span class="badge" title="'+attr(tr("This task is no longer available"))+'">'+tr("Task unavailable")+'</span>':'')+'</div>';
  var allowed=typeof canI!=="undefined"&&canI.viewTask?canI.viewTask(live):true;
  return '<div class="file-actions">'+statusHtml
    + (allowed
        ? '<button class="btn xs" title="'+attr(tr("Open")+" "+live.id)+'" onclick="openProjectFileTask(\''+live.id+'\')">'+I.ext+tr("Open task")+'</button>'
        : '<span class="badge" title="'+attr(tr("You do not have access to this task"))+'">'+I.lock+tr("No access")+'</span>')
    + '</div>';
}
/* §513 opening a task from Files keeps the project context behind the panel. */
function openProjectFileTask(id){ openTask(id); setTab("files"); }
function addMilestoneModal(pid){ openModal("Add milestone",fieldHtml("ms_name","Name",'<input id="ms_name" placeholder="e.g. Print-ready files">')+fieldHtml("ms_due","Due",'<input id="ms_due" type="date" value="'+iso(7)+'">'),'<button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="if(require([\'ms_name\'])){var p=project(\''+pid+'\');p.milestones.push({id:uid(\'ms\'),name:val(\'ms_name\'),due:offsetFromIso(val(\'ms_due\')),done:false});updateMilestoneProgress(p);closeModal();toast(\'Milestone added\');renderScreen(false);persistProject(p,false)}">Add</button>'); }
function saveProjectText(id){ var p=project(id); p.description=val("pj_desc"); p.brief=document.getElementById("pj_brief").value.trim(); p.progress=projectProgress(p); logWorkspace("edited","project",id,{what:"project brief",project:id}); persistProject(p,false).then(function(saved){ if(saved===false)return false; S.projectTextEdit=null; renderScreen(false); toast("Project description and objective saved"); }); }
function editProject(id,k,v){ var p=project(id); if (k==="name"&&!v.trim()) return; if (p[k]===v) return; if (k==="status"&&(v==="archived"||p.status==="archived")) return archiveProject(id,v!=="archived"); p[k]=v; if (k==="status"&&v==="done") p.completedAt=new Date().toISOString(); logWorkspace("edited","project",id,{what:"project "+p.name,project:id}); if (k==="status"||k==="progress") renderScreen(false); persistProject(p,false); }
/* title only — so a task never has to wait for a project to be set up properly */
function quickProjectModal(){
  if (!canI.createProject()) return toast("You do not have permission to create projects","bad");
  openModal("New project",
    fieldHtml("qp_name","Project name",'<input id="qp_name" placeholder="e.g. Q4 Retention Campaign" onkeydown="if(event.key===\'Enter\')quickCreateProject()">')
    + '<p class="hint">Just the title for now. Owner, deadline, teams and milestones can be filled in later from the project page.</p>',
    '<button class="btn primary" onclick="quickCreateProject()">'+I.plus+'Create &amp; use</button>');
  setTimeout(function(){ var el=document.getElementById("qp_name"); if (el) el.focus(); },60);
}
function quickCreateProject(){
  if (!require(["qp_name"])) return;
  var p={id:uid("p"),name:val("qp_name"),owner:ME,start:0,due:30,progress:0,status:"active",tags:[],teams:[],team:[ME],description:"",brief:"",milestones:[],sort:PROJECTS.length+1};
  PROJECTS.push(p);
  logWorkspace("project_created","project",p.id,{what:p.name,project:p.id});
  closeModal();
  var tk=S.drawerTask&&task(S.drawerTask);
  if (tk){ if (tk._draft){ tk.proj=p.id; renderDrawer(); } else editTask("proj",p.id); toast('Created "'+p.name+'" and moved this task into it'); }
  else { toast("Project created"); renderScreen(false); }
  persistProject(p,true);
}
function newProjectModal(){ openModal("New project",fieldHtml("np_name","Name",'<input id="np_name" placeholder="e.g. Holiday Campaign 2026">')+'<div class="field-row">'+fieldHtml("np_owner","Owner",selectHtml("np_owner",peopleOpts(),ME))+fieldHtml("np_due","Deadline",'<input id="np_due" type="date" value="'+iso(30)+'">')+'</div>'+fieldHtml("np_desc","Description",'<textarea id="np_desc"></textarea>')+fieldHtml("np_teams","Teams",'<div class="chips">'+activeTeams().map(function(t){ return '<label class="chipx" style="cursor:pointer;--tc:'+teamColorCss(t.color)+'"><input type="checkbox" data-npteam="'+t.id+'"> <span class="tdot"></span> '+esc(t.name)+'</label>'; }).join("")+'</div>')+fieldHtml("np_tags","Tags",tagPicker("np_tags",[],"")),'<button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="createProject()">Create project</button>'); }
function createProject(){ if (!require(["np_name"])) return; var teams=[]; document.querySelectorAll("[data-npteam]").forEach(function(c){ if (c.checked) teams.push(c.getAttribute("data-npteam")); }); var p={id:uid("p"),name:val("np_name"),owner:val("np_owner"),start:0,due:offsetFromIso(val("np_due")),progress:0,status:"active",tags:tagPickerValues("np_tags"),teams:teams,team:[val("np_owner")],description:val("np_desc"),brief:"",milestones:[],sort:PROJECTS.length+1}; PROJECTS.push(p); logWorkspace("project_created","project",p.id,{what:p.name,project:p.id}); closeModal(); toast("Project created"); go("projects",p.id); persistProject(p,true); }
function saveProject(id){ if (!require(["ep_name"])) return; var p=project(id); p.name=val("ep_name"); p.owner=val("ep_owner"); p.status=val("ep_status"); p.due=offsetFromIso(val("ep_due")); p.start=offsetFromIso(val("ep_start")); p.tags=tagPickerValues("ep_tags"); var team=[],teams=[]; document.querySelectorAll("[data-team]").forEach(function(c){ if (c.checked) team.push(c.getAttribute("data-team")); }); document.querySelectorAll("[data-pteam]").forEach(function(c){ if (c.checked) teams.push(c.getAttribute("data-pteam")); }); p.team=team.length?team:[p.owner]; p.teams=teams; toast("Project saved"); renderScreen(false); persistProject(p,false); }
function deleteProject(id){ var n=TASKS.filter(function(t){return t.proj===id;}).length; confirmModal("Delete project?","This deletes the project and its "+n+" tasks.",function(){ deleteProjectById(id); toast("Project deleted","bad"); go("projects"); },true); }
</script>
