<script>
/* Layer composition is shared by preview, PNG download and asset export. */
function aiRefreshProperties(){var old=document.querySelector('.ai-props');if(!old)return;var y=old.scrollTop;old.outerHTML=aiStudioProperties();var el=document.querySelector('.ai-props');el.scrollTop=y;aiBindHistoryInputs();localizeVisibleText(el);}
var aiCanvasEditAtBase=aiCanvasEditAt,aiTextDragEndBase=aiTextDragEnd;
aiCanvasEditAt=function(ev,cv){aiCanvasEditAtBase(ev,cv);aiRefreshProperties();};
aiTextDragEnd=function(ev){aiTextDragEndBase(ev);aiRefreshProperties();};
function aiLayerMeta(id){var all=AIF.layerMeta||(AIF.layerMeta={});return all[id]||(all[id]={visible:true,locked:false,rotation:0,opacity:100});}
function aiLayerIds(){var ids=['badge','headline','sub','cta','logo'].concat((AIF.extraLayers||[]).map(function(x){return 'extra_'+x.id;}),['disclaimer']);var saved=AIF.layerOrder||[];return saved.filter(function(id,i){return ids.indexOf(id)>=0&&saved.indexOf(id)===i;}).concat(ids.filter(function(id){return saved.indexOf(id)<0;}));}
function aiMoveLayer(id,delta){var ids=aiLayerIds(),i=ids.indexOf(id),j=i+delta;if(i<0||j<0||j>=ids.length||aiLayerMeta(id).locked)return;aiHistoryBefore();ids.splice(i,1);ids.splice(j,0,id);AIF.layerOrder=ids;aiRenderKeepScroll();}
function aiMetaSet(id,key,value){aiHistoryBefore();aiLayerMeta(id)[key]=value;aiRenderKeepScroll();}
function aiCompositeLayers(g,planes,sz,generated){
 var hits=AI_LAYER_HITS.map(function(h){var scale=(h.id==='headline'||h.id==='sub')?aiLayerScale(h.id)/100:1;return {id:h.id,x:h.x+h.w*(1-scale)/2,y:h.y+h.h*(1-scale)/2,w:h.w*scale,h:h.h*scale};}),ordered=[];AI_LAYER_BASE_HITS=hits;
 if(generated&&AIF.protectText!==false)aiProtectText(g,hits,sz);
 aiLayerIds().forEach(function(id){var cv=planes[id],m=aiLayerMeta(id),hit=hits.find(function(h){return h.id===id;});if(!cv||m.visible===false)return;var cx=hit?hit.x+hit.w/2:sz.w/2,cy=hit?hit.y+hit.h/2:sz.h/2,r=(Number(m.rotation)||0)*Math.PI/180;
  g.save();g.globalAlpha=Math.max(0,Math.min(100,Number(m.opacity)))/100;g.translate(cx,cy);g.rotate(r);var sc=(id==='headline'||id==='sub')?aiLayerScale(id)/100:1;if(sc!==1)g.scale(sc,sc);if(typeof aiGlowOn==='function')aiGlowOn(g,aiLayerStyle(id));g.drawImage(cv,-cx,-cy);g.restore();
  if(hit){var w=Math.abs(hit.w*Math.cos(r))+Math.abs(hit.h*Math.sin(r)),h=Math.abs(hit.w*Math.sin(r))+Math.abs(hit.h*Math.cos(r));ordered.push({id:id,x:cx-w/2,y:cy-h/2,w:w,h:h});}
  cv.width=1;cv.height=1;
 });AI_LAYER_HITS=ordered;
}
/* Sequential loading keeps visual stacking and pointer hit order identical. */
aiDrawExtras=function(g,sz,done,begin){var xs=(AIF.extraLayers||[]).filter(function(x){return x.visible!==false;}),i=0;
 function next(){if(i>=xs.length)return done();var x=xs[i++],id='extra_'+x.id,c=begin?begin(id):g,px=aiOffset(x.x,sz.w),py=aiOffset(x.y,sz.h),scale=aiLayerScale(id)/100,st=aiLayerStyle(id);
  function paint(im){c.save();aiShadowOn(c,st);var w,h;
   if(x.type==='text'){var fs=Math.max(10,(Number(x.size)||36)*scale),font=(x.italic?'italic ':'')+(x.weight||700)+' '+fs+'px '+aiTextFont(x.font,brandFontStack());c.font=font;var lines=[];String(x.content||'').split('\n').forEach(function(line){lines=lines.concat(line?wrapText(c,line,sz.w*(Number(x.w)||50)/100,fs,font):['']);});h=Math.max(1,lines.length)*fs*(Number(x.lineHeight)||1.3);w=1;lines.forEach(function(line){w=Math.max(w,c.measureText(line).width);});aiPaintBox(c,px-w/2-st.padX,py-h/2-st.padY,w+st.padX*2,h+st.padY*2,st);c.font=font;c.fillStyle=aiLayerTextPaint(c,sz,st,x.color||'#fff',{x:px-w/2,y:py-h/2,w:w,h:h});c.globalAlpha=(Number(st.textOpacity)/100);c.textAlign=x.align||'center';c.textBaseline='top';var tx=x.align==='left'?px-w/2:x.align==='right'?px+w/2:px;lines.forEach(function(line,n){var y=py-h/2+n*fs*(Number(x.lineHeight)||1.3);if(st.textStroke){c.strokeStyle=st.textStrokeColor;c.lineWidth=Number(st.textStrokeWidth)||1;c.strokeText(line,tx,y);}c.fillText(line,tx,y);if(x.underline){c.fillRect(x.align==='left'?tx:x.align==='right'?tx-c.measureText(line).width:tx-c.measureText(line).width/2,y+fs,c.measureText(line).width,Math.max(1,fs/18));}});
   }else{w=sz.w*Math.max(1,Math.min(200,Number(x.w)||22))/100*scale;h=x.type==='image'&&im?w*im.height/im.width:sz.h*Math.max(1,Math.min(200,Number(x.h)||20))/100*scale;c.fillStyle=x.gradient?aiGradient(c,w,h,x.color||'#2F5BFF',x.color2||'#C6F24E',x.angle==null?135:x.angle,100,x.gradientType,px-w/2,py-h/2):x.color||'#2F5BFF';aiShapePath(c,x.shape,px,py,w,h,x.radius);if(im){c.clip();c.filter='brightness('+(x.brightness==null?100:x.brightness)+'%) contrast('+(x.contrast==null?100:x.contrast)+'%) saturate('+(x.saturation==null?100:x.saturation)+'%)';c.drawImage(im,px-w/2,py-h/2,w,h);}else c.fill();if(Number(x.strokeWidth)>0){c.strokeStyle=x.strokeColor||'#fff';c.lineWidth=Number(x.strokeWidth);c.stroke();}}
   c.restore();aiAddHit(id,px-w/2,py-h/2,w,h);next();}
  if(x.type==='image'){if(!x.src)return next();var im=new Image();im.onload=function(){paint(im);};im.onerror=next;im.src=x.src;}else paint(null);
 }next();};
function aiAddShape(shape){if(!aiGuardLayers(1,false))return;aiHistoryBefore();var sz=aiActiveSize(),x={id:uid('layer'),name:tr('Shape'),type:'shape',shape:shape||'rectangle',x:AIF.offsetUnit==='px'?sz.w/2:50,y:AIF.offsetUnit==='px'?sz.h/2:50,w:28,h:24,radius:20,color:(WS.theme||{}).accent||'#2F5BFF',color2:'#C6F24E'};AIF.extraLayers=AIF.extraLayers||[];AIF.extraLayers.push(x);AIF.selectedLayer='extra_'+x.id;aiRenderKeepScroll();}
function aiDuplicateLayer(id){var old=aiExtra(id.slice(6));if(!old)return;if(!aiGuardLayers(1,old.type==='image'))return;aiHistoryBefore();var x=clone(old),nid=uid('layer');x.id=nid;x.name=(x.name||tr('Layer'))+' '+tr('copy');x.x=Number(x.x)+(AIF.offsetUnit==='px'?24:2);x.y=Number(x.y)+(AIF.offsetUnit==='px'?24:2);AIF.extraLayers.push(x);AIF.layerStyles['extra_'+nid]=clone(aiLayerStyle(id));AIF.layerMeta['extra_'+nid]=Object.assign({},aiLayerMeta(id),{locked:false});AIF.selectedLayer='extra_'+nid;aiRenderKeepScroll();}
function aiAlignLayer(id,axis){if(aiLayerMeta(id).locked)return;var hit=AI_LAYER_HITS.find(function(h){return h.id===id;});if(!hit)return;var sz=aiActiveSize(),p=id.indexOf('extra_')===0?aiExtra(id.slice(6)):aiLayerPosition(id);aiHistoryBefore();var dx=axis==='left'?-hit.x:axis==='right'?sz.w-hit.x-hit.w:axis==='center'?(sz.w-hit.w)/2-hit.x:0,dy=axis==='top'?-hit.y:axis==='bottom'?sz.h-hit.y-hit.h:axis==='middle'?(sz.h-hit.h)/2-hit.y:0;p.x=Number(p.x)+(AIF.offsetUnit==='px'?dx:dx/sz.w*100);p.y=Number(p.y)+(AIF.offsetUnit==='px'?dy:dy/sz.h*100);aiRenderKeepScroll();}
function aiExtraSet(id,key,value){var x=aiExtra(id);if(!x||aiLayerMeta('extra_'+id).locked)return;x[key]=value;aiPreviewSoon();}
function aiExtraEditor(x){if(x.type==='text'){if(x.weight==null)x.weight=700;if(x.lineHeight==null)x.lineHeight=1.3;if(x.align==null)x.align='center';if(x.w==null)x.w=50;}if(x.type==='image'){['brightness','contrast','saturation'].forEach(function(k){if(x[k]==null)x[k]=100;});}var id=x.id,html='',field=function(key,label,type,min,max){return '<div class="field"><label>'+esc(tr(label))+'</label><input aria-label="'+attr(tr(label))+'" type="'+type+'" '+(min!=null?'min="'+min+'" max="'+max+'"':'')+' value="'+attr(x[key]==null?'':x[key])+'" oninput="aiExtraSet(\''+id+'\',\''+key+'\','+(type==='number'?'Number(this.value)':'this.value')+')"></div>';},select=function(key,label,opts){return '<div class="field"><label>'+esc(tr(label))+'</label><select aria-label="'+attr(tr(label))+'" onchange="aiExtraSet(\''+id+'\',\''+key+'\',this.value)">'+opts.map(function(o){return '<option value="'+attr(o[0])+'"'+(String(x[key])===String(o[0])?' selected':'')+'>'+esc(tr(o[1]))+'</option>';}).join('')+'</select></div>';};
 html+=field('name','Layer name','text');
 if(x.type==='text'){html+='<div class="field"><label>'+esc(tr('Content'))+'</label><textarea aria-label="'+attr(tr('Content'))+'" rows="3" oninput="aiExtraSet(\''+id+'\',\'content\',this.value)">'+esc(x.content||'')+'</textarea></div>';html+=select('font','Font',[['','Workspace headline font']].concat(aiWorkspaceFonts().map(function(f){return [f,f];})))+'<div class="field-row">'+field('size','Font size','number',10,600)+select('weight','Font weight',[[400,'Regular'],[500,'Medium'],[700,'Bold'],[900,'Black']])+'</div><div class="field-row">'+select('align','Alignment',[['center','Center'],['left','Left'],['right','Right']])+field('lineHeight','Line spacing','number',0.7,3)+'</div><div class="ai-layer-tools">'+['italic','underline'].map(function(k){return '<button class="btn xs" aria-pressed="'+!!x[k]+'" onclick="aiHistoryBefore();aiExtraSet(\''+id+'\',\''+k+'\','+!x[k]+');aiRenderKeepScroll()">'+esc(tr(k==='italic'?'Italic':'Underline'))+'</button>';}).join('')+'</div>'+field('w','Text box width (%)','number',1,100)+aiTextStyleEditor('extra_'+id);}
 else if(x.type==='shape'){html+=select('shape','Shape',[['rectangle','Rectangle'],['rounded','Rounded rectangle'],['pill','Pill'],['ellipse','Ellipse'],['triangle','Triangle'],['diamond','Diamond'],['pentagon','Pentagon'],['hexagon','Hexagon'],['star','Star'],['arrow','Arrow'],['chevron','Chevron'],['parallelogram','Parallelogram']])+'<div class="field-row">'+field('color','Fill color','color')+field('color2','Secondary color','color')+'</div><button class="btn xs" aria-pressed="'+!!x.gradient+'" onclick="aiHistoryBefore();aiExtraSet(\''+id+'\',\'gradient\','+!x.gradient+');aiRenderKeepScroll()">'+esc(tr('Gradient'))+'</button><div class="field-row">'+field('w','Width (%)','number',1,200)+field('h','Height (%)','number',1,200)+'</div>'+field('radius','Corner radius','number',0,999)+'<div class="field-row">'+field('strokeWidth','Outline width','number',0,50)+field('strokeColor','Outline color','color')+'</div>';}
 else{html+=field('w','Width (%)','number',1,200)+field('radius','Corner radius','number',0,999)+'<div class="field-row">'+field('brightness','Brightness (%)','number',0,200)+field('contrast','Contrast (%)','number',0,200)+'</div>'+field('saturation','Saturation (%)','number',0,200);}
 return html+'<div class="field-row">'+field('x',AIF.offsetUnit==='px'?'X (px)':'X (%)','number',-10000,10000)+field('y',AIF.offsetUnit==='px'?'Y (px)':'Y (%)','number',-10000,10000)+'</div>'+(x.type==='text'?'':aiShadowEditor('extra_'+id))+'<div class="ai-layer-tools"><button class="btn xs" onclick="aiDuplicateLayer(\'extra_'+id+'\')">'+esc(tr('Duplicate layer'))+'</button><button class="btn xs danger-soft" onclick="aiDeleteLayer(\'extra_'+id+'\')">'+esc(tr('Delete layer'))+'</button></div>';
}
var aiStudioPropertiesBase=aiStudioProperties;
aiStudioProperties=function(){var html=aiStudioPropertiesBase(),id=AIF.selectedLayer||'canvas',m=aiLayerMeta(id),names={badge:'Badge',headline:'Headline',sub:'Subheadline',cta:'Button',logo:'Logo',disclaimer:'Disclaimer'},rows=aiStudioLayerButton('canvas',tr('Canvas'),I.grid)+aiLayerIds().slice().reverse().map(function(key){var x=key.indexOf('extra_')===0?aiExtra(key.slice(6)):null,meta=aiLayerMeta(key);return '<div class="ai-layer-row">'+aiStudioLayerButton(key,esc(meta.name||(x?x.name:tr(names[key]))),x&&x.type==='shape'?I.grid:I.edit)+'<button class="iconbtn" title="'+attr(tr(meta.visible===false?'Show layer':'Hide layer'))+'" aria-label="'+attr(tr(meta.visible===false?'Show layer':'Hide layer'))+'" aria-pressed="'+(meta.visible!==false)+'" onclick="aiMetaSet(\''+key+'\',\'visible\','+(meta.visible===false)+')">'+(meta.visible===false?aiCanvasIcon('eyeOff'):I.eye)+'</button><button class="iconbtn" title="'+attr(tr(meta.locked?'Unlock layer':'Lock layer'))+'" aria-label="'+attr(tr(meta.locked?'Unlock layer':'Lock layer'))+'" aria-pressed="'+!!meta.locked+'" onclick="aiMetaSet(\''+key+'\',\'locked\','+!meta.locked+')">'+(meta.locked?I.lock:aiInspectorIcon('unlock'))+'</button></div>';}).join('');
 html=html.replace(/<div class="ai-layer-list">[\s\S]*?<\/div><div class="ai-layer-add">/,'<div class="ai-layer-list">'+rows+'</div><div class="ai-layer-add">').replace('onclick="aiAddTextLayer()"','onclick="aiAddTextLayer()"');html=html.replace('PNG / image</button></div>','PNG / image</button><button class="btn xs" onclick="aiAddShape()">'+I.plus+esc(tr('Shape'))+'</button></div>');
 var controls='';if(id!=='canvas'){controls='<div class="ai-layer-tools"><button class="btn xs" onclick="aiMoveLayer(\''+id+'\',1)">'+esc(tr('Bring forward'))+'</button><button class="btn xs" onclick="aiMoveLayer(\''+id+'\',-1)">'+esc(tr('Send backward'))+'</button></div><fieldset class="ai-edit-fields" '+(m.locked?'disabled':'')+'><div class="field-row"><div class="field"><label>'+esc(tr('Rotation (°)'))+'</label><input aria-label="'+attr(tr('Rotation (°)'))+'" type="number" min="-360" max="360" value="'+(m.rotation||0)+'" oninput="aiLayerMeta(\''+id+'\').rotation=Number(this.value);aiPreviewSoon()"></div><div class="field"><label>'+esc(tr('Opacity (%)'))+'</label><input aria-label="'+attr(tr('Opacity (%)'))+'" type="number" min="0" max="100" value="'+m.opacity+'" oninput="aiLayerMeta(\''+id+'\').opacity=Number(this.value);aiPreviewSoon()"></div></div><div class="ai-layer-tools">'+['left','center','right','top','middle','bottom'].map(function(a){var label={left:'Left',center:'Center',right:'Right',top:'Top',middle:'Middle',bottom:'Bottom'}[a];return '<button class="btn xs" onclick="aiAlignLayer(\''+id+'\',\''+a+'\')">'+esc(tr(label))+'</button>';}).join('')+'</div>';}
 if(id.indexOf('extra_')===0){var x=aiExtra(id.slice(6));if(x)html=html.replace(/<div class="ai-prop-body">[\s\S]*<\/div><\/div><\/section>$/, '<div class="ai-prop-body">'+aiExtraEditor(x)+'</div></div></section>');}
 if(id!=='canvas')html=html.replace('<div class="ai-prop-body">','<div class="ai-prop-body">'+controls).replace('</div></div></section>','</fieldset></div></div></section>');
 else html=html.replace('<div class="ai-prop-body">','<div class="ai-prop-body"><button class="btn xs" onclick="aiHistoryBefore();AIF.hideGenerated=!AIF.hideGenerated;aiRenderKeepScroll()">'+esc(tr(AIF.hideGenerated?'Show generated background':'Hide generated background'))+'</button>');
 return html;};
Object.assign(UI_ID,{'Brand default prompt':'Prompt brand bawaan','Describe your brand voice, visual direction, required colors, and things to avoid.':'Jelaskan gaya bahasa, arahan visual, warna wajib, serta hal yang harus dihindari.','Included with every AI Hub generation, including custom prompts and templates. Only workspace administrators can change it. Review generated visuals before publishing.':'Disertakan pada setiap pembuatan gambar di AI Hub, termasuk prompt khusus dan templat. Hanya admin workspace yang dapat mengubahnya. Tinjau hasil gambar sebelum dipublikasikan.','Layer name':'Nama layer','Shape':'Bentuk','Rectangle':'Persegi panjang','Ellipse':'Elips','Triangle':'Segitiga','Bring forward':'Majukan layer','Send backward':'Mundurkan layer','Lock layer':'Kunci layer','Unlock layer':'Buka kunci layer','Duplicate layer':'Duplikat layer','Rotation (°)':'Rotasi (°)','Font size':'Ukuran font','Font weight':'Ketebalan font','Regular':'Normal','Bold':'Tebal','Italic':'Miring','Underline':'Garis bawah','Line spacing':'Jarak baris','Text box width (%)':'Lebar kotak teks (%)','Fill color':'Warna isi','Brightness (%)':'Kecerahan (%)','Contrast (%)':'Kontras (%)','Saturation (%)':'Saturasi (%)','Middle':'Tengah vertikal','Hide generated background':'Sembunyikan latar AI','Show generated background':'Tampilkan latar AI','copy':'salinan'});

function aiProtectText(g,hits,sz){
 var pad=Math.max(0,Math.min(200,Number(AIF.textProtectionPadding==null?24:AIF.textProtectionPadding))),bg=AIF.canvasBg||{};
 g.save();g.globalAlpha=1;g.fillStyle=bg.color||AIF.background||(WS.brand||{}).primary||'#0B2A5B';
 hits.forEach(function(h){var m=aiLayerMeta(h.id),x=h.id.indexOf('extra_')===0?aiExtra(h.id.slice(6)):null;
 if(m.visible===false||Number(m.opacity)===0||h.id==='logo'||(x&&x.type!=='text'))return;var text=x?x.content:AIF[h.id==='disclaimer'?'disclaimerText':h.id];if(!String(text||'').trim())return;
 var r=(Number(m.rotation)||0)*Math.PI/180,cx=h.x+h.w/2,cy=h.y+h.h/2;
 g.save();g.translate(cx,cy);g.rotate(r);g.fillRect(-h.w/2-pad,-h.h/2-pad,h.w+pad*2,h.h+pad*2);g.restore();
 });g.restore();
}
function aiReorderLayer(id,target,before){
 if(id===target||aiLayerMeta(id).locked)return;
 var ids=aiLayerIds().reverse(),i=ids.indexOf(id);if(i<0||ids.indexOf(target)<0)return;
 ids.splice(i,1);var j=ids.indexOf(target);ids.splice(j+(before?0:1),0,id);
 aiHistoryBefore();AIF.layerOrder=ids.reverse();aiRenderKeepScroll();
}
function aiLayerSortStart(ev,id){
 if(ev.button!==0||aiLayerMeta(id).locked)return;ev.preventDefault();
 var target=null,before=true,list=ev.currentTarget.closest('.ai-layer-list');
 function clear(){list.querySelectorAll('.ai-drop-before,.ai-drop-after').forEach(function(n){n.classList.remove('ai-drop-before','ai-drop-after');});}
 function move(e){e.preventDefault();clear();var box=list.getBoundingClientRect();if(e.clientY<box.top+28)list.scrollTop-=16;if(e.clientY>box.bottom-28)list.scrollTop+=16;var row=document.elementFromPoint(e.clientX,e.clientY);row=row&&row.closest('[data-layer-id]');target=row&&list.contains(row)?row.dataset.layerId:null;if(target&&target!==id){before=e.clientY<row.getBoundingClientRect().top+row.offsetHeight/2;row.classList.add(before?'ai-drop-before':'ai-drop-after');}}
 function end(e){clear();window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',end);window.removeEventListener('pointercancel',cancel);if(target)aiReorderLayer(id,target,before);}
 function cancel(){target=null;end();}
 window.addEventListener('pointermove',move,{passive:false});window.addEventListener('pointerup',end);window.addEventListener('pointercancel',cancel);
}
function aiRemoveLayer(id){if(!aiLayerMeta(id).locked)aiDeleteLayer(id);}
var AI_INSPECTOR_UI={layers:true,sections:{}};
function aiInspectorIcon(name){var paths={unlock:'<rect x="4" y="10" width="16" height="11" rx="3"/><path d="M8 10V6a4 4 0 0 1 8 0M12 14v3"/>',up:'<path d="m6 10 6-6 6 6M12 4v16"/>',down:'<path d="m6 14 6 6 6-6M12 4v16"/>',layers:'<path d="m12 3 9 5-9 5-9-5 9-5Zm-9 9 9 5 9-5M3 16l9 5 9-5"/>'};return '<svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+(paths[name]||paths.layers)+'</svg>';}
var aiInspectorBase=aiStudioProperties;
aiStudioProperties=function(){
 var tpl=document.createElement('template');tpl.innerHTML=aiInspectorBase();var root=tpl.content.querySelector('.ai-props');if(!root)return tpl.innerHTML;
 root.classList.add('ai-inspector');var id=AIF.selectedLayer||'canvas',locked=aiLayerMeta(id).locked;
 root.querySelectorAll('.ai-layer-row').forEach(function(row){var select=row.querySelector('.ai-layer'),match=select&&select.getAttribute('onclick').match(/(?:selectedLayer=|aiSelectLayer\()'([^']+)'/);if(!match){var keys=aiLayerIds().slice().reverse();match=[null,keys[Array.from(row.parentNode.children).filter(function(n){return n.classList.contains('ai-layer-row');}).indexOf(row)]];}var key=match[1];row.dataset.layerId=key;
 var grip=document.createElement('button');grip.className='iconbtn ai-layer-grip';grip.setAttribute('aria-label',tr('Drag to reorder'));grip.title=tr('Drag to reorder');grip.textContent='⠿';grip.setAttribute('onpointerdown',"aiLayerSortStart(event,'"+key+"')");grip.setAttribute('onkeydown',"if(event.key==='ArrowUp'||event.key==='ArrowDown'){event.preventDefault();aiMoveLayer('"+key+"',event.key==='ArrowUp'?1:-1)}");grip.disabled=!!aiLayerMeta(key).locked;row.prepend(grip);
 var trash=document.createElement('button');trash.className='iconbtn danger-soft';trash.title=tr('Delete layer');trash.setAttribute('aria-label',tr('Delete layer'));trash.innerHTML=I.trash;trash.disabled=!!aiLayerMeta(key).locked;trash.setAttribute('onclick',"aiRemoveLayer('"+key+"')");row.append(trash);
 });
 var body=root.querySelector('.ai-prop-body');if(id!=='canvas'){
 var fields=body.querySelector('fieldset'),source=fields||body,groups={Position:[],Layout:[],Content:[],Appearance:[],Effects:[]};
 Array.from(source.children).forEach(function(n){var t=n.textContent.trim();Object.keys(UI_ID).sort(function(a,b){return UI_ID[b].length-UI_ID[a].length;}).forEach(function(en){if(typeof UI_ID[en]==='string'&&UI_ID[en])t=t.split(UI_ID[en]).join(en);});if(n.matches('.ai-layer-tools')&&/Delete layer|Hapus layer/.test(t)){n.querySelectorAll('button').forEach(function(b){if((b.getAttribute('onclick')||'').indexOf('aiDeleteLayer')>=0)b.remove();});if(!n.children.length)return;}if(n.matches('button')&&/Delete layer|Hide layer/.test(t))return;
 var category=/Position|X offset|Y offset|X \(|Y \(|Rotation|Opacity \(%\)/.test(t)&&!n.matches('.ai-prop-group')?'Position':/Drop shadow/.test(t)&&!(/Text appearance/.test(t))?'Effects':n.matches('.ai-prop-group')||/Fill color|Corner radius|Outline|Brightness|Saturation|Contrast|Gradient/.test(t)?'Appearance':'Content';if(/Width \(%\)|Height \(%\)|Text box width/.test(t))category='Layout';if(n.matches('.ai-layer-tools')&&/Left/.test(t)){category='Position';n.classList.add('ai-align-icons');var icons=['⊢','↔','⊣','⤒','↕','⤓'];n.querySelectorAll('button').forEach(function(b,i){b.title=tr(b.textContent);b.setAttribute('aria-label',tr(b.textContent));b.innerHTML=aiCanvasIcon(['alignLeft','alignCenter','alignRight','alignTop','alignMiddle','alignBottom'][i]);});}groups[category].push(n.outerHTML);
 });
 var order=body.querySelector(':scope > .ai-layer-tools');body.innerHTML=(order?order.outerHTML:'')+'<button class="btn xs danger-soft ai-delete-selected" '+(locked?'disabled':'')+' onclick="aiRemoveLayer(\''+id+'\')">'+I.trash+esc(tr('Delete layer'))+'</button><fieldset class="ai-edit-fields" '+(locked?'disabled':'')+'>'+Object.keys(groups).map(function(k){return groups[k].length?'<details class="ai-inspector-section" open><summary>'+esc(tr(k))+'</summary><div class="ai-section-fields">'+groups[k].join('')+'</div></details>':'';}).join('')+'</fieldset>';
 }else body.insertAdjacentHTML('afterbegin','<details class="ai-inspector-section" open><summary>'+esc(tr('Text protection'))+'</summary><div class="ai-section-fields"><label class="ai-protect-toggle"><input type="checkbox" '+(AIF.protectText!==false?'checked':'')+' onchange="aiHistoryBefore();AIF.protectText=this.checked;aiPreviewSoon()">'+esc(tr('Keep AI image outside text areas'))+'</label><p>'+esc(tr('Text areas use the canvas color, including in exports.'))+'</p><div class="field"><label>'+esc(tr('Padding (px)'))+'</label><input aria-label="'+attr(tr('Padding (px)'))+'" type="number" min="0" max="200" value="'+(AIF.textProtectionPadding==null?24:AIF.textProtectionPadding)+'" oninput="AIF.textProtectionPadding=Number(this.value);aiPreviewSoon()"></div></div></details>');
 root.querySelectorAll('.pref .pl span').forEach(function(n){if(/Optional border|Applies to this layer only|Independent from the canvas/.test(n.textContent))n.remove();});aiPolishInspector(root,id);return root.outerHTML;
};
Object.assign(UI_ID,{'Drag to reorder':'Geser untuk mengurutkan','Text protection':'Perlindungan teks','Keep AI image outside text areas':'Jauhkan gambar AI dari area teks','Text areas use the canvas color, including in exports.':'Area teks memakai warna kanvas, termasuk pada hasil ekspor.','Padding (px)':'Jarak tepi (px)','Appearance':'Tampilan','Effects':'Efek','Content':'Konten'});


function aiPolishInspector(root,id){
 var panel=root.querySelector('#aiProperties'),list=panel.querySelector('.ai-layer-list'),add=panel.querySelector('.ai-layer-add'),title=panel.querySelector('.ai-prop-title'),body=panel.querySelector('.ai-prop-body');
 var label=panel.querySelector(':scope > .eyebrow');if(label)label.remove();
 var layers=document.createElement('details');layers.className='ai-layer-browser';layers.open=AI_INSPECTOR_UI.layers;layers.setAttribute('ontoggle','AI_INSPECTOR_UI.layers=this.open');
 layers.innerHTML='<summary>'+aiInspectorIcon('layers')+'<span>'+esc(tr('Layers'))+'</span><span class="ai-layer-count">'+aiLayerIds().length+'</span></summary>';
 panel.insertBefore(layers,list);layers.append(list);if(add){layers.append(add);add.querySelectorAll('button').forEach(function(b){if(b.textContent.trim()==='PNG / image')b.innerHTML=I.image+esc(tr('Image'));});}
 var reset=panel.querySelector('[onclick="aiResetAllPositions()"]');if(reset){reset.className='btn xs ghost ai-reset-positions';layers.append(reset);}
 list.querySelectorAll('.ai-layer-row').forEach(function(row){var selected=row.dataset.layerId===id;row.classList.toggle('is-selected',selected);row.classList.toggle('is-locked',!!aiLayerMeta(row.dataset.layerId).locked);var pick=row.querySelector('.ai-layer');pick.setAttribute('aria-pressed',String(selected));pick.title=pick.textContent.trim();});
 title.classList.add('ai-selection-heading');var name=document.createElement('span');name.textContent=title.textContent;title.textContent='';title.append(name);
 var del=body.querySelector('.ai-delete-selected');if(del){del.className='iconbtn ai-delete-selected';del.setAttribute('aria-label',tr('Delete layer'));del.title=tr('Delete layer');del.innerHTML=I.trash;title.append(del);}
 var toolbar=body.querySelector(':scope > .ai-layer-tools');if(toolbar){toolbar.classList.add('ai-stack-toolbar');toolbar.querySelectorAll('button').forEach(function(b,i){b.innerHTML=aiInspectorIcon(i?'down':'up')+esc(tr(i?'Move down':'Move up'));b.disabled=!!aiLayerMeta(id).locked;});}
 if(id!=='canvas'&&aiLayerMeta(id).locked){var unlock=document.createElement('button');unlock.className='btn xs ai-unlock-notice';unlock.innerHTML=aiInspectorIcon('unlock')+esc(tr('Unlock to edit'));unlock.setAttribute('onclick',"aiMetaSet('"+id+"','locked',false)");body.prepend(unlock);}
 body.querySelectorAll('.ai-inspector-section').forEach(function(section,i){var summary=section.querySelector('summary'),key=summary.textContent.trim();section.dataset.section=key;section.open=AI_INSPECTOR_UI.sections[key]===undefined?key!==tr('Effects'):AI_INSPECTOR_UI.sections[key];section.setAttribute('ontoggle',"AI_INSPECTOR_UI.sections['"+key.replace(/'/g,'')+"']=this.open");});
 root.querySelector('.panel-head .sq').innerHTML=aiInspectorIcon('layers');
}
Object.assign(UI_ID,{'Move up':'Naikkan','Move down':'Turunkan','Unlock to edit':'Buka kunci untuk mengedit','Image':'Gambar'});

</script>
