<script>
/* Shared paints keep previews, gallery thumbnails and downloads consistent. */
function aiGradient(g,w,h,a,b,angle,stop,type,ox,oy){ox=Number(ox)||0;oy=Number(oy)||0;var rad=((Number(angle)||0)-90)*Math.PI/180,reach=Math.sqrt(w*w+h*h)/2,x=Math.cos(rad)*reach,y=Math.sin(rad)*reach,gr=type==='radial'?g.createRadialGradient(ox+w/2,oy+h/2,0,ox+w/2,oy+h/2,Math.max(1,Math.min(w,h)/2)):g.createLinearGradient(ox+w/2-x,oy+h/2-y,ox+w/2+x,oy+h/2+y),at=Math.max(.01,Math.min(1,(Number(stop)||100)/100));gr.addColorStop(0,a||'#2F5BFF');gr.addColorStop(at,b||'#7C3AED');if(at<1)gr.addColorStop(1,b||'#7C3AED');return gr;}
function aiGlowOn(g,s){if(!s||!s.glow)return;g.shadowColor=aiShadowRgba(s.glowColor||'#7C83FF',s.glowOpacity==null?65:Math.max(0,Math.min(100,Number(s.glowOpacity)||0)));g.shadowBlur=Math.max(0,Math.min(200,s.glowBlur==null?24:Number(s.glowBlur)||0));g.shadowOffsetX=0;g.shadowOffsetY=0;}
function aiShapePath(g,shape,px,py,w,h,radius){var vertices=null;g.beginPath();if(shape==='ellipse'){g.ellipse(px,py,w/2,h/2,0,0,Math.PI*2);return;}if(shape==='triangle')vertices=[[0,-1],[1,1],[-1,1]];else if(shape==='diamond')vertices=[[0,-1],[1,0],[0,1],[-1,0]];else if(shape==='arrow')vertices=[[-1,-.42],[.15,-.42],[.15,-1],[1,0],[.15,1],[.15,.42],[-1,.42]];else if(shape==='chevron')vertices=[[-1,-1],[.25,-1],[1,0],[.25,1],[-1,1],[-.25,0]];else if(shape==='parallelogram')vertices=[[-.5,-1],[1,-1],[.5,1],[-1,1]];else if(['pentagon','hexagon','star'].includes(shape)){var n=shape==='star'?10:shape==='pentagon'?5:6;vertices=[];for(var i=0;i<n;i++){var a=-Math.PI/2+i*Math.PI*2/n,r=shape==='star'&&i%2?.45:1;vertices.push([Math.cos(a)*r,Math.sin(a)*r]);}}if(vertices){vertices.forEach(function(p,i){g[i?'lineTo':'moveTo'](px+p[0]*w/2,py+p[1]*h/2);});g.closePath();return;}roundRect(g,px-w/2,py-h/2,w,h,shape==='pill'?Math.min(w,h)/2:Math.min(w/2,h/2,Number(radius)||(shape==='rounded'?20:0)));}
function aiEffectTarget(id,scope){if(scope==='canvas')return AIF.canvasBg||(AIF.canvasBg={type:'solid'});if(scope==='shape')return aiExtra(id.slice(6));return aiLayerStyle(id);}
function aiEffectSet(id,scope,key,value,rebuild){if(id!=='canvas'&&aiLayerMeta(id).locked)return;var target=aiEffectTarget(id,scope);if(!target)return;aiHistoryBefore();target[key]=value;if(rebuild)aiRenderKeepScroll();else aiPreviewSoon();}
function aiEffectNumber(id,scope,key,label,value,max){return '<div class="field"><label>'+tr(label)+'</label><input aria-label="'+attr(tr(label))+'" type="number" min="0" max="'+max+'" value="'+value+'" onchange="aiEffectSet(\''+id+'\',\''+scope+'\',\''+key+'\',Math.max(0,Math.min('+max+',Number(this.value)||0)),false)"></div>';}
function aiGradientModeControl(id,scope,key,current,label){return '<div class="field"><label>'+tr(label)+'</label><select aria-label="'+attr(tr(label))+'" onchange="aiEffectSet(\''+id+'\',\''+scope+'\',\''+key+'\',this.value,true)"><option value="linear" '+(current!=='radial'?'selected':'')+'>'+tr('Linear gradient')+'</option><option value="radial" '+(current==='radial'?'selected':'')+'>'+tr('Radial gradient')+'</option></select></div>';}
var aiStyleInspector=aiPolishInspector;
aiPolishInspector=function(root,id){aiStyleInspector(root,id);if(aiSelectedIds().length>1)return;var body=root.querySelector('.ai-prop-body');if(!body)return;var target=id==='canvas'?null:aiLayerStyle(id),x=id.startsWith('extra_')?aiExtra(id.slice(6)):null,gradient='';
 if(x&&x.type==='shape'&&x.gradient)gradient+=aiGradientModeControl(id,'shape','gradientType',x.gradientType,'Gradient type')+(x.gradientType!=='radial'?aiEffectNumber(id,'shape','angle','Gradient angle (°)',x.angle==null?135:Number(x.angle)||0,360):'');
 if(target){if(target.textFillGradient)gradient+=aiGradientModeControl(id,'style','textGradientType',target.textGradientType,'Text gradient type');if(target.bg&&target.gradient)gradient+=aiGradientModeControl(id,'style','gradientType',target.gradientType,'Background gradient type');}
 if(gradient){var app=Array.from(body.querySelectorAll('.ai-inspector-section')).find(function(s){return s.dataset.section===tr('Appearance');}),group=document.createElement('div');group.className='ai-effect-controls';group.innerHTML=gradient;(app&&app.querySelector('.ai-section-fields')||app||body).append(group);}
 if(target){var effects=Array.from(body.querySelectorAll('.ai-inspector-section')).find(function(s){return s.dataset.section===tr('Effects');});if(!effects){effects=document.createElement('details');effects.className='ai-inspector-section';effects.innerHTML='<summary>'+tr('Effects')+'</summary>';body.append(effects);}var glow=document.createElement('div');glow.className='ai-effect-controls';glow.innerHTML='<label class="ai-glow-toggle"><input type="checkbox" '+(target.glow?'checked':'')+' onchange="aiEffectSet(\''+id+'\',\'style\',\'glow\',this.checked,true)">'+tr('Outer glow')+'</label>'+(target.glow?'<div class="field"><label>'+tr('Glow color')+'</label><input aria-label="'+attr(tr('Glow color'))+'" type="color" value="'+attr(target.glowColor||'#7C83FF')+'" onchange="aiEffectSet(\''+id+'\',\'style\',\'glowColor\',this.value,false)"></div><div class="field-row">'+aiEffectNumber(id,'style','glowOpacity','Glow opacity (%)',target.glowOpacity==null?65:target.glowOpacity,100)+aiEffectNumber(id,'style','glowBlur','Glow size (px)',target.glowBlur==null?24:target.glowBlur,200)+'</div>':'');(effects.querySelector('.ai-section-fields')||effects).append(glow);}
 if(x&&x.type==='shape'&&!['rectangle','rounded'].includes(x.shape))body.querySelectorAll('input[oninput]').forEach(function(n){if(n.getAttribute('oninput').includes("'radius'")){var f=n.closest('.field');if(f)f.remove();}});
 var angleKeys=[];if(id==='canvas'&&(AIF.canvasBg||{}).type==='radial')angleKeys.push('AIF.canvasBg.angle=');if(target&&target.textGradientType==='radial')angleKeys.push('.textFillAngle=');if(target&&target.gradientType==='radial')angleKeys.push('.gradientAngle=');body.querySelectorAll('input[oninput]').forEach(function(n){if(angleKeys.some(function(k){return n.getAttribute('oninput').includes(k);})){var field=n.closest('.field');if(field)field.remove();}});
 if(id!=='canvas'&&aiLayerMeta(id).locked)body.querySelectorAll('.ai-effect-controls input,.ai-effect-controls select').forEach(function(n){n.disabled=true;});
};
Object.assign(UI_ID,{'Outer glow':'Cahaya luar','Glow color':'Warna cahaya','Glow opacity (%)':'Opasitas cahaya (%)','Glow size (px)':'Ukuran cahaya (px)','Radial gradient':'Gradasi melingkar','Gradient type':'Jenis gradasi','Text gradient type':'Jenis gradasi teks','Background gradient type':'Jenis gradasi latar','Gradient angle (°)':'Sudut gradasi (°)','Diamond':'Belah ketupat','Pentagon':'Segi lima','Hexagon':'Segi enam','Star':'Bintang','Arrow':'Panah','Chevron':'Chevron','Parallelogram':'Jajar genjang'});
</script>
