<script>
/* ============================================================
   TASKS — one dataset, five views (Kanban · List · Grid · Calendar · Timeline), filters, sort, group, saved views, universal drag-and-drop (§23–41)
   ============================================================ */
var DUE_PRESETS=[["","Any due date"],["today","Today"],["tomorrow","Tomorrow"],["week","This week"],["nextweek","Next week"],["overdue","Overdue"],["custom","Custom range…"]];
function weekRange(offsetWeeks){ var dow=(TODAY.getDay()+6)%7; var s=-dow+7*offsetWeeks; return [s,s+6]; }
function dueMatch(t,preset,f){ if (!preset) return true; if (preset==="today") return t.due===0; if (preset==="tomorrow") return t.due===1; if (preset==="overdue") return t.due<0&&!isClosed(t); if (preset==="week"){ var w=weekRange(0); return t.due>=w[0]&&t.due<=w[1]; } if (preset==="nextweek"){ var n=weekRange(1); return t.due>=n[0]&&t.due<=n[1]; } if (preset==="custom"){ var a=f.dueFrom?offsetFromIso(f.dueFrom):-9999, b=f.dueTo?offsetFromIso(f.dueTo):9999; return t.due>=a&&t.due<=b; } return true; }
function filteredTasks(){ var f=S.filters; return TASKS.filter(function(x){ if (!f.archived&&projArchived(x.proj)&&!(S.screen==="projects"&&S.projectId===x.proj)) return false; if (f.hidden==="only"&&!(x.hidden||autoHidden(x))) return false; if (!f.hidden&&(x.hidden||autoHidden(x))) return false;
    if (f.label&&(x.labels||[]).indexOf(f.label)<0) return false; if (S.taskScope==="mine"&&!isAssignee(x,ME)&&!isReviewer(x,ME)) return false; if (S.projectId&&S.screen==="projects"&&x.proj!==S.projectId) return false; if (f.status&&x.status!==f.status) return false; if (f.kind&&stageKind(x.status)!==f.kind) return false; if (f.assignee&&!isAssignee(x,f.assignee)) return false; if (f.reviewer&&!isReviewer(x,f.reviewer)) return false; if (f.proj&&x.proj!==f.proj) return false; if (f.prio&&x.prio!==f.prio) return false; if (f.team&&(x.team||"")!==f.team) return false; if (f.tag&&x.tags.indexOf(f.tag)<0) return false; if (f.dependency==="blocked"&&!isTaskBlocked(x)) return false; if (f.dependency==="ready"&&dependencyState(x)!=="ready") return false; if (f.dependency==="blocking"&&!blockingTasksOf(x).length) return false; if (f.dependency==="has"&&!(x.dependencies||[]).length) return false; if (f.dependency==="none"&&(x.dependencies||[]).length) return false; if (!dueMatch(x,f.due,f)) return false; return true; }); }
function anyFilter(){ var f=S.filters; return Object.keys(f).some(function(k){ return f[k]; }); }
function useManualTaskFilters(){ if(!S._temporaryTaskFilter)return; S._temporaryTaskFilter=false; S._manualTaskFilters=null; S._manualTaskScope=null; S._manualActiveView=null; }
function clearFilters(){ useManualTaskFilters(); S.filters=emptyTaskFilters(); S.activeView=null; renderScreen(false); }
function setFilter(k,v){ useManualTaskFilters(); S.filters[k]=v; S.activeView=null; if (k==="due"&&v==="custom") return customRangeModal(); renderScreen(false); }
function customRangeModal(){ openModal("Custom due range",'<div class="field-row">'+fieldHtml("cr_from","From",'<input id="cr_from" type="date" value="'+(S.filters.dueFrom||iso(0))+'">')+fieldHtml("cr_to","To",'<input id="cr_to" type="date" value="'+(S.filters.dueTo||iso(14))+'">')+'</div>','<button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="S.filters.dueFrom=val(\'cr_from\');S.filters.dueTo=val(\'cr_to\');closeModal();renderScreen(false)">Apply</button>'); }
function sortedTasks(list){ var k=S.sort, d=S.sortDir; var wf=WS.workflow.map(function(s){ return s.id; }); return list.slice().sort(function(a,b){ var x,y; if (k==="manual"){ x=a.sort||0; y=b.sort||0; } else if (k==="due"){ x=a.due; y=b.due; } else if (k==="prio"){ x=PRANK[a.prio]; y=PRANK[b.prio]; } else if (k==="created"){ x=-(a.ago||0); y=-(b.ago||0); } else if (k==="status"){ x=wf.indexOf(a.status); y=wf.indexOf(b.status); } else if (k==="assignee"){ x=person(a.assignee).name; y=person(b.assignee).name; } else if (k==="proj"){ x=projName(a); y=projName(b); } else if (k==="team"){ x=teamName(a.team); y=teamName(b.team); } else if (k==="effort"){ x=a.effort; y=b.effort; } else { x=a.title.toLowerCase(); y=b.title.toLowerCase(); } return ((x<y?-1:x>y?1:0)||(a.due-b.due))*d; }); }
function groupKey(t,g){ if (g==="status") return t.status; if (g==="team") return t.team||""; if (g==="assignee") return t.assignee||""; if (g==="proj") return t.proj; if (g==="prio") return t.prio; if (g==="due") return t.due<0?"overdue":t.due===0?"today":t.due===1?"tomorrow":t.due<=weekRange(0)[1]?"week":t.due<=weekRange(1)[1]?"nextweek":"later"; return ""; }
function groupLabel(key,g){ if (g==="status") return {l:stageName(key),c:""}; if (g==="team"){ return {l:teamName(key),c:teamVar(key)}; } if (g==="assignee") return {l:key?person(key).name:"Unassigned",c:""}; if (g==="proj"){ var p=project(key); return {l:p?p.name:"No project",c:""}; } if (g==="prio") return {l:prioL(key),c:""}; if (g==="due") return {l:{overdue:"Overdue",today:"Today",tomorrow:"Tomorrow",week:"This week",nextweek:"Next week",later:"Later"}[key],c:""}; return {l:"",c:""}; }
function groupOrder(g){ if (g==="status") return WS.workflow.map(function(s){ return s.id; }); if (g==="team") return activeTeams().map(function(t){ return t.id; }).concat([""]); if (g==="assignee") return Object.keys(PEOPLE); if (g==="proj") return PROJECTS.map(function(p){ return p.id; }); if (g==="prio") return ["urgent","high","medium","low"]; if (g==="due") return ["overdue","today","tomorrow","week","nextweek","later"]; return []; }
function groupedTasks(list,g){ var m={}; list.forEach(function(t){ var k=groupKey(t,g); (m[k]=m[k]||[]).push(t); }); var keys=groupOrder(g).filter(function(k){ return m[k]; }); Object.keys(m).forEach(function(k){ if (keys.indexOf(k)<0) keys.push(k); }); return keys.map(function(k){ return {key:k,tasks:m[k]}; }); }
function groupOp(g,key){ if (g==="status") return {type:"MOVE_TASK_STATUS",toStatusId:key,apply:function(t){ t.status=key; }}; if (g==="team") return {type:"MOVE_TASK_TEAM",teamId:key||null,apply:function(t){ t.team=key||null; }}; if (g==="assignee") return {type:"MOVE_TASK_ASSIGNEE",assigneeId:key||null,apply:function(t){ t.assignee=key||null; }}; if (g==="proj") return {type:"MOVE_TASK_PROJECT",projectId:key,apply:function(t){ t.proj=key; }}; if (g==="prio") return {type:"MOVE_TASK_PRIORITY",priority:key,apply:function(t){ t.prio=key; }}; return null; }
function rankBetween(before,after,fallback){ var b=before?before.sort||0:null, a=after?after.sort||0:null; if (b!=null&&a!=null) return (b+a)/2; if (b!=null) return b+1000; if (a!=null) return a-1000; return fallback||0; }
function taskCardColor(t,view){ var mode=((WS.taskCardColors||{})[view])||"team", firstLabel=labelsOf(t)[0]; return mode==="label"&&firstLabel?firstLabel.color:teamVar(t.team); }
function taskIdFrom(el){ var host=el&&el.closest?el.closest("[data-id]"):null; return host?host.getAttribute("data-id"):""; }

/* ---------- toolbar ---------- */
function pillSel(name,cur,opts,cb){ var selected=opts.filter(function(o){return o[0]===cur;})[0]||opts[0]||["",""]; return '<label class="pillsel pillsel-custom'+(cur?" on":"")+'"><span>'+name+'</span><button type="button" class="pillsel-trigger" onclick="event.preventDefault();event.stopPropagation();pillSelToggle(this.parentNode)"><span class="pillsel-value">'+esc(selected[1])+'</span><span class="pillsel-chevron"></span></button><select class="pillsel-native" onchange="'+cb+'">'+opts.map(function(o){ return '<option value="'+attr(o[0])+'"'+(o[0]===cur?" selected":"")+'>'+esc(o[1])+'</option>'; }).join("")+'</select><span class="pillsel-menu" role="listbox">'+opts.map(function(o){ return '<button type="button" role="option" data-value="'+attr(o[0])+'"'+(o[0]===cur?' aria-selected="true"':'')+' onclick="pillSelChoose(this)">'+esc(o[1])+'</button>'; }).join("")+'</span></label>'; }
function pillSelToggle(root){ document.querySelectorAll(".pillsel-custom.open").forEach(function(x){if(x!==root)x.classList.remove("open");}); root.classList.toggle("open"); }
function pillSelChoose(option){ var root=option.closest(".pillsel-custom"), select=root&&root.querySelector(".pillsel-native"); if(!root||!select)return; select.value=option.getAttribute("data-value"); root.querySelector(".pillsel-value").textContent=option.textContent; root.classList.toggle("on",!!select.value); root.classList.remove("open"); root.querySelectorAll("[role=option]").forEach(function(x){x.setAttribute("aria-selected",x===option?"true":"false");}); select.dispatchEvent(new Event("change",{bubbles:true})); }
document.addEventListener("click",function(e){if(!e.target.closest(".pillsel-custom"))document.querySelectorAll(".pillsel-custom.open").forEach(function(x){x.classList.remove("open");});});
function viewSwitch(views){ var all={kanban:["Kanban",I.kanban],list:["List",I.list],grid:["Grid",I.grid],calendar:["Calendar",I.calendar.replace('class="i"','')],timeline:["Timeline",I.timeline]}; return '<div class="seg" data-tour="task-views">'+(views||["kanban","list","grid","calendar","timeline"]).map(function(k){ return '<button data-view="'+k+'" class="'+(S.taskView===k?"on":"")+'" onclick="S.taskView=\''+k+'\';renderScreen(false)">'+all[k][1]+all[k][0]+'</button>'; }).join("")+'</div>'; }
var FILTER_DEFS=function(opts){ var tags=WS.tags.slice(); TASKS.forEach(function(x){ x.tags.forEach(function(g){ if (tags.indexOf(g)<0) tags.push(g); }); }); var defs=[
  ["status","Status",[["","Any"]].concat(WS.workflow.map(function(s){ return [s.id,s.name]; }))],["team","Team",[["","Any"]].concat(activeTeams().map(function(x){ return [x.id,x.name]; }))],["assignee","Assignee",[["","Any"]].concat(peopleOpts())],["reviewer","Reviewer",[["","Any"]].concat(peopleOpts())],
  ["prio","Priority",[["","Any"]].concat(PRIOS)],["tag","Tag",[["","Any"]].concat(tags.map(function(x){ return [x,x]; }))],["dependency","Dependency",[["","All dependency states"],["blocked","Blocked"],["ready","Ready"],["blocking","Blocking other tasks"],["has","Has dependencies"],["none","No dependencies"]]],["due","Due date",DUE_PRESETS]];
  if (!opts.noProject){ defs.splice(4,0,["proj","Project",[["","Any"]].concat((S.filters.archived?PROJECTS:liveProjects()).map(function(p){ return [p.id,p.name]; }))]); if (PROJECTS.some(function(p){ return p.status==="archived"; })) defs.push(["archived","Archived projects",[["","Hidden"],["show","Show"]]]); }
  if (TASKS.some(function(x){ return x.hidden||autoHidden(x); })) defs.push(["hidden","Hidden tasks",[["","Hidden"],["show","Show all"],["only","Hidden only"]]]);
  if (allLabels().length) defs.push(["label","Label",[["","All labels"]].concat(allLabels().map(function(l){ return [l.id,l.name]; }))]); return defs; };
function filterLabel(k,v){ if (k==="status") return stageName(v); if (k==="team") return teamName(v); if (k==="assignee"||k==="reviewer") return person(v).name; if (k==="proj") return (project(v)||{name:v}).name; if (k==="prio") return prioL(v); if (k==="dependency") return {blocked:"Blocked",ready:"Ready",blocking:"Blocking other tasks",has:"Has dependencies",none:"No dependencies"}[v]||v; if (k==="due"){ var p=DUE_PRESETS.filter(function(x){ return x[0]===v; })[0]; return p?p[1]:v; } if (k==="archived") return "shown"; if (k==="hidden") return v==="only"?"hidden only":"shown"; if (k==="kind") return "In review"; return v; }
function filterBar(opts){ opts=opts||{}; var f=S.filters; var defs=FILTER_DEFS(opts); var active=defs.filter(function(d){ return f[d[0]]; }); if (f.kind) active.push(["kind","Stage kind"]);
  var h='<div class="toolbar" data-tour="task-filters">'+(opts.noScope?'':'<div class="seg"><button class="'+(S.taskScope==="mine"?"on":"")+'" onclick="S.taskScope=\'mine\';renderScreen(false)">Mine</button><button class="'+(S.taskScope==="all"?"on":"")+'" onclick="S.taskScope=\'all\';renderScreen(false)">All</button></div>')+
    '<button data-tour="task-dependency-filter" class="btn sm'+(active.length?" ink":"")+'" onclick="filterModal()" aria-label="Filters">'+I.filter+'<span class="tb-label">Filters</span>'+(active.length?' <span class="cnt" style="background:var(--color-secondary);color:#111;border-radius:10px;padding:0 6px;font-size:10px">'+active.length+'</span>':'')+'</button>'+
    '<div class="fchips">'+active.map(function(d){ var k=d[0]; return '<span class="fchip">'+esc(d[1])+': <b>'+esc(filterLabel(k,f[k]))+'</b>'+(k==="due"&&f.due==="custom"?' <span class="mono">'+esc(f.dueFrom||"…")+'→'+esc(f.dueTo||"…")+'</span>':'')+'<button title="Remove" onclick="setFilter(\''+k+'\',\'\')">'+I.x+'</button></span>'; }).join("")+(active.length>1?'<button class="btn xs ghost" onclick="clearFilters()">Clear all</button>':'')+'</div><span class="spacer"></span>';
  if (S.taskView!=="calendar"&&S.taskView!=="timeline") h+=pillSel("Sort",S.sort,[["manual","Manual"],["due","Due date"],["prio","Priority"],["created","Created"],["title","A → Z"],["status","Status"],["team","Team"],["assignee","Assignee"]],"S.sort=this.value;S.sortDir=1;renderScreen(false)")+'<button class="iconbtn" style="width:30px;height:30px" title="Reverse sort" aria-label="Reverse sort" onclick="S.sortDir=-S.sortDir;renderScreen(false)">'+(S.sortDir>0?I.arrowdn:I.arrowup)+'</button>';
  if (S.taskView==="list"||S.taskView==="grid") h+=pillSel("Group",S.group,[["","None"],["status","Status"],["team","Team"],["assignee","Assignee"],["proj","Project"],["prio","Priority"],["due","Due date"]],"S.group=this.value;renderScreen(false)");
  if (S.taskView==="grid") h+='<button class="btn sm" onclick="fieldsMenu(this)" data-menu>'+I.grid+'Fields</button>';
  h+=taskCheckChip()+viewsMenuBtn(); return h+'</div>'; }
function filterModal(){ var f=S.filters; var defs=FILTER_DEFS({noProject:S.screen==="projects"&&S.projectId}); openModal("Filters",'<div class="fgrid">'+defs.map(function(d){ return fieldHtml("fm_"+d[0],d[1],selectHtml("fm_"+d[0],d[2],f[d[0]]||"",d[0]==="due"?'onchange="document.getElementById(\'fm_range\').style.display=this.value===\'custom\'?\'grid\':\'none\'"':'')); }).join("")+'</div><div id="fm_range" class="field-row" style="display:'+(f.due==="custom"?"grid":"none")+'">'+fieldHtml("fm_from","From",'<input id="fm_from" type="date" value="'+(f.dueFrom||iso(0))+'">')+fieldHtml("fm_to","To",'<input id="fm_to" type="date" value="'+(f.dueTo||iso(14))+'">')+'</div><p class="hint">Filters combine with AND. Save the result as a view to reuse it.</p>','<button class="btn ghost" onclick="closeModal();clearFilters()">Clear all</button><span class="spacer"></span><button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="applyFilterModal()">Apply</button>',true); }
function applyFilterModal(){ useManualTaskFilters(); var defs=FILTER_DEFS({noProject:S.screen==="projects"&&S.projectId}); defs.forEach(function(d){ S.filters[d[0]]=val("fm_"+d[0]); }); if (S.filters.due==="custom"){ S.filters.dueFrom=val("fm_from"); S.filters.dueTo=val("fm_to"); } S.activeView=null; closeModal(); renderScreen(false); }
function viewsMenuBtn(){ var cur=S.activeView?byId(VIEWS,S.activeView):null; return '<button class="btn sm'+(cur?" ink":"")+'" data-menu onclick="viewsMenu(this)" aria-label="Views">'+I.star+'<span class="tb-label">'+(cur?esc(cur.name):"Views")+'</span>'+I.chevd+'</button>'; }
function viewsMenu(anchor){ ctxMenu(anchor,'<div class="mh">Saved views</div>'+(VIEWS.length?VIEWS.map(function(v){ return '<button onclick="closePops();applyView(\''+v.id+'\')">'+I.star+'<span style="flex:1">'+esc(v.name)+(S.activeView===v.id?" ✓":"")+'</span><span class="hint">'+esc(v.type)+'</span></button>'; }).join(""):'<div class="hint" style="padding:6px 10px">No saved views yet</div>')+'<div class="mh">This view</div><button onclick="closePops();saveViewModal()">'+I.plus+(S.activeView?"Save as new view":"Save current view")+'</button>'+(S.activeView?'<button onclick="closePops();updateView()">'+I.check+'Update “'+esc((byId(VIEWS,S.activeView)||{}).name)+'”</button><button onclick="closePops();renameView(\''+S.activeView+'\')">'+I.edit+'Rename</button><button onclick="closePops();deleteViewById(\''+S.activeView+'\');toast(\'View deleted\',\'bad\')">'+I.trash+'Delete</button><button onclick="closePops();S.activeView=null;clearFilters()">'+I.x+'Exit view</button>':'')); }
var GRID_FIELDS=[["status","Status"],["team","Team"],["assignee","Assignee"],["reviewer","Reviewer"],["proj","Project"],["prio","Priority"],["start","Start"],["due","Due"],["effort","Effort (h)"],["tags","Tags"]].concat((WS.customFields||[]).map(function(f){ return ["cf:"+f.id,f.name]; }));
function fieldsMenu(anchor){ var cf=(WS.customFields||[]).map(function(f){ return ["cf:"+f.id,f.name]; }); ctxMenu(anchor,'<div class="mh">Visible columns</div>'+GRID_FIELDS.slice(0,10).concat(cf).map(function(f){ var on=S.gridFields.indexOf(f[0])>=0; return '<button onclick="event.stopPropagation();toggleGridField(\''+f[0]+'\')"><span style="width:16px">'+(on?"✓":"")+'</span>'+esc(f[1])+'</button>'; }).join("")); }
function toggleGridField(k){ var i=S.gridFields.indexOf(k); if (i>=0) S.gridFields.splice(i,1); else S.gridFields.push(k); renderScreen(false); fieldsMenu(document.querySelector("[data-menu]")||document.body); }
function viewSnapshot(){ return {type:S.taskView,filters:clone(S.filters),sort:S.sort,group:S.group,fields:S.gridFields.slice(),config:{scope:S.taskScope,sortDir:S.sortDir}}; }
function applyView(id){ var v=byId(VIEWS,id); if (!v) return; S.taskView=v.type; S.filters=Object.assign(emptyTaskFilters(),v.filters||{}); S.sort=v.sort||"manual"; S.group=v.group||""; if (v.fields&&v.fields.length) S.gridFields=v.fields.slice(); S.taskScope=(v.config&&v.config.scope)||"all"; S.sortDir=(v.config&&v.config.sortDir)||1; S.activeView=id; if (S.screen!=="tasks") go("tasks"); else renderScreen(false); }
function saveViewModal(){ openModal("Save view",fieldHtml("sv_name","Name",'<input id="sv_name" placeholder="e.g. Design — this week">')+'<p class="hint">Saves the current view type, filters, sort, grouping and visible fields.</p>','<button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="if(require([\'sv_name\'])){var v=Object.assign({id:uid(\'sv\'),name:val(\'sv_name\'),owner:ME},viewSnapshot());VIEWS.push(v);S.activeView=v.id;closeModal();toast(\'View saved\');renderScreen(false);persistView(v,true)}">Save</button>'); }
function updateView(){ var v=byId(VIEWS,S.activeView); if (!v) return; Object.assign(v,viewSnapshot()); toast("View updated"); renderScreen(false); persistView(v,false); }
function viewMenu(anchor,id){ ctxMenu(anchor,'<button onclick="closePops();renameView(\''+id+'\')">'+I.edit+'Rename</button><button onclick="closePops();deleteViewById(\''+id+'\');toast(\'View deleted\',\'bad\')">'+I.trash+'Delete view</button>'); }
function renameView(id){ var v=byId(VIEWS,id); openModal("Rename view",fieldHtml("sv_name","Name",'<input id="sv_name" value="'+attr(v.name)+'">'),'<button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="if(require([\'sv_name\'])){var v=byId(VIEWS,\''+id+'\');v.name=val(\'sv_name\');closeModal();renderScreen(false);persistView(v,false)}">Save</button>'); }

function renderTasks(){ var list=filteredTasks(); var h='<div class="pagehead task-pagehead"><div><h1>'+tr(S.taskScope==="mine"?"My tasks":"All tasks")+'</h1><div class="muted" style="margin-top:4px">'+list.length+' '+tr("tasks")+' · '+list.filter(function(x){return !isClosed(x);}).length+' '+tr("open")+(S.activeView?' · '+tr("view")+' “'+esc((byId(VIEWS,S.activeView)||{}).name)+'”':'')+'</div></div><div class="actions">'+viewSwitch()+'<button class="btn task-export" onclick="exportModal(\'xlsx\')">'+I.download+'Excel</button>'+(canI.createTask()?'<button class="btn primary" onclick="newTaskModal()">'+I.plus+'New task</button>':'')+'</div></div>'+filterBar();
  h+=taskViewBody(list); document.getElementById("content").innerHTML=h; }
function taskViewBody(list){ var out=S.taskView==="kanban"?kanban(list):S.taskView==="list"?taskTable(list):S.taskView==="grid"?taskGrid(list):S.taskView==="calendar"?calendar(list):timeline(list); return '<div data-tour="task-list">'+out+'</div>'; }

/* ---------- KANBAN (drag within column = REORDER_TASK, between columns = MOVE_TASK_STATUS) ---------- */
function kanban(list){ return '<div class="kanban">'+WS.workflow.map(function(s){ var col=sortedTasks(list.filter(function(x){ return x.status===s.id; })); return '<div class="kcol" data-status="'+s.id+'" ondragover="kOver(event,this)" ondragleave="this.classList.remove(\'over\')" ondrop="kDrop(event,\''+s.id+'\',this,null)"><div class="kcol-head '+s.kind+'"><span class="kdot"></span>'+esc(s.name)+'<span class="cnt">'+col.length+'</span></div><div class="kcol-body">'+col.map(kcard).join("")+(col.length?'':'<div class="empty" style="padding:18px 8px"><p>Drop a card here</p></div>')+'</div>'+(canI.createTask()?'<button class="kadd" onclick="newTaskModal({status:\''+s.id+'\'})">+ Add task</button>':'')+'</div>'; }).join("")+'</div>'; }
function kcard(tk){ var v=tk.versions.length?tk.versions[tk.versions.length-1]:null; var dim=tk.hidden||autoHidden(tk); return '<div class="kcard'+(dim?" dim":"")+(taskChecked(tk.id)?" checked":"")+'" style="--tc:'+taskCardColor(tk,"kanban")+'" draggable="true" data-id="'+attr(tk.id)+'" data-status="'+attr(tk.status)+'" ondragstart="kStart(event,taskIdFrom(this))" ondragend="kEnd(this)" ondragover="kCardOver(event,this)" ondragleave="this.classList.remove(\'drop-before\')" ondrop="kDrop(event,this.getAttribute(\'data-status\'),this.closest(\'.kcol\'),taskIdFrom(this))" onclick="openTask(taskIdFrom(this))">'+(v?'<div class="kthumb" style="background:'+(v.img?"url("+v.img+") center/cover":v.color)+'">V'+v.n+(v.state==="approved"?" · approved":"")+'</div>':'')+labelChips(tk,true)+'<div class="kt-line">'+taskCheckBtn(tk.id)+'<div class="kt">'+esc(tk.title)+'</div></div><div class="km">'+(dim?'<span class="badge muted-badge" title="'+(tk.hidden?"Hidden manually":"Auto-hidden \u00b7 "+attr(autoHideLabel()))+'">'+(tk.hidden?"hidden":"archived")+'</span>':'')+dependencyBadge(tk,false)+requestBadge(tk)+teamBadge(tk.team)+'<span>'+esc(projName(tk))+'</span></div><div class="kf"><span style="display:flex;gap:6px;align-items:center"><span class="prio '+tk.prio+'" style="height:12px" title="'+prioL(tk.prio)+'"></span><span class="due '+dueCls(tk.due,tk)+'">'+dueTxt(tk.due)+'</span>'+(tk.effort?'<span class="tiny muted mono">'+tk.effort+'h</span>':'')+(assetCount(tk)?assetBadge(tk):'')+'</span>'+avStack(assigneesOf(tk))+'</div></div>'; }
var DRAG=null, DEP_STATUS_CONTINUE=null;
function needsDependencyWarning(tk,status){ var kind=stageKind(status); return isTaskBlocked(tk)&&(kind==="work"||kind==="review"||kind==="closed"); }
function confirmDependencyStatusMove(tk,status,done){ if(!needsDependencyWarning(tk,status)) return done(); var blocked=unresolvedDependencies(tk); DEP_STATUS_CONTINUE=done; openModal("Task still has unresolved dependencies",'<p>This task is blocked by:</p><ul style="margin:8px 0 0;padding-left:20px">'+blocked.map(function(x){return '<li><b>'+esc(x.title)+'</b> · '+esc(stageName(x.status))+'</li>';}).join("")+'</ul><p class="hint" style="margin-top:12px">You can still move it to '+esc(stageName(status))+' when work has started early.</p>','<button class="btn" onclick="DEP_STATUS_CONTINUE=null;closeModal()">Cancel</button><button class="btn primary" onclick="var fn=DEP_STATUS_CONTINUE;DEP_STATUS_CONTINUE=null;closeModal();if(fn)fn()">Move anyway</button>',true); }
function kStart(e,id){ DRAG=id; e.dataTransfer.effectAllowed="move"; e.dataTransfer.setData("text/plain",id); e.stopPropagation(); setTimeout(function(){ var el=document.querySelector('.kcard[data-id="'+id+'"]'); if (el) el.classList.add("drag"); },0); }
function kEnd(el){ el.classList.remove("drag"); document.querySelectorAll(".drop-before,.kcol.over").forEach(function(x){ x.classList.remove("drop-before","over"); }); }
function kOver(e,col){ e.preventDefault(); col.classList.add("over"); }
function kCardOver(e,card){ e.preventDefault(); e.stopPropagation(); card.classList.add("drop-before"); }
function kDrop(e,status,col,beforeId){ e.preventDefault(); e.stopPropagation(); col.classList.remove("over"); document.querySelectorAll(".drop-before").forEach(function(x){ x.classList.remove("drop-before"); }); var id=DRAG||e.dataTransfer.getData("text/plain"); var tk=task(id); DRAG=null; if (!tk||id===beforeId) return;
  var colTasks=sortedTasks(filteredTasks().filter(function(x){ return x.status===status&&x.id!==id; })); var idx=beforeId?colTasks.findIndex(function(x){ return x.id===beforeId; }):colTasks.length; var after=idx>0?colTasks[idx-1]:null, before=idx<colTasks.length?colTasks[idx]:null; var newSort=rankBetween(after,before,tk.sort);
  if (tk.status===status){ if (S.sort!=="manual") return toast("Switch sort to Manual to reorder cards"); moveTask(tk,{type:"REORDER_TASK",afterTaskId:after?after.id:null,beforeTaskId:before?before.id:null},function(t){ t.sort=newSort; }); }
  else { var from=tk.status, run=function(){ moveTask(tk,{type:"MOVE_TASK_STATUS",fromStatusId:from,toStatusId:status,afterTaskId:after?after.id:null,beforeTaskId:before?before.id:null},function(t){ t.status=status; t.sort=newSort; }).then(function(saved){ if(saved===false)return false; toast("Moved to “"+stageName(status)+"”"); if (stageKind(status)==="review"&&tk.reviewer) notify("status",tk.reviewer,tk.id); }); }; confirmDependencyStatusMove(tk,status,run); } }

/* ---------- LIST (grouping, drag reorder, drag between groups) ---------- */
function setSort(k){ if (S.sort===k) S.sortDir=-S.sortDir; else { S.sort=k; S.sortDir=1; } renderScreen(false); }
/* v38 fixed column widths (px) by column type: the table no longer re-measures itself from its content, so switching Mine/All or filters can't shift columns */
var LIST_COL_W={check:40,drag:28,title:164,status:116,dependency:80,team:118,assignee:124,proj:114,prio:80,start:58,due:146,effort:48,tags:76};
var GRID_COL_W={drag:32,title:230,status:130,team:150,assignee:160,reviewer:160,proj:170,prio:100,start:130,due:130,effort:90,tags:200};
function colW(map,k){ return map[k]||(String(k).indexOf("cf:")===0?140:120); }
function taskTable(list){ var k=S.sort; var th=function(key,label){ return '<th style="width:'+colW(LIST_COL_W,key)+'px" class="'+(k===key?"on":"")+'" onclick="setSort(\''+key+'\')">'+label+(k===key?(S.sortDir>0?" ↑":" ↓"):"")+'</th>'; };
  if (!list.length) return '<div class="panel">'+emptyBox("No tasks match these filters","Clear a filter or switch to All tasks.")+'</div>';
  var row=function(x){ return '<tr draggable="true" data-id="'+attr(x.id)+'" ondragstart="kStart(event,taskIdFrom(this))" ondragend="lEnd(this)" ondragover="lRowOver(event,this)" ondragleave="this.classList.remove(\'drop-before\')" ondrop="lDrop(event,this)" onclick="openTask(taskIdFrom(this))" class="'+(taskChecked(x.id)?'checked':'')+'"><td class="tcheck-col" onclick="event.stopPropagation()">'+taskCheckBtn(x.id)+'</td><td class="drag-h">'+I.drag+'</td><td class="t"><div>'+esc(x.title)+'</div><div class="mono tiny muted">'+esc(x.id)+'</div></td><td onclick="event.stopPropagation();statusMenu(this,taskIdFrom(this))">'+statusBadge(x.status)+'</td><td>'+dependencyBadge(x,false)+'</td><td>'+teamBadge(x.team)+'</td><td><span class="cell-flex">'+avStack(assigneesOf(x))+esc(assigneesOf(x).map(first).join(", "))+'</span></td><td>'+esc(projName(x))+'</td><td onclick="event.stopPropagation();prioMenu(this,taskIdFrom(this))"><span class="cell-flex"><span class="prio '+x.prio+'" style="height:14px"></span>'+prioL(x.prio)+'</span></td><td class="mono">'+dueDate(x.due-x.span)+'</td><td><span class="due '+dueCls(x.due,x)+'">'+dueDate(x.due)+' · '+dueTxt(x.due)+'</span></td><td class="mono">'+(x.effort||"—")+'h</td><td>'+x.tags.slice(0,3).map(function(t){ return '<span class="badge">'+esc(t)+'</span> '; }).join("")+'</td></tr>'; };
  var body=""; if (S.group){ groupedTasks(sortedTasks(list),S.group).forEach(function(g){ var gl=groupLabel(g.key,S.group); body+='<tr class="grp" data-group="'+attr(g.key)+'" ondragover="event.preventDefault();this.classList.add(\'over\')" ondragleave="this.classList.remove(\'over\')" ondrop="lGroupDrop(event,this,\''+attr(g.key)+'\')"><td colspan="13"><span style="display:inline-flex;align-items:center;gap:8px">'+(gl.c?'<span class="tdot" style="--tc:'+gl.c+'"></span>':'')+esc(gl.l)+'<span class="cnt">'+g.tasks.length+'</span>'+(S.group==="assignee"&&g.key?'<span class="hint mono">'+assigned(g.key)+'h / '+person(g.key).cap+'h</span>':'')+'</span></td></tr>'+g.tasks.map(row).join(""); }); } else body=sortedTasks(list).map(row).join("");
  return '<div class="panel"><div class="tbl-wrap"><table class="tbl tbl-fixed" style="--tbl-min:'+Object.keys(LIST_COL_W).reduce(function(s,x){return s+LIST_COL_W[x];},0)+'px"><thead><tr><th class="tcheck-col" style="width:'+LIST_COL_W.check+'px"></th><th style="width:'+LIST_COL_W.drag+'px"></th>'+th("title","Task")+th("status","Status")+'<th style="width:'+LIST_COL_W.dependency+'px">Dependency</th>'+th("team","Team")+th("assignee","Assignee")+th("proj","Project")+th("prio","Priority")+'<th style="width:'+LIST_COL_W.start+'px">Start</th>'+th("due","Due")+th("effort","Est.")+'<th style="width:'+LIST_COL_W.tags+'px">Tags</th></tr></thead><tbody>'+body+'</tbody></table></div><div class="panel-foot hint">Drag rows to reorder (Manual sort) or drop them on a group header to change status, team, assignee, project or priority. Click a status or priority to change it.</div></div>'; }
function lEnd(el){ el.classList.remove("dragging"); document.querySelectorAll(".drop-before,.grp.over").forEach(function(x){ x.classList.remove("drop-before","over"); }); }
function lRowOver(e,tr){ e.preventDefault(); e.stopPropagation(); tr.classList.add("drop-before"); }
function lDrop(e,tr){ e.preventDefault(); e.stopPropagation(); tr.classList.remove("drop-before"); var id=DRAG||e.dataTransfer.getData("text/plain"); DRAG=null; var tk=task(id), target=task(tr.getAttribute("data-id")); if (!tk||!target||tk===target) return;
  var ops=[]; if (S.group){ var gk=groupKey(target,S.group); if (groupKey(tk,S.group)!==gk){ var op=groupOp(S.group,gk); if (op) ops.push(op); } }
  var listIds=Array.prototype.map.call(document.querySelectorAll(".tbl tbody tr[data-id]"),function(r){ return r.getAttribute("data-id"); }).filter(function(x){ return x!==id; }); var idx=listIds.indexOf(target.id); var after=idx>0?task(listIds[idx-1]):null; var newSort=rankBetween(after,target,tk.sort);
  if (S.sort!=="manual"&&!ops.length) return toast("Switch sort to Manual to reorder rows");
  var run=function(){ if (S.sort==="manual") moveTask(tk,{type:"REORDER_TASK",afterTaskId:after?after.id:null,beforeTaskId:target.id},function(t){ t.sort=newSort; }); };
  if (ops.length){ var o=ops[0]; var apply=o.apply; delete o.apply; moveTask(tk,o,apply).then(run); } else run(); }
function lGroupDrop(e,tr,key){ e.preventDefault(); tr.classList.remove("over"); var id=DRAG||e.dataTransfer.getData("text/plain"); DRAG=null; var tk=task(id); if (!tk) return; if (groupKey(tk,S.group)===key) return; var op=groupOp(S.group,key); if (!op) return toast("Can't move into a due-date group — change the date instead"); var apply=op.apply; delete op.apply; moveTask(tk,op,apply).then(function(saved){ if(saved===false)return false; toast("Moved to "+groupLabel(key,S.group).l); }); }
function statusMenu(anchor,id){ var tk=task(id); if (!canI.editTask(tk)) return; ctxMenu(anchor,'<div class="mh">Move to</div>'+WS.workflow.map(function(s){ return '<button onclick="closePops();setStatus(\''+id+'\',\''+s.id+'\')"><span class="kdot" style="width:9px;height:9px;border-radius:50%;background:'+(s.kind==="closed"?"var(--color-success)":s.kind==="review"?"var(--color-warning)":s.kind==="revision"?"var(--color-danger)":"var(--color-primary)")+'"></span>'+esc(s.name)+(tk.status===s.id?" ✓":"")+'</button>'; }).join("")); }
function prioMenu(anchor,id){ var tk=task(id); if (!canI.editTask(tk)) return; ctxMenu(anchor,'<div class="mh">Priority</div>'+PRIOS.map(function(p){ return '<button onclick="closePops();setPrio(\''+id+'\',\''+p[0]+'\')"><span class="prio '+p[0]+'" style="height:12px"></span>'+p[1]+(tk.prio===p[0]?" ✓":"")+'</button>'; }).join("")); }
function setStatus(id,st){ var tk=task(id); if (tk.status===st) return; confirmDependencyStatusMove(tk,st,function(){ moveTask(tk,{type:"MOVE_TASK_STATUS",fromStatusId:tk.status,toStatusId:st},function(t){ t.status=st; }).then(function(saved){ if(saved===false)return false; toast("Moved to “"+stageName(st)+"”"); }); }); }
function setPrio(id,p){ var tk=task(id); moveTask(tk,{type:"MOVE_TASK_PRIORITY",priority:p},function(t){ t.prio=p; }); }

/* ---------- GRID (spreadsheet: every cell edits the same task record, §31) ---------- */
function taskGrid(list){ if (!list.length) return '<div class="panel">'+emptyBox("No tasks match these filters","")+'</div>'; var cols=S.gridFields; var cf=WS.customFields||[];
  var cell=function(x,k){ var ed=canI.editTask(x); var dis=ed?"":" disabled", set='gridSet(taskIdFrom(this),\''+k+'\',this.value)'; if (k==="status") return '<select'+dis+' onchange="'+set+'">'+WS.workflow.map(function(s){ return '<option value="'+attr(s.id)+'"'+(x.status===s.id?" selected":"")+'>'+esc(s.name)+'</option>'; }).join("")+'</select>'; if (k==="team") return '<select'+dis+' onchange="'+set+'">'+teamOpts(true).map(function(o){ return '<option value="'+attr(o[0])+'"'+((x.team||"")===o[0]?" selected":"")+'>'+esc(o[1])+'</option>'; }).join("")+'</select>';
    if (k==="assignee"||k==="reviewer") return '<select'+dis+' onchange="'+set+'">'+peopleOpts().map(function(o){ return '<option value="'+attr(o[0])+'"'+(x[k]===o[0]?" selected":"")+'>'+esc(o[1])+'</option>'; }).join("")+'</select>'; if (k==="proj") return '<select'+dis+' onchange="'+set+'">'+PROJECTS.map(function(p){ return '<option value="'+attr(p.id)+'"'+(x.proj===p.id?" selected":"")+'>'+esc(p.name)+'</option>'; }).join("")+'</select>';
    if (k==="prio") return '<select'+dis+' onchange="'+set+'">'+PRIOS.map(function(p){ return '<option value="'+attr(p[0])+'"'+(x.prio===p[0]?" selected":"")+'>'+p[1]+'</option>'; }).join("")+'</select>'; if (k==="start") return '<input'+dis+' type="date" value="'+iso(x.due-x.span)+'" onchange="'+set+'">'; if (k==="due") return '<input'+dis+' type="date" value="'+iso(x.due)+'" onchange="'+set+'">';
    if (k==="effort") return '<input'+dis+' type="number" min="0" value="'+x.effort+'" onchange="'+set+'">'; if (k==="tags") return tagPicker("tp_grid_"+x.id,x.tags||[],function(value){ gridSet(x.id,"tags",value); },{readonly:!!dis,compact:true});
    if (k.indexOf("cf:")===0){ var f=byId(cf,k.slice(3)); if (!f) return ""; var v=x.custom[f.id]; if (f.type==="checkbox") return '<input'+dis+' type="checkbox" '+(v?"checked":"")+' onchange="gridSet(taskIdFrom(this),\''+k+'\',this.checked)">'; if (f.type==="select") return '<select'+dis+' onchange="'+set+'"><option value="">—</option>'+f.options.map(function(o){ return '<option'+(v===o?" selected":"")+'>'+esc(o)+'</option>'; }).join("")+'</select>'; return '<input'+dis+' type="'+(f.type==="number"?"number":"text")+'" value="'+attr(v==null?"":v)+'" onchange="'+set+'">'; } return ""; };
  var head='<tr><th style="width:'+GRID_COL_W.drag+'px"></th><th style="width:'+GRID_COL_W.title+'px">Task</th>'+cols.map(function(k){ var f=GRID_FIELDS.concat(cf.map(function(c){ return ["cf:"+c.id,c.name]; })).filter(function(g){ return g[0]===k; })[0]; return '<th style="width:'+colW(GRID_COL_W,k)+'px">'+esc(f?f[1]:k)+'</th>'; }).join("")+'</tr>', gridMin=GRID_COL_W.drag+GRID_COL_W.title+cols.reduce(function(s,k){ return s+colW(GRID_COL_W,k); },0);
  var row=function(x){ return '<tr draggable="true" data-id="'+attr(x.id)+'" ondragstart="kStart(event,taskIdFrom(this))" ondragend="lEnd(this)" ondragover="lRowOver(event,this)" ondragleave="this.classList.remove(\'drop-before\')" ondrop="lDrop(event,this)" style="cursor:default"><td class="drag-h">'+I.drag+'</td><td><div class="cell"><input value="'+attr(x.title)+'" '+(canI.editTask(x)?'':'disabled')+' onchange="gridSet(taskIdFrom(this),\'title\',this.value)" style="font-weight:600"><button class="iconbtn flat" style="width:26px;height:26px" onclick="openTask(taskIdFrom(this))" title="Open">'+I.ext+'</button></div></td>'+cols.map(function(k){ return '<td><div class="cell">'+cell(x,k)+'</div></td>'; }).join("")+'</tr>'; };
  var body=""; if (S.group){ groupedTasks(sortedTasks(list),S.group).forEach(function(g){ var gl=groupLabel(g.key,S.group); body+='<tr class="grp" ondragover="event.preventDefault();this.classList.add(\'over\')" ondragleave="this.classList.remove(\'over\')" ondrop="lGroupDrop(event,this,\''+attr(g.key)+'\')"><td colspan="'+(cols.length+2)+'"><span style="display:inline-flex;align-items:center;gap:8px">'+(gl.c?'<span class="tdot" style="--tc:'+gl.c+'"></span>':'')+esc(gl.l)+'<span class="cnt">'+g.tasks.length+'</span></span></td></tr>'+g.tasks.map(row).join(""); }); } else body=sortedTasks(list).map(row).join("");
  return '<div class="panel"><div class="tbl-wrap" style="max-height:70vh"><table class="tbl gridv tbl-fixed" style="--tbl-min:'+gridMin+'px"><thead>'+head+'</thead><tbody>'+body+'</tbody></table></div><div class="panel-foot hint">Every cell writes straight to the task record — the same one Kanban, Calendar and Timeline show.</div></div>'; }
function gridSet(id,k,v){ var tk=task(id); if (!tk) return; if (k==="status") return setStatus(id,v); if (k==="prio") return setPrio(id,v); if (k==="team") return moveTask(tk,{type:"MOVE_TASK_TEAM",teamId:v||null},function(t){ t.team=v||null; }); if (k==="assignee") return moveTask(tk,{type:"MOVE_TASK_ASSIGNEE",assigneeId:v},function(t){ t.assignee=v; }).then(function(saved){ if(saved===false)return false; notify("assigned",v,id); }); if (k==="proj") return moveTask(tk,{type:"MOVE_TASK_PROJECT",projectId:v},function(t){ t.proj=v; });
  if (k==="due"||k==="start"){ var due=k==="due"?offsetFromIso(v):tk.due; var start=k==="start"?offsetFromIso(v):tk.due-tk.span; if (start>due) start=due; return moveTask(tk,{type:"MOVE_TASK_DATE",startDate:iso(start),dueDate:iso(due)},function(t){ t.due=due; t.span=Math.max(1,due-start); }); }
  editTaskWith(tk,function(t){ if (k==="title") t.title=v||t.title; else if (k==="reviewer") t.reviewer=v; else if (k==="effort") t.effort=+v||0; else if (k==="tags") t.tags=tagsFromLegacy(v); else if (k.indexOf("cf:")===0){ var f=byId(WS.customFields,k.slice(3)); t.custom[f.id]=f.type==="number"?(v===""?null:+v):v; } log(t,"edited",{what:k.replace("cf:","")}); }); }

/* ---------- CALENDAR (month / week / day; drag a chip to a day = MOVE_TASK_DATE, §27–28) ---------- */
var CAL_AGENDA={};
function calNav(dir){ if (S.calMode==="month"){ S.calMonth+=dir; if (S.calMonth>11){S.calMonth=0;S.calYear++;} if (S.calMonth<0){S.calMonth=11;S.calYear--;} } else if (S.calMode==="week") S.calDay+=7*dir; else S.calDay+=dir; renderScreen(false); }
function calToday(){ S.calMonth=TODAY.getMonth(); S.calYear=TODAY.getFullYear(); S.calDay=0; renderScreen(false); }
function calendarMobileControls(){ var defs=FILTER_DEFS({noProject:false}), active=defs.filter(function(d){return S.filters[d[0]];}).length+(S.filters.kind?1:0), cur=S.activeView?byId(VIEWS,S.activeView):null;
  return '<div class="calendar-mobile-controls"><div class="cal-mobile-date"><button class="iconbtn" aria-label="'+attr(tr("Previous"))+'" onclick="calNav(-1)">'+I.chevl+'</button><strong>'+calTitle()+'</strong><button class="iconbtn" aria-label="'+attr(tr("Next"))+'" onclick="calNav(1)">'+I.chev+'</button><button class="btn sm cal-mobile-today" onclick="calToday()">'+tr("Today")+'</button></div><div class="cal-mobile-actions"><button class="iconbtn'+(active?' active':'')+'" aria-label="'+attr(tr("Filters"))+'" title="'+attr(tr("Filters"))+'" onclick="filterModal()">'+I.filter+(active?'<span class="cal-mobile-count">'+active+'</span>':'')+'</button><button class="iconbtn'+(cur?' active':'')+'" data-menu aria-label="'+attr(tr("Views"))+'" title="'+attr(tr("Views"))+'" onclick="viewsMenu(this)">'+I.star+'</button><button class="btn sm cal-mobile-scope-toggle" aria-label="'+attr(tr("Scope"))+'" onclick="S.calScope=S.calScope===\'mine\'?\'all\':\'mine\';renderScreen(false)">'+tr(S.calScope==="mine"?"Mine":"Team")+'</button>'+segHtml([["month","Month"],["week","Week"],["day","Day"]],S.calMode,"setCalMode")+'<button class="iconbtn'+(S.calLabelsOpen?' active':'')+'" aria-pressed="'+(S.calLabelsOpen?'true':'false')+'" aria-label="'+attr(tr(S.calLabelsOpen?'Hide labels':'Show labels'))+'" title="'+attr(tr(S.calLabelsOpen?'Hide labels':'Show labels'))+'" onclick="toggleChipLabels()">'+(S.calLabelsOpen?I.eyeoff:I.eye)+'</button></div></div>'; }
function calItems(list){ var byDay={}; list.forEach(function(t){ var k=iso(t.due); (byDay[k]=byDay[k]||[]).push({type:"task",o:t}); }); (S.filters.archived?PROJECTS:liveProjects()).forEach(function(p){ p.milestones.forEach(function(ms){ var k=iso(ms.due); (byDay[k]=byDay[k]||[]).push({type:"ms",o:ms,p:p}); }); if (p.status!=="done"){ var k2=iso(p.due); (byDay[k2]=byDay[k2]||[]).push({type:"pdue",o:p}); } }); return byDay; }
function chipHtml(t){ var ls=labelsOf(t), dim=t.hidden||autoHidden(t);
  return '<div class="chip'+(isClosed(t)?" closed":(t.due<0?" over":""))+(dim?" dim":"")+(taskChecked(t.id)?" checked":"")+'" data-id="'+attr(t.id)+'" style="--tc:'+taskCardColor(t,"calendar")+'" draggable="true" ondragstart="kStart(event,taskIdFrom(this))" ondragend="kEnd(this)" onclick="event.stopPropagation();openTask(taskIdFrom(this))" title="'+attr(t.title+" \u00b7 "+stageName(t.status)+" \u00b7 "+person(t.assignee).name+(isTaskBlocked(t)?" \u00b7 Blocked by "+unresolvedDependencies(t).map(function(x){return x.title;}).join(", "):"")+(ls.length?" \u00b7 "+ls.map(function(x){return x.name;}).join(", "):""))+'">'
    + '<div class="chip-eyebrow">'+(ls.length?labelPills(t)+labelFull(t):'<span class="eb">'+esc(teamName(t.team)||projName(t))+'</span>')
    + '<span class="spacer"></span><span class="sb badge '+badgeCls(t.status)+'">'+esc(stageName(t.status))+'</span></div>'
    + '<div class="chip-main">'+taskCheckBtn(t.id,"xs")+'<span class="pd '+t.prio+'"></span><span class="chip-t">'+(isTaskBlocked(t)?'⛓ ':'')+esc(t.title)+'</span>'+avStack(assigneesOf(t))+'</div></div>'; }
function dayCell(d,items,other,extraCls,limit){ var off=Math.round((d-TODAY)/86400000); var k=iso(off); var h='<div class="cal-day'+(other?" other":"")+(off===0?" today":"")+(extraCls||"")+'" data-off="'+off+'" ondragover="event.preventDefault();this.classList.add(\'over\')" ondragleave="this.classList.remove(\'over\')" ondrop="calDrop(event,this,'+off+')" onclick="if(event.target===this||event.target.classList.contains(\'dn\')||event.target.parentNode.classList.contains(\'dn\'))'+(canI.createTask()?'newTaskModal({due:'+off+'})':'calAgenda(\''+k+'\')')+'"><div class="dn"><span>'+d.getDate()+'</span>'+(off===0?'<b class="todaytag">Today</b>':'')+(items.length>limit?'<small>'+items.length+'</small>':'')+'</div>';
  items.slice(0,limit).forEach(function(it){ if (it.type==="task") h+=chipHtml(it.o); else if (it.type==="ms") h+='<div class="chip ms" onclick="event.stopPropagation();go(\'projects\',\''+it.p.id+'\')" title="'+attr(it.p.name+" · "+it.o.name)+'">◆ '+esc(it.o.name)+'</div>'; else h+='<div class="chip ms" style="border-left-color:var(--color-warning)" onclick="event.stopPropagation();go(\'projects\',\''+it.o.id+'\')">⚑ '+esc(it.o.name)+' '+tr("deadline")+'</div>'; });
  if (items.length>limit) h+='<div class="chip more" onclick="event.stopPropagation();calAgenda(\''+k+'\')">+'+(items.length-limit)+' '+tr("more")+'</div>'; return h+'</div>'; }
function calDrop(e,el,off){ e.preventDefault(); el.classList.remove("over"); var id=DRAG||e.dataTransfer.getData("text/plain"); DRAG=null; var tk=task(id); if (!tk||tk.due===off) return; var span=tk.span; moveTask(tk,{type:"MOVE_TASK_DATE",startDate:iso(off-span),dueDate:iso(off)},function(t){ t.due=off; }).then(function(saved){ if(saved===false)return false; toast("Due "+dueDate(off)); }); }
function calendar(list){ var byDay=calItems(list); CAL_AGENDA=byDay; var h='<div class="toolbar calendar-toolbar" style="justify-content:space-between"><div class="cal-nav"><button class="iconbtn" aria-label="'+attr(tr("Previous"))+'" onclick="calNav(-1)">'+I.chevl+'</button><h2>'+calTitle()+'</h2><button class="iconbtn" aria-label="'+attr(tr("Next"))+'" onclick="calNav(1)">'+I.chev+'</button><button class="btn sm" onclick="calToday()">Today</button><button class="btn sm'+(S.calLabelsOpen?" primary":"")+'" aria-pressed="'+(S.calLabelsOpen?"true":"false")+'" id="calLabelBtn" onclick="toggleChipLabels()" title='+(S.calLabelsOpen?'"Hide the label names"':'"Name every label on the board"')+'>'+(S.calLabelsOpen?I.eyeoff+"Hide labels":I.eye+"Show labels")+'</button></div><div class="calendar-display-controls">'+segHtml([["month","Month"],["week","Week"],["day","Day"]],S.calMode,"setCalMode")+'<div class="legend" style="padding:0"><span><i style="background:var(--color-primary)"></i>Task (team color)</span><span><i style="background:var(--color-secondary)"></i>Milestone</span><span><i style="background:var(--color-danger)"></i>Overdue</span></div></div></div>';
  if (S.calMode==="month"){ var y=S.calYear, m=S.calMonth; var startDow=(new Date(y,m,1).getDay()+6)%7; var start=new Date(y,m,1-startDow); var cells=(startDow+new Date(y,m+1,0).getDate()<=35)?35:42;
    h+='<div class="cal'+(S.calLabelsOpen?" labels-open":"")+'"><div class="cal-head">'+["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(function(d){ return '<div>'+tr(d)+'</div>'; }).join("")+'</div><div class="cal-grid">'; for (var i=0;i<cells;i++){ var d=new Date(start); d.setDate(start.getDate()+i); h+=dayCell(d,byDay[iso(Math.round((d-TODAY)/86400000))]||[],d.getMonth()!==m,"",3); } h+='</div></div>'; }
  else if (S.calMode==="week"){ var w=weekRange(0); var s0=w[0]+Math.floor(S.calDay/7)*7; h+='<div class="cal'+(S.calLabelsOpen?" labels-open":"")+'"><div class="cal-head">'+[0,1,2,3,4,5,6].map(function(i){ var d=dateOf(s0+i); return '<div>'+tr(["Mon","Tue","Wed","Thu","Fri","Sat","Sun"][i])+' '+d.getDate()+'</div>'; }).join("")+'</div><div class="cal-week">'; for (var j=0;j<7;j++){ var dd=dateOf(s0+j); h+=dayCell(dd,byDay[iso(s0+j)]||[],false,"",12); } h+='</div></div>'; }
  else { var items=byDay[iso(S.calDay)]||[]; var dd2=dateOf(S.calDay); h+='<div class="cal'+(S.calLabelsOpen?" labels-open":"")+'"><div class="cal-dayv" ondragover="event.preventDefault()" ondrop="calDrop(event,this,'+S.calDay+')">'+(items.length?items.map(function(it){ if (it.type==="task") return '<div style="display:flex;gap:10px;align-items:center">'+chipHtml(it.o).replace('class="chip','style="flex:1" class="chip')+statusBadge(it.o.status)+av(it.o.assignee)+'</div>'; if (it.type==="ms") return '<div class="chip ms" onclick="go(\'projects\',\''+it.p.id+'\')">◆ '+esc(it.p.name)+' · '+esc(it.o.name)+'</div>'; return '<div class="chip ms" style="border-left-color:var(--color-warning)">⚑ '+esc(it.o.name)+' '+tr("deadline")+'</div>'; }).join(""):emptyBox((UI_LANG==="id"?"Tidak ada tenggat pada ":"Nothing due on ")+uiDow(dd2.getDay()),tr("Drop a task here or create one."),null,canI.createTask()?'<button class="btn sm primary" onclick="newTaskModal({due:'+S.calDay+'})">'+tr("New task")+'</button>':''))+'</div></div>'; }
  var up=sortTasks(list.filter(function(t){ return !isClosed(t)&&t.due>=0&&t.due<=14; }));
  h+=panel("Next 14 days",up.length,'<div class="agenda">'+(up.length?up.map(function(t){ return '<div class="row dated'+(taskChecked(t.id)?" checked":"")+'" data-id="'+attr(t.id)+'" onclick="openTask(taskIdFrom(this))"><div class="prio '+t.prio+'"></div>'+taskCheckBtn(t.id)+'<span class="dd">'+dueDate(t.due)+'</span><div style="min-width:0"><div class="t">'+esc(t.title)+'</div><div class="m">'+teamBadge(t.team)+' · '+esc(projName(t))+' · '+statusBadge(t.status)+'</div></div><div class="r">'+av(t.assignee)+'</div></div>'; }).join(""):emptyBox("Nothing due in the next two weeks",""))+'</div>',null,null,I.calendar);
  return h; }
function calTitle(){ if (S.calMode==="month") return uiMol(S.calMonth)+" "+S.calYear; if (S.calMode==="week"){ var w=weekRange(0); var s=w[0]+Math.floor(S.calDay/7)*7; return (UI_LANG==="id"?"Pekan ":"Week of ")+dueDate(s)+" – "+dueDate(s+6); } var d=dateOf(S.calDay); return uiDow(d.getDay())+", "+uiMol(d.getMonth())+" "+d.getDate(); }
function setCalMode(m){ S.calMode=m; renderScreen(false); }
function openCalendarTask(id){ closeModal(); openTask(id); }
function calAgendaRow(it){
  if(it.type==="task") return taskRow(it.o,{fixedMeta:true,check:true,openAction:"openCalendarTask(taskIdFrom(this))"});
  var milestone=it.type==="ms", p=milestone?it.p:it.o, title=milestone?it.o.name:p.name;
  return '<div class="row cal-context-row" onclick="closeModal();go(\'projects\',\''+p.id+'\')"><span class="cal-context-icon '+(milestone?'milestone':'deadline')+'">'+(milestone?'◆':'⚑')+'</span><span class="cal-context-spacer"></span><div style="min-width:0"><div class="t">'+esc(title)+'</div><div class="m"><span class="badge">'+tr(milestone?'Milestone':'Project deadline')+'</span><span>'+esc(p.name)+'</span></div></div><div class="r meta-grid"><span class="mcell mcell-assets"></span><span class="mcell mcell-due"><span class="due">'+dueDate(milestone?it.o.due:p.due)+'</span></span><span class="mcell mcell-who">'+av(p.owner)+'</span></div></div>';
}
function calAgenda(k){
  var off=offsetFromIso(k), items=CAL_AGENDA[k]||[];
  openModal(dueDate(off)+(items.length?' \u00b7 '+items.length+' '+tr(items.length===1?"item":"items"):""),
    '<div class="agenda cal-more-list">'+(items.length?items.map(calAgendaRow).join(""):emptyBox("Nothing due",""))+'</div>');
}
function renderCalendarScreen(){ var h='<div class="pagehead calendar-pagehead"><div><h1>Calendar</h1><div class="muted" style="margin-top:4px">A view over task dates — drag a task to another day to reschedule it</div></div><div class="actions"><div class="seg"><button class="'+(S.calScope==="mine"?"on":"")+'" onclick="S.calScope=\'mine\';renderScreen(false)">Mine</button><button class="'+(S.calScope==="all"?"on":"")+'" onclick="S.calScope=\'all\';renderScreen(false)">Team</button></div>'+(canI.createTask()?'<button class="btn primary" onclick="newTaskModal()">'+I.plus+'New task</button>':'')+'</div></div>'; var saved=S.taskScope, sv=S.taskView; S.taskScope=S.calScope; S.taskView="calendar"; h+=filterBar({noScope:true}); h+=calendarMobileControls()+calendar(filteredTasks()); S.taskScope=saved; S.taskView=sv; document.getElementById("content").innerHTML=h; }

/* ---------- TIMELINE (drag bar = shift dates, resize = change duration; MOVE_TASK_TIMELINE §32) ---------- */
var TL={from:-14,days:42,label:240};
function timeline(list){ var from=TL.from, days=TL.days; var cols=TL.label+"px repeat("+days+",minmax(26px,1fr))"; var start=dateOf(from);
  var hd='<div class="tl-hd" style="grid-template-columns:'+cols+'"><div style="text-align:left;position:sticky;left:0;background:var(--color-surface);z-index:3">'+tr("Project / task")+'</div>'; for (var i=0;i<days;i++){ var d=new Date(start); d.setDate(start.getDate()+i); var off=from+i; var prevMon=i>0&&(new Date(start.getTime()+(i-1)*86400000)).getDay()===1; var isFirst=d.getDate()===1&&!prevMon; var lbl=(d.getDay()===1||isFirst)?uiMo(d.getMonth())+" "+d.getDate():(prevMon?"":String(d.getDate())); hd+='<div class="'+(d.getDay()===1?"wk":"")+(off===0?" today":"")+'" style="'+(d.getDay()===1||isFirst?"text-align:left;overflow:visible;padding-left:6px;position:relative;z-index:1":"")+'">'+lbl+'</div>'; } hd+='</div>';
  var cells=function(){ var c=''; for (var i=0;i<days;i++){ var d=new Date(start); d.setDate(start.getDate()+i); c+='<div class="tl-cell'+(d.getDay()===0||d.getDay()===6?" we":"")+'" style="grid-column:'+(i+2)+'"></div>'; } return c; };
  var todayLine='<div class="tl-today" style="left:calc('+TL.label+'px + ('+(-from)+' + 0.5) * ((100% - '+TL.label+'px) / '+days+'))"></div>';
  var barStyle=function(s,e){ var a=Math.max(from,s), b=Math.min(from+days-1,e); if (b<a) return null; return 'left:calc('+TL.label+'px + '+(a-from)+' * ((100% - '+TL.label+'px) / '+days+') + 2px);width:calc('+(b-a+1)+' * ((100% - '+TL.label+'px) / '+days+') - 4px)'; };
  var rows=''; var projs=S.projectId&&S.screen==="projects"?PROJECTS.filter(function(p){ return p.id===S.projectId; }):(S.filters.archived?PROJECTS:liveProjects());
  projs.forEach(function(p){ var ts=sortedTasks(list.filter(function(t){ return t.proj===p.id; })); if (!ts.length&&(S.taskScope==="mine"||anyFilter())) return;
    var ps=barStyle(p.start,p.due),progress=projectProgress(p); rows+='<div class="tl-row group" style="grid-template-columns:'+cols+'"><div class="tl-lbl lbl" onclick="go(\'projects\',\''+p.id+'\')">'+esc(p.name)+' <span class="tiny muted mono">'+progress+'%</span></div>'+cells()+(ps?'<div class="tl-bar" style="'+ps+';background:var(--color-border-strong);color:var(--color-text-primary);opacity:.9;cursor:pointer" onclick="go(\'projects\',\''+p.id+'\')">'+esc(p.name)+'</div>':'')+todayLine+'</div>';
    p.milestones.forEach(function(ms){ var s=barStyle(ms.due,ms.due+2); if (!s) return; rows+='<div class="tl-row" style="grid-template-columns:'+cols+';min-height:30px"><div class="tl-lbl" style="color:var(--color-text-secondary)">◆ '+esc(ms.name)+'</div>'+cells()+'<div class="tl-bar ms" style="'+s+';width:auto" title="'+attr(ms.name)+'">'+esc(ms.name)+(ms.done?" ✓":"")+'</div>'+todayLine+'</div>'; });
    ts.forEach(function(t){ var s=barStyle(t.due-t.span,t.due); var ed=canI.editTask(t); rows+='<div class="tl-row" data-id="'+attr(t.id)+'" style="grid-template-columns:'+cols+'"><div class="tl-lbl" onclick="openTask(taskIdFrom(this))">'+av(t.assignee)+'<span class="tdot" style="--tc:'+teamVar(t.team)+'"></span><span style="overflow:hidden;text-overflow:ellipsis">'+esc(t.title)+'</span></div>'+cells()+(s?'<div class="tl-bar'+(isClosed(t)?" closed":"")+'" style="'+s+';--tc:'+teamVar(t.team)+'" data-id="'+attr(t.id)+'" '+(ed?'onmousedown="tlDown(event,taskIdFrom(this),\'move\')"':'')+' onclick="tlClick(taskIdFrom(this))" title="'+attr(t.title+" · "+dueDate(t.due-t.span)+" → "+dueDate(t.due))+'">'+(ed?'<span class="hz l" onmousedown="tlDown(event,taskIdFrom(this),\'start\')"></span>':'')+esc(t.title)+(ed?'<span class="hz r" onmousedown="tlDown(event,taskIdFrom(this),\'end\')"></span>':'')+'</div>':'')+todayLine+'</div>'; }); });
  if (!rows) rows='<div class="empty" style="padding:40px"><p>No tasks match the current filters.</p></div>';
  return '<div class="tlw"><div class="tl-grid" id="tlGrid">'+hd+rows+'</div></div><div class="hint" style="padding:6px 4px">Drag a bar to move it, drag its edges to change duration. Changes persist to the task start/due dates.</div>'; }
var TLD=null;
function tlDown(e,id,mode){ if (e.button!==0) return; e.preventDefault(); e.stopPropagation(); var grid=document.getElementById("tlGrid"); var dayW=(grid.getBoundingClientRect().width-TL.label)/TL.days; var bar=document.querySelector('.tl-bar[data-id="'+id+'"]'); TLD={id:id,mode:mode,x0:e.clientX,dayW:dayW,bar:bar,left0:bar.offsetLeft,w0:bar.offsetWidth,delta:0,moved:false}; bar.classList.add("moving"); document.addEventListener("mousemove",tlMove); document.addEventListener("mouseup",tlUp); }
function tlMove(e){ if (!TLD) return; var dx=e.clientX-TLD.x0; var delta=Math.round(dx/TLD.dayW); if (Math.abs(dx)>3) TLD.moved=true; TLD.delta=delta; var b=TLD.bar; if (TLD.mode==="move") b.style.transform="translateX("+(delta*TLD.dayW)+"px)"; else if (TLD.mode==="end") b.style.width=Math.max(TLD.dayW-4,TLD.w0+delta*TLD.dayW)+"px"; else { var nw=Math.max(TLD.dayW-4,TLD.w0-delta*TLD.dayW); b.style.width=nw+"px"; b.style.transform="translateX("+(TLD.w0-nw)+"px)"; } }
function tlUp(){ document.removeEventListener("mousemove",tlMove); document.removeEventListener("mouseup",tlUp); var d=TLD; TLD=null; if (!d) return; d.bar.classList.remove("moving"); d.bar.style.transform=""; d.bar.style.width=""; var tk=task(d.id); if (!tk||!d.delta||!d.moved) { if (d.moved) renderScreen(false); return; } window._tlSuppress=true; setTimeout(function(){ window._tlSuppress=false; },50);
  var start=tk.due-tk.span, due=tk.due; if (d.mode==="move"){ start+=d.delta; due+=d.delta; } else if (d.mode==="end"){ due=Math.max(start,due+d.delta); } else { start=Math.min(due,start+d.delta); }
  moveTask(tk,{type:"MOVE_TASK_TIMELINE",startDate:iso(start),dueDate:iso(due)},function(t){ t.due=due; t.span=Math.max(1,due-start); }).then(function(saved){ if(saved===false)return false; toast(dueDate(start)+" → "+dueDate(due)); }); }
function tlClick(id){ if (window._tlSuppress) return; openTask(id); }

/* ---------- create (same drawer as viewing a task — a draft that is only saved on "Create") ---------- */
function newTaskModal(pre){ pre=pre||{}; if (S.drawerTask){ var cur=task(S.drawerTask); if (cur&&cur._draft) discardDraft(); }
  var asReq=!!pre.request; var assignee=pre.assignee!==undefined?pre.assignee:(asReq?null:ME); var due=pre.due!==undefined?pre.due:(asReq?7:5); var start=Math.min(due,pre.start!==undefined?pre.start:0);
  var status=pre.status||(asReq?firstStage():(WS.workflow[0]||{}).id); var maxSort=0; TASKS.forEach(function(x){ if (x.status===status&&x.sort>maxSort) maxSort=x.sort; });
  var tplId=pre.tpl||(asReq?(byId(WS.briefTemplates,"general")?"general":""):""); var brief=null; if (tplId){ brief={tpl:tplId}; (byId(WS.briefTemplates,tplId)||{fields:[]}).fields.forEach(function(f){ brief[f]=""; }); if (pre.brief) Object.assign(brief,pre.brief); }
  var tk={id:"T-new",_draft:true,title:pre.title||"",description:pre.description||"",proj:pre.proj||S.projectId||(liveProjects()[0]||{}).id,team:pre.team||(assignee?primaryTeam(assignee):"")||null,status:status,prio:pre.prio||"medium",assignee:assignee,reviewer:pre.reviewer||(assignee?defaultReviewerFor(assignee,pre.team||primaryTeam(assignee)):null),assignees:assignee?[assignee]:[],reviewers:[],dependencies:pre.dependencies||[],hidden:false,assetCount:0,labels:pre.labels||[],due:due,span:Math.max(1,due-start),effort:asReq?0:4,sort:maxSort+1000,tags:pre.tags?tagsFromLegacy(pre.tags):(asReq?["request"]:[]),brief:brief,custom:{},versions:[],files:[],comments:[],activity:[],ago:0,createdBy:ME,requestId:pre.requestId||null,_onCreated:pre.onCreated||null,_request:asReq};
  if (!tk.reviewer&&!asReq) tk.reviewer=ME; tk.reviewers=tk.reviewer?[tk.reviewer]:[]; TASKS.push(tk); openTask("T-new"); S.drawerTab="brief"; renderDrawer(); setTimeout(function(){ var el=document.querySelector(".dr-title"); if (el){ el.focus(); } },80); }
function newRequestModal(pre){ newTaskModal(Object.assign({request:true},pre||{})); }
function discardDraft(){ var i=TASKS.findIndex(function(x){ return x._draft; }); if (i>=0) TASKS.splice(i,1); if (S.drawerTask==="T-new") closeDrawer(); refresh(); }
function createDraft(){ var tk=task("T-new"); if (!tk) return; var title=(document.querySelector(".dr-title")||{}).textContent||tk.title; tk.title=String(title).trim(); if (!tk.title||tk.title==="Untitled task"){ toast("Give the task a title first","bad"); var el=document.querySelector(".dr-title"); if (el) el.focus(); return; }
  var isReq=tk._request||(!tk.assignee&&tk.status===firstStage()); if (!isReq&&!canI.createTask()) return toast("You don't have permission to create tasks","bad");
  var i=TASKS.indexOf(tk); TASKS.splice(i,1); var onCreated=tk._onCreated; var t=clone(tk); delete t._draft; delete t._onCreated; delete t._request; t.id=nextId("T-",TASKS); t.activity=[]; t.assignees=assigneesOf(t); t.reviewers=reviewersOf(t); t.assignee=t.assignees[0]||null; t.reviewer=t.reviewers[0]||null;
  log(t,"created"); if (t.brief) log(t,"brief"); if (t.assignee&&t.assignee!==ME) log(t,"assigned",{to:first(t.assignee)}); closeDrawer();
  createTask(t).then(function(saved){ if(saved===false)return false; toast(isReq&&!t.assignee?"Request "+t.id+" submitted — it is in the inbox for triage":"Task "+t.id+" created"); if (t.assignee) notify("assigned",assigneesOf(t),t.id); if (isReq&&!t.assignee) notify("request",Object.keys(PEOPLE).filter(function(id){ var r=byId(ROLES,PEOPLE[id].perm); return PEOPLE[id].perm==="admin"||(r&&(r.permissions||[]).indexOf("decide_request")>=0); }),t.id); if (onCreated) onCreated(t); openTask(t.id); }).catch(function(){}); }
function submitNewTask(){ createDraft(); }
function deleteTask(id){ var linked=TASKS.filter(function(t){return (t.dependencies||[]).some(function(d){return d.taskId===id;});}); var msg=tr("This removes the task, its versions, files and comments. Workspace activity is kept.")+(linked.length?" "+tr("It is currently blocking")+" "+linked.length+" "+tr(linked.length===1?"task":"tasks")+": "+linked.map(function(t){return t.title;}).join(", ")+". "+tr("Their dependency links will be removed."):""); confirmModal(tr("Delete task")+" "+id+"?",msg,function(){ closeDrawer(); deleteTaskById(id).then(function(saved){ if(saved===false)return false; toast(tr("Task deleted"),"bad"); }); },true); }
</script>
