<script>
/* ============================================================
   TEAMS — customizable teams (color, icon, lead, order), multi-membership, drag users between teams, team workload (§6–11, §64)
   ============================================================ */
function teamDoneThisMonth(t){if(!isSuccessfulTask(t))return false;var d=t.completedAt?new Date(t.completedAt):dateOf(t.due);return d.getFullYear()===TODAY.getFullYear()&&d.getMonth()===TODAY.getMonth();}
function renderTeams(){ if (S.teamId) return renderTeamDetail(S.teamId); var ids=Object.keys(PEOPLE).filter(function(k){ return !PEOPLE[k].stakeholder; }); var cap=0, asg=0; ids.forEach(function(id){ cap+=person(id).cap; asg+=assigned(id); }); var ed=canI.manageTeams(),doneMonth=TASKS.filter(teamDoneThisMonth),produced=assetsProduced(doneMonth);
  var h='<div class="pagehead m-head"><div><h1>Teams</h1><div class="muted" style="margin-top:4px">'+activeTeams().length+' teams · '+ids.length+' creatives · '+asg+'h assigned of '+cap+'h capacity'+(ed?'<span class="desktop-only"> · drag a person onto another team card, drag cards to reorder</span>':'')+'</div></div><div class="actions"><button class="btn desktop-only" onclick="exportModal(\'xlsx\')">'+I.download+'Excel</button><button class="btn primary desktop-only" onclick="exportModal(\'ppt\')">'+I.download+'PowerPoint</button>'+(ed?'<button class="btn desktop-only" onclick="go(\'settings\',\'members\')">'+I.user+'Members</button><button class="btn primary m-primary" aria-label="New team" onclick="teamModal()">'+I.plus+'New team</button>':'')+'</div></div>';
  h+='<div class="kpis team-kpis">'+kpi("",activeTeams().length,tr("Teams"),tr("customizable"),"",I.team,"ink")+kpi(asg>cap?"danger":"accent",(cap?Math.round(asg/cap*100):0)+"%",tr("Utilization"),tr("this week"),"",I.analytics,"blue")+kpi("",TASKS.filter(function(t){ return isReview(t); }).length,tr("In review"),tr("across teams"),"",I.eye,"lime")+kpi("",openTasks().length,tr("Open tasks"),tr("all projects"),"go('tasks','list')",I.tasks,"")+kpi("good",doneMonth.length,tr("Done this month"),tr("completed tasks"),"",I.check,"lime")+kpi("accent",produced,tr("Assets produced"),tr("from completed tasks"),"",I.assets,"blue")+'</div>';
  h+='<div class="tgrid">'+activeTeams().map(function(t){ var w=teamWorkload(t.id); var members=teamMembers(t.id); return '<div class="tcard" draggable="'+(ed?"true":"false")+'" data-team="'+t.id+'" ondragstart="tStart(event,\''+t.id+'\')" ondragend="this.classList.remove(\'drag\')" ondragover="event.preventDefault();this.classList.add(\'over\')" ondragleave="this.classList.remove(\'over\')" ondrop="tDrop(event,this,\''+t.id+'\')" onclick="go(\'teams\',\''+t.id+'\')"><div class="th">'+teamIcon(t)+'<div style="min-width:0;flex:1"><div class="tn">'+esc(t.name)+'</div><div class="td">'+esc(t.description||"")+'</div></div>'+(ed?'<button class="iconbtn flat" onclick="event.stopPropagation();teamModal(\''+t.id+'\')" title="Edit team">'+I.edit+'</button>':'')+'</div><div class="ts"><span><b>'+members.length+'</b>people</span><span><b>'+w.open+'</b>open</span><span><b>'+w.pct+'%</b>utilization</span></div><div class="wl" style="padding:0;border:0;grid-template-columns:minmax(0,1fr);--tc:var(--team-'+t.color+')"><div><div class="track '+(w.pct>100?"hot":w.pct>=90?"warm":"")+'" style="margin-top:0"><i style="width:'+Math.min(100,w.pct)+'%"></i></div></div></div><div class="tm">'+members.map(function(id){ var pr=primaryTeam(id)===t.id; return '<span class="mchip" draggable="'+(ed?"true":"false")+'" ondragstart="mStart(event,\''+id+'\',\''+t.id+'\')" ondragend="this.classList.remove(\'drag\')" onclick="event.stopPropagation();go(\'team\',\''+id+'\')" title="'+attr(person(id).name+(pr?" · primary team":""))+'">'+av(id)+esc(first(id))+(pr?'<span class="pr"></span>':'')+(t.lead===id?'<span class="hint">lead</span>':'')+'</span>'; }).join("")+(members.length?'':'<span class="hint">No members yet — drag someone here</span>')+'</div></div>'; }).join("")+'</div>';
  h+='<div class="grid g-2-1">'+panel("Workload by person",null,workloadRows(true),null,null,I.team)+panel("Stakeholders",null,Object.keys(PEOPLE).filter(function(k){ return PEOPLE[k].stakeholder; }).map(function(k){ var p=person(k); return '<div class="member" onclick="go(\'team\',\''+k+'\')">'+av(k,"lg")+'<div><div style="font-weight:600">'+esc(p.name)+'</div><div class="tiny muted">'+esc(p.role)+' · submits requests, sees stakeholder-visible comments</div></div><span class="badge client">viewer</span></div>'; }).join("")||emptyBox("No stakeholders",""),null,null,I.eye)+'</div>';
  document.getElementById("content").innerHTML=h; }
var TDRAG=null, MDRAG=null;
function tStart(e,id){ if (!canI.manageTeams()) return e.preventDefault(); TDRAG=id; MDRAG=null; e.dataTransfer.effectAllowed="move"; e.target.classList.add("drag"); }
function mStart(e,uid_,fromTeam){ if (!canI.manageTeams()) return e.preventDefault(); e.stopPropagation(); MDRAG={user:uid_,from:fromTeam}; TDRAG=null; e.dataTransfer.effectAllowed="move"; e.target.classList.add("drag"); }
function tDrop(e,card,teamId){ e.preventDefault(); e.stopPropagation(); card.classList.remove("over");
  if (MDRAG){ var m=MDRAG; MDRAG=null; if (m.from===teamId) return; var p=person(m.user); var already=teamsOf(m.user).indexOf(teamId)>=0; var mode=e.shiftKey?"add":"move"; if (already&&mode==="add") return toast(first(m.user)+" is already in "+teamName(teamId)); var snap=clone(p.teams);
    if (mode==="move") p.teams=p.teams.filter(function(x){ return x[0]!==m.from; }); if (!already) p.teams.push([teamId,false]); if (!p.teams.some(function(x){ return x[1]; })&&p.teams.length) p.teams[0][1]=true; renderScreen(false); toast(first(m.user)+(mode==="move"?" moved to ":" added to ")+teamName(teamId)+" — hold Shift to add instead of move");
    logWorkspace("member_team","user",m.user,{team:teamId,user:m.user,what:first(m.user)+" → "+teamName(teamId)}); if (API.on) apiFetch("POST","/api/members/"+m.user+"/team",{teamId:teamId,isPrimary:false,fromTeamId:mode==="move"?m.from:null}).then(function(d){ PEOPLE=d; WS.people=PEOPLE; refresh(); }).catch(function(err){ p.teams=snap; refresh(); fail(err,"Couldn't update team membership. "+err.message); }); return; }
  if (TDRAG&&TDRAG!==teamId){ var order=activeTeams(); var mv=byId(order,TDRAG); order.splice(order.indexOf(mv),1); order.splice(order.findIndex(function(t){ return t.id===teamId; }),0,mv); order.forEach(function(t,i){ t.sort=i+1; }); TDRAG=null; renderScreen(false); persistTeamOrder(); } }
function teamModal(id){ var t=id?team(id):{name:"",description:"",color:TEAM_COLORS[activeTeams().length%TEAM_COLORS.length],icon:"palette",lead:null}; window._tm={color:t.color,icon:t.icon}; var isHex=/^#/.test(t.color||"");
  openModal(id?"Edit team":"New team",fieldHtml("tm_name","Name",'<input id="tm_name" value="'+attr(t.name)+'" placeholder="e.g. Photography">')+fieldHtml("tm_desc","Description",'<input id="tm_desc" value="'+attr(t.description||"")+'" placeholder="What this team owns">')+'<div class="field"><label>Color</label><div class="tcolor" id="tm_colors">'+TEAM_COLORS.map(function(c){ return '<button style="background:var(--team-'+c+')" class="'+(c===t.color?"on":"")+'" title="'+c+'" onclick="pickTeamColor(\''+c+'\',this)"></button>'; }).join("")+'<label class="sw custom" title="Custom color" style="width:26px;height:26px"><input type="color" value="'+(isHex?t.color:"#2563EB")+'" oninput="pickTeamColor(this.value,this.parentNode)"></label><span class="hint mono" id="tm_hex">'+esc(t.color)+'</span></div><div class="hint" style="margin-top:6px">Pick a preset or any custom colour. Team colours are indicators only — they tint cards lightly, never the whole UI.</div></div><div class="field"><label>Icon</label><div class="ticons">'+Object.keys(TICONS).map(function(k){ return '<button class="'+(k===t.icon?"on":"")+'" title="'+k+'" onclick="window._tm.icon=\''+k+'\';[].forEach.call(this.parentNode.children,function(b){b.classList.remove(\'on\')});this.classList.add(\'on\');document.getElementById(\'tm_svgpv\').innerHTML=\'\'">'+TICONS[k]+'</button>'; }).join("")+'</div><div style="display:flex;align-items:center;gap:10px;margin-top:10px;flex-wrap:wrap"><button class="btn sm" onclick="pickTeamSvg()">'+I.up+'Upload custom SVG</button><span id="tm_svgpv">'+(/^data:/.test(t.icon||"")?'<span class="ticon sm" style="--tc:'+teamColorCss(t.color)+'"><img src="'+t.icon+'" alt=""></span>':'')+'</span><span class="hint">SVG under 50 KB, square works best — rendered in white on the team colour.</span></div></div>'+fieldHtml("tm_lead","Team lead (optional)",selectHtml("tm_lead",[["","No lead"]].concat(peopleOpts()),t.lead||"")),(id?'<button class="btn danger-soft" onclick="archiveTeam(\''+id+'\')">Archive</button>':'')+'<span class="spacer"></span><button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveTeam('+(id?"'"+id+"'":"null")+')">'+(id?"Save":"Create team")+'</button>'); }
function pickTeamColor(c,btn){ window._tm.color=c; var wrap=document.getElementById("tm_colors"); [].forEach.call(wrap.children,function(b){ b.classList.remove("on"); }); if (btn&&btn.classList) btn.classList.add("on"); document.getElementById("tm_hex").textContent=c; }
function pickTeamSvg(){ var inp=document.getElementById("fileInput"); inp.accept=".svg,image/svg+xml"; inp.onchange=function(){ var f=inp.files[0]; inp.value=""; if (!f) return; if (f.size>51200) return toast("SVG must be under 50 KB","bad"); var rd=new FileReader(); rd.onload=function(){ var svg=String(rd.result); if (/<script/i.test(svg)) return toast("SVG with scripts is not allowed","bad"); var url="data:image/svg+xml;base64,"+btoa(unescape(encodeURIComponent(svg))); window._tm.icon=url; document.getElementById("tm_svgpv").innerHTML='<span class="ticon sm" style="--tc:'+teamColorCss(window._tm.color)+'"><img src="'+url+'" alt=""></span>'; [].forEach.call(document.querySelectorAll(".ticons button"),function(b){ b.classList.remove("on"); }); }; rd.readAsText(f); }; inp.click(); }
function saveTeam(id){ if (!require(["tm_name"])) return; var isNew=!id; var t=isNew?{id:uid("team"),sort:activeTeams().length+1,archived:false}:team(id); var oldColor=t.color; t.name=val("tm_name"); t.description=val("tm_desc"); t.color=window._tm.color; t.icon=window._tm.icon; t.lead=val("tm_lead")||null; if (isNew) TEAMS.push(t); if (isNew&&typeof convEnsureTeamDefaults==="function"&&CHAT_RUNTIME.loaded) convEnsureTeamDefaults(); closeModal(); toast(isNew?"Team created":"Team saved"); refresh(); if (!API.on){ ACTIVITY.unshift(A(ME,isNew?"team_created":(oldColor!==t.color?"team_color":"edited"),0,{team:t.id,what:t.name+(oldColor!==t.color&&!isNew?" color":"")})); } persistTeam(t,isNew); }
function archiveTeam(id){ closeModal(); var n=TASKS.filter(function(t){ return t.team===id; }).length; confirmModal("Archive "+esc(teamName(id))+"?",n+" task"+(n===1?"":"s")+" will lose their team; members keep their other teams.",function(){ var t=team(id); t.archived=true; TASKS.forEach(function(x){ if (x.team===id) x.team=null; }); Object.keys(PEOPLE).forEach(function(u){ PEOPLE[u].teams=(PEOPLE[u].teams||[]).filter(function(x){ return x[0]!==id; }); }); S.teamId=null; toast("Team archived","bad"); refresh(); if (API.on) apiFetch("DELETE","/api/teams/"+id).then(function(list){ TEAMS=list; reloadAll(); }).catch(function(e){ fail(e); reloadAll(); }); },true); }
function renderTeamDetail(id){ var t=team(id); if (!t){ S.teamId=null; return renderTeams(); } var w=teamWorkload(id); var members=teamMembers(id); var tasks=sortTasks(TASKS.filter(function(x){ return x.team===id; })); var open=tasks.filter(function(x){ return !isClosed(x); }); var ed=canI.manageTeams(),doneMonth=tasks.filter(teamDoneThisMonth),produced=assetsProduced(doneMonth);
  var h='<div><button class="btn ghost sm" onclick="go(\'teams\')">'+I.back+'All teams</button></div><div class="pagehead m-head"><div style="display:flex;gap:14px;align-items:center">'+teamIcon(t)+'<div><h1>'+esc(t.name)+'</h1><div class="muted" style="margin-top:4px">'+esc(t.description||"")+(t.lead?' · lead '+esc(person(t.lead).name):'')+'</div></div></div><div class="actions"><button class="btn desktop-only" onclick="exportModal(\'ppt\')">'+I.download+'PowerPoint</button><button class="btn m-icon" aria-label="Board" onclick="S.filters.team=\''+id+'\';S.taskScope=\'all\';go(\'tasks\',\'kanban\')">'+I.kanban+'<span class="m-label">Board</span></button>'+(ed?'<button class="btn m-icon" aria-label="'+attr(tr("Edit team"))+'" onclick="teamModal(\''+id+'\')">'+I.edit+'<span class="m-label">Edit team</span></button>':'')+(canI.createTask()?'<button class="btn primary m-primary" aria-label="'+attr(tr("New task"))+'" onclick="newTaskModal({team:\''+id+'\',assignee:\''+(members[0]||ME)+'\'})">'+I.plus+'New task</button>':'')+'</div></div>';
  h+='<div class="kpis team-kpis">'+kpi(w.pct>100?"danger":w.pct>=90?"warn":"accent",w.pct+"%","Utilization",w.assigned+"h of "+w.cap+"h","",I.analytics,"blue")+kpi("",open.length,"Open tasks","in this team","",I.tasks,"ink")+kpi("",open.filter(isReview).length,"In review","","",I.eye,"lime")+kpi(open.filter(function(x){ return x.due<0; }).length?"danger":"good",open.filter(function(x){ return x.due<0; }).length,"Overdue","","",I.bell,"")+kpi("good",doneMonth.length,"Done this month","completed tasks","",I.check,"lime")+kpi("accent",produced,"Assets produced","this month","",I.assets,"blue")+'</div>';
  h+='<div class="grid g-1-1">'+panel("Members",members.length,members.map(function(m){ var p=person(m); var a=assigned(m); var pct=p.cap?Math.round(a/p.cap*100):0; var pr=primaryTeam(m)===id; return '<div class="member" onclick="go(\'team\',\''+m+'\')">'+av(m,"lg")+'<div style="min-width:0"><div style="font-weight:600">'+esc(p.name)+(pr?' <span class="badge lime" style="background:var(--color-secondary);color:#111">'+tr("primary")+'</span>':' <span class="badge">secondary</span>')+(t.lead===m?' <span class="badge">lead</span>':'')+'</div><div class="tiny muted">'+esc(p.role)+' · '+a+'h / '+p.cap+'h · '+pct+'%</div></div><div style="display:flex;gap:4px">'+(ed?'<button class="btn xs" onclick="event.stopPropagation();setPrimary(\''+m+'\',\''+id+'\')" '+(pr?"disabled":"")+'>Make primary</button><button class="iconbtn flat" style="width:26px;height:26px" onclick="event.stopPropagation();removeFromTeam(\''+m+'\',\''+id+'\')" title="Remove from team">'+I.x+'</button>':'')+'</div></div>'; }).join("")+'<div class="panel-foot" style="gap:8px"><span class="h mono tiny muted">Total <b>'+w.assigned+'h</b> / '+w.cap+'h · utilization '+w.pct+'%</span><span class="spacer"></span>'+(ed?'<button class="btn sm" onclick="addToTeamModal(\''+id+'\')">'+I.plus+'Add member</button>':'')+'</div>',null,null,I.team)+panel("Workload",null,workloadRows(true,members.filter(function(m){ return !PEOPLE[m].stakeholder; })),null,null,I.analytics)+'</div>';
  h+=panel("Team tasks",tasks.length,tasks.length?tasks.map(function(x){ return taskRow(x); }).join(""):emptyBox("No tasks for this team","Assign a team on any task."),null,null,I.tasks);
  document.getElementById("content").innerHTML=h; }
function setPrimary(uid_,teamId){ var p=person(uid_); p.teams.forEach(function(x){ x[1]=x[0]===teamId; }); renderScreen(false); persistMemberTeam(uid_,teamId,true,null); }
function removeFromTeam(uid_,teamId){ var p=person(uid_); p.teams=p.teams.filter(function(x){ return x[0]!==teamId; }); if (p.teams.length&&!p.teams.some(function(x){ return x[1]; })) p.teams[0][1]=true; toast(first(uid_)+" removed from "+teamName(teamId),"bad"); renderScreen(false); removeMemberTeam(uid_,teamId); }
function addToTeamModal(teamId){ var opts=Object.keys(PEOPLE).filter(function(id){ return teamsOf(id).indexOf(teamId)<0; }).map(function(id){ return [id,PEOPLE[id].name]; }); if (!opts.length) return toast("Everyone is already in this team"); openModal("Add member to "+esc(teamName(teamId)),fieldHtml("at_user","Person",selectHtml("at_user",opts,opts[0][0]))+'<label style="display:flex;gap:8px;align-items:center;font-size:var(--fs-sm)"><input type="checkbox" id="at_primary"> Make this their primary team</label>','<button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="var u=val(\'at_user\');var pr=document.getElementById(\'at_primary\').checked;var p=person(u);if(pr)p.teams.forEach(function(x){x[1]=false});p.teams.push([\''+teamId+'\',pr||!p.teams.length]);closeModal();renderScreen(false);persistMemberTeam(u,\''+teamId+'\',pr,null);toast(first(u)+\' added\')">Add</button>'); }
function renderMember(){ var id=S.memberId; var p=PEOPLE[id]; if (!p){ S.memberId=null; return renderTeams(); } var mine=sortTasks(TASKS.filter(function(t){ return isAssignee(t,id); })); var open=mine.filter(function(t){ return !isClosed(t); }); var rev=sortTasks(TASKS.filter(function(t){ return isReviewer(t,id)&&isReview(t); })); var a=assigned(id); var pct=p.cap?Math.round(a/p.cap*100):0; var r=byId(ROLES,p.perm);
  /* v19.5 header: avatar with a hover pencil (photo change / remove), name + a settings shortcut for the owner, and only the title line — details live in Settings → My profile */
  var avatarHtml=canEditPhoto(id)?'<span class="mp-avatar" title="'+attr(tr("Change photo"))+'" onclick="avatarEditMenu(this,\''+id+'\')">'+av(id,"xl")+'<span class="mp-avatar-edit" aria-hidden="true">'+I.edit+'</span></span>':'<span class="mp-avatar">'+av(id,"xl")+'</span>';
  var h='<div><button class="btn ghost sm" onclick="go(\'teams\')">'+I.back+'Teams</button></div><div class="pagehead"><div style="display:flex;gap:14px;align-items:center">'+avatarHtml+'<div><h1 style="display:flex;align-items:center;gap:8px"><span data-no-translate>'+esc(p.name)+'</span>'+(id===ME?'<button class="iconbtn mp-settings" title="'+attr(tr("Edit my profile"))+'" aria-label="'+attr(tr("Edit my profile"))+'" onclick="go(\'settings\',\'profile\')">'+I.settings+'</button>':'')+'</h1><div class="muted" style="margin-top:4px;display:flex;gap:6px;flex-wrap:wrap;align-items:center">'+esc(p.role)+' · <span class="badge">'+esc(r?r.name:p.perm)+'</span> · '+(p.teams||[]).map(function(x){ return teamBadge(x[0])+(x[1]?'<span class="hint">'+tr("primary")+'</span>':''); }).join(" ")+'</div></div></div><div class="actions">'+(canI.manageMembers()||id===ME?'<label class="pillsel"><span>Capacity</span><input type="number" min="0" value="'+p.cap+'" style="width:56px;border:0;background:transparent;font-weight:600;outline:none" onchange="PEOPLE[\''+id+'\'].cap=+this.value;renderScreen(false);persistPerson(\''+id+'\')"><span>h / week</span></label>':'')+(canI.manageMembers()?'<button class="btn" onclick="go(\'settings\',\'members\')">'+I.edit+'Edit member</button>':'')+'</div></div>';
  h+='<div class="kpis kpis-4">'+kpi(pct>100?"danger":pct>=90?"warn":"accent",pct+"%","Utilization",a+"h of "+p.cap+"h","",I.analytics,"blue")+kpi("",open.length,"Open tasks","assigned","",I.tasks,"ink")+kpi("",rev.length,"To review","as reviewer","",I.eye,"lime")+kpi(open.filter(function(t){return t.due<0;}).length?"danger":"good",open.filter(function(t){return t.due<0;}).length,"Overdue","","",I.bell,"")+'</div>';
  h+='<div class="grid g-2-1">'+panel("Assigned tasks",open.length,open.length?open.map(function(t){ return taskRow(t,{showAssignee:false}); }).join(""):emptyBox("Nothing assigned","Free capacity — assign something from the board."),null,null,I.tasks)+panel("Reviewing",rev.length,rev.length?rev.map(function(t){ return taskRow(t,{showStatus:false}); }).join(""):emptyBox("Nothing to review",""),null,null,I.eye)+'</div>';
  h+=panel("Completed",mine.filter(function(t){return isClosed(t);}).length,mine.filter(function(t){return isClosed(t);}).slice(0,12).map(function(t){ return taskRow(t,{showAssignee:false}); }).join("")||emptyBox("No completed tasks yet",""),null,null,I.check);
  document.getElementById("content").innerHTML=h; }
/* v19.5 avatar pencil: change or remove the photo from one small menu */
function avatarEditMenu(a,id){ if(!canEditPhoto(id)) return; if(!person(id).avatar) return pickAvatar(id); ctxMenu(a,'<button onclick="closePops();pickAvatar(\''+id+'\')">'+I.up+tr("Change photo")+'</button><button onclick="closePops();removeAvatar(\''+id+'\')">'+I.trash+tr("Remove photo")+'</button>'); }
</script>
